### ISSUE TITLE
Debug symbols

### ISSUE THREAD

**Issue by xsleonard** [tpoechtrager/osxcross#1]
What would it take to get debug info working?  I am trying to cross compile go+cgo which relies on DWARF abbrev, info and str fields for linking go with the object files

**Comment by tamird** [comment]
This issue should probably be reopened, since debug info still doesn't work.

**Comment by tpoechtrager** [comment]
@tamird: Debug info works: https://github.com/tpoechtrager/osxcross/blob/master/README.DEBUGGING.md.
