### ISSUE TITLE
compile from windows

### ISSUE THREAD

**Issue by LogicalError** [tpoechtrager/osxcross#101]
How hard would it be to compile for mac OS X and Linux with clang from windows instead?

**Comment by tpoechtrager** [comment]
Already possible. See https://github.com/tpoechtrager/osxcross/blob/master/README.CYGWIN.md.

**Comment by AraHaan** [comment]
What if I need to update all of the clang and gcc stuff to the latest ones? like clang 3.9.1 and gcc to 6.3.0?

**Comment by msink** [comment]
Would be great if it can be built using [MSYS2](https://msys2.github.io) instead of CYGWIN - it is much more recent versions, installable from command line...

**Comment by tpoechtrager** [comment]
> What if I need to update all of the clang and gcc stuff to the latest ones? like clang 3.9.1 and gcc to 6.3.0?

Build the compiler on your own.

> Also mind adding steps to install those things using the command line as it is hard to see with an list to select them from.

Cygwin does not support installing packages via the command line. It is already as easy as it can get.

> Would be great if it can be built using MSYS2 instead of CYGWIN - it is much more recent versions, installable from command line...

OSXCross is not a native Windows application and never will be.

**Comment by msink** [comment]
> OSXCross is not a native Windows application and never will be.

Yes, but MSYS2 is not native Windows.
It is modern fork of CYGWIN, but already with gcc 6.3.0, and packages are installed via the command line.
Sadly OSXcros does not recognize it as CYGWIN variant.

**Comment by tpoechtrager** [comment]
I will add support for it if you can convince the MSYS2 developers to build their GCC with objective-c support enabled.

**Comment by AraHaan** [comment]
@tpoechtrager Yeah, I could build it on my own but gcc 6.3.0 can now be downloaded from the installer. However sadly CYGWIN does not include ``<experimental/filesystem>`` which is really needed for many C++ 14 projects. And that is really the only thing missing is the filesystem stuff. I even tried building it myself on that filesystem thing manually and it still does the same thing.

**Comment by donbright** [comment]
some might find it easier to use Windows 10  'bash on ubuntu on windows', which works pretty much like an ubuntu inside of windows, including apt-get install inside a bash terminal. the linux instructions should apply directly.

**Comment by anb0s** [comment]
I have MSYS2 as supported environment for windows at company and just want to ask if somebody already tweaked osxcross to compile with it? Thanks in advance.

**Comment by tpoechtrager** [comment]
Still waiting for a GCC with objective-c support.

**Comment by anb0s** [comment]
Thanks. I know it's not yet supported, but just tried to see how far it brings me...

I've installed all the packages described in README.CYGWIN.md and additionally Clang and GCC with objective-c support in MSYS2 for x86_64:
`pacman -S mingw-w64-x86_64-clang mingw-w64-x86_64-gcc-objc`

and x86:
`pacman -S mingw-w64-i686-clang mingw-w64-i686-gcc-objc`

The Clang version is:
```
$ clang --version
clang version 3.9.1 (tags/RELEASE_391/final)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:\msys64\mingw64\bin

```

The GCC:
```
$ gcc --version
gcc.exe (Rev2, Built by MSYS2 project) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

build.sh starts with:

```
$ ./build.sh
found SDK version 10.9 at tarballs/MacOSX10.9.sdk.tar.xz
verified at tarballs/MacOSX10.9.sdk.tar.xz

Building OSXCross toolchain, Version: 0.15

OS X SDK Version: 10.9, Target: darwin13
Minimum targeted OS X Version: 10.5

```

I see lot of checking messages, specially this one:
`checking whether we are using the GNU Objective C compiler... yes`

The config phase does not report any errors and the compiling starts:
`Making all in libstuff`

but has compile errors:

```
libtool: compile:  clang -DPACKAGE_NAME=\"cctools\" -DPACKAGE_TARNAME=\"cctools\" -DPACKAGE_VERSION=\"895\" "-DPACKAGE_STRING=\"cctools 895\"" -DPACKAGE_BUGREPORT=\"t.poechtrager@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -DEMULATED_HOST_CPU_TYPE=16777223 -DEMULATED_HOST_CPU_SUBTYPE=3 -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -I. -I../include -I../include/foreign -D__DARWIN_UNIX03 -Wall -Wno-long-long -Wno-import -Wno-format -Wno-deprecated -Wno-unused-variable -Wno-unused-private-field -Wno-unused-function -Wno-invalid-offsetof -Wno-int-conversion -Wno-char-subscripts -Wno-shift-negative-value -DPROGRAM_PREFIX=\"x86_64-apple-darwin13-\" -D__LITTLE_ENDIAN__=1 -O3 -isystem /usr/local/include -isystem /usr/pkg/include -DDISABLE_CLANG_AS -c dylib_table.c  -DDLL_EXPORT -DPIC -o .libs/libstuff_la-dylib_table.o
dylib_roots.c:32:10: fatal error: 'fts.h' file not found
#include <fts.h>
         ^
libtool: compile:  clang -DPACKAGE_NAME=\"cctools\" -DPACKAGE_TARNAME=\"cctools\" -DPACKAGE_VERSION=\"895\" "-DPACKAGE_STRING=\"cctools 895\"" -DPACKAGE_BUGREPORT=\"t.poechtrager@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -DEMULATED_HOST_CPU_TYPE=16777223 -DEMULATED_HOST_CPU_SUBTYPE=3 -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -I. -I../include -I../include/foreign -D__DARWIN_UNIX03 -Wall -Wno-long-long -Wno-import -Wno-format -Wno-deprecated -Wno-unused-variable -Wno-unused-private-field -Wno-unused-function -Wno-invalid-offsetof -Wno-int-conversion -Wno-char-subscripts -Wno-shift-negative-value -DPROGRAM_PREFIX=\"x86_64-apple-darwin13-\" -D__LITTLE_ENDIAN__=1 -O3 -isystem /usr/local/include -isystem /usr/pkg/include -DDISABLE_CLANG_AS -c fatal_arch.c  -DDLL_EXPORT -DPIC -o .libs/libstuff_la-fatal_arch.o
crc32.c:61:14: error: unknown type name 'u_int32_t'; did you mean 'uint32_t'?
static const u_int32_t crctab[] = {
             ^~~~~~~~~
             uint32_t
D:\msys64\mingw64\x86_64-w64-mingw32\include\stdint.h:40:20: note: 'uint32_t' declared here
typedef unsigned   uint32_t;
                   ^
crc32.c:125:20: error: unknown type name 'u_char'; did you mean 'char'?
    register const u_char *p;
                   ^~~~~~
                   char
crc32.c:127:14: error: unknown type name 'u_int32_t'; did you mean 'uint32_t'?
    register u_int32_t crc;
             ^~~~~~~~~
             uint32_t
D:\msys64\mingw64\x86_64-w64-mingw32\include\stdint.h:40:20: note: 'uint32_t' declared here
typedef unsigned   uint32_t;
                   ^
3 errors generated.
make[1]: *** [Makefile:471: libstuff_la-crc32.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
port.c:45:10: fatal error: 'sys/mman.h' file not found
#include <sys/mman.h>
         ^
dylib_table.c:29:10: fatal error: 'sys/mman.h' file not found
#include <sys/mman.h>
         ^
1 error generated.
make[1]: *** [Makefile:474: libstuff_la-dylib_roots.lo] Error 1
1 error generated.
make[1]: *** [Makefile:480: libstuff_la-port.lo] Error 1
execute.c:28:10: fatal error: 'sys/wait.h' file not found
#include <sys/wait.h>
         ^
1 error generated.
1 error generated.
make[1]: *** [Makefile:486: libstuff_la-execute.lo] Error 1
make[1]: *** [Makefile:477: libstuff_la-dylib_table.lo] Error 1
libtool: compile:  clang -DPACKAGE_NAME=\"cctools\" -DPACKAGE_TARNAME=\"cctools\" -DPACKAGE_VERSION=\"895\" "-DPACKAGE_STRING=\"cctools 895\"" -DPACKAGE_BUGREPORT=\"t.poechtrager@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DLT_OBJDIR=\".libs/\" -DEMULATED_HOST_CPU_TYPE=16777223 -DEMULATED_HOST_CPU_SUBTYPE=3 -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -I. -I../include -I../include/foreign -D__DARWIN_UNIX03 -Wall -Wno-long-long -Wno-import -Wno-format -Wno-deprecated -Wno-unused-variable -Wno-unused-private-field -Wno-unused-function -Wno-invalid-offsetof -Wno-int-conversion -Wno-char-subscripts -Wno-shift-negative-value -DPROGRAM_PREFIX=\"x86_64-apple-darwin13-\" -D__LITTLE_ENDIAN__=1 -O3 -isystem /usr/local/include -isystem /usr/pkg/include -DDISABLE_CLANG_AS -c fatals.c  -DDLL_EXPORT -DPIC -o .libs/libstuff_la-fatals.o

```

Just to give you my investigations so far...

**Comment by tpoechtrager** [comment]
`mingw-w64-x86_64-*` targets MinGW-w64. I need a GCC with objective-c support for MSYS2.

I will try to find a way once I am done adding TAPIv2 support to OSXCross.

**Comment by anb0s** [comment]
OK, i see, thanks!

**Comment by tpoechtrager** [comment]
Cygwin/Windows is no longer supported by OSXCross.

**Comment by ZhenFTW** [comment]
Is it still not supported this 2019?

**Comment by tpoechtrager** [comment]
It is no longer possible to build OSXCross on Windows. You may want to use WSL (Windows Subsystem for Linux) or a Virtual Machine instead.

**Comment by ZhenFTW** [comment]
Im on windows 8 and WSL is not available. Is my only option is using Virtual machine ? Or do you think there are good alternatives for WSL? I wish you support cygwin. Building executable is nice as i can  run it without installing another software.

**Comment by tpoechtrager** [comment]
A VM is your only option. Sorry.
