### ISSUE TITLE
Compilation issues with GCC fortran 

### ISSUE THREAD

**Issue by abb58** [tpoechtrager/osxcross#107]
Hey ! I have gone through the instructions to build a GCC cross compiler for C, C++ and fortran and not sure where things went wrong. I was testing the a helloworld example in fortran using both static and dynamic linking and both gave me issues.
```
$ target/bin/x86_64-apple-darwin15-gfortran -ffree-form helloworld.f -o hellworldF
collect2: fatal error: cannot find 'nm'
compilation terminated.

$ target/bin/x86_64-apple-darwin15-gfortran -static-libgcc -static-libgfortran -ffree-form helloworld.f -o hellworldF
collect2: fatal error: cannot find 'nm'
compilation terminated.
```
I also tested for helloworld in C and C++ using gcc and g++ variants and didn't have much of success.
```
x86_64-apple-darwin15-gcc: error trying to exec 'cc1': execvp: No such file or directory
x86_64-apple-darwin15-g++: error trying to exec 'cc1': execvp: No such file or directory
```
Appreciate any pointers !

**Comment by tpoechtrager** [comment]
Is `target/bin` in `PATH`?

**Comment by abb58** [comment]
Thanks for the prompt response. I did forget to update the PATH variable. It works now. 

Appreciate that!
