### ISSUE TITLE
osxcross toolchain failing at "OpenSSL_add_all_ciphers" check

### ISSUE THREAD

**Issue by codedump** [tpoechtrager/osxcross#109]
Hello everybody,

my toolchain compiling attempt fails when trying to build xar:

> extracting xar-1.5.2.tar.gz ...
> 
> checking for gcc... clang
> [...]
> checking openssl/evp.h usability... yes
> checking openssl/evp.h presence... yes
> checking for openssl/evp.h... yes
> checking for OpenSSL_add_all_ciphers in -lcrypto... no
> configure: error: Cannot build without libcrypto (OpenSSL)
> 
> exiting with abnormal exit code (1)
> run 'OCDEBUG=1 ./build.sh' to enable debug messages
> removing stale locks...
> if it is happening the first time, then just re-run the script

Re-running the script won't fix the issue.

I'm trying to compile on a fresh Debian 9.0 (current 'testing', almost 'stable'). OpenSSL version installed is 1.1.0e-1 (the -1 might be a Debian thing). Apparently, OpenSSL_add_all_ciphers is deprecated in OpenSSL v1.1.

I don't know if this is relevant (was in: where does xar come from? Is it extracted from the Xcode package?), but I was trying to build the osxcross chain for a 10.6 MacOS SDK, from an fairly old Xcode-3.2.6, from some time in 2011. If xar is indeed extracted from the SDK, then I figure it's probably a version incompatiblity between an impossibly old xar and the current OpenSSL, right?

Any ideas?

Thanks in advance

**Comment by tpoechtrager** [comment]
Should be fixed.
