### ISSUE TITLE
Output Linux binary from source targeting Darwin/OSX

### ISSUE THREAD

**Issue by diatech** [tpoechtrager/osxcross#110]
HI,

I am porting some OS X code to Linux. The source is using latest version of GCD/XPC.  I tried libdispatch Linux port, but it is still too old and its very tricky to setup cland/llvm tool chain as well. I am wonder if I can use this tool chain output Linux binary from a program using GCD/XPC from Mac.

Thanks!

**Comment by tpoechtrager** [comment]
Not possible due to incompatible headers and libraries.
