### ISSUE TITLE
The wrapper breaks passed arguments that contain quotes

### ISSUE THREAD

**Issue by pedronavf** [tpoechtrager/osxcross#117]
ICU's build system adds `-MT "stubdata.d stubdata.o stubdata.ao"` but when parsing arguments the C library removes the quotes, resulting in the wrapper output being `-MT stubdata.d stubdata.o stubdata.ao`, which break the compile because of invalid parameters passed to clang.

Pull request #115 fixes that by adding the quotes back.

**Comment by tpoechtrager** [comment]
What OS are you on? Adding back quotes should not be required.

**Comment by pedronavf** [comment]
Linux, but we are using the icecream distributed compiler that wraps the compiler in a shell script. Probably the shell script is stripping the quotes and passing `stubdata.d stubdata.o stubdata.ao` as a single argument when it does the exec call...
Do you think the shell script should be escaping the quotes instead?

**Comment by tpoechtrager** [comment]
Yes. Try:

    #!/usr/bin/env bash
    o32-clang ${1+"$@"}

**Comment by pedronavf** [comment]
I had something similar to escape the quotes, I'll try your approach though, but I was wondering if you wanted the wrapper to handle these situations if they ever pop up again, that's why I submitted the pull request. If it's preferred that the caller takes care on escaping the arguments that's fine.

**Comment by pedronavf** [comment]
I agree that is better to let the caller handle quotes so I'm closing this.
