### ISSUE TITLE
Extracting MacOSX10.6.pkg fails with "bzip2 support not compiled in"

### ISSUE THREAD

**Issue by SolraBizna** [tpoechtrager/osxcross#118]
Running `build.sh` on my Debian laptop resulted in this:

    extracting MacOSX10.6.pkg ...
    Error while extracting archive:(Bom): bzip2 support not compiled in. (Success)

I was able to fix this by installing the `libbz2-dev` package. It seems that xar's build process will plug along happily without bzip2 support if the relevant library isn't already installed. It would be good if there were a more informative error message, earlier in the build process, when this situation has occurred.

**Comment by lostiniceland** [comment]
I am seeing this issue despite having libbz2-devel (Suse) installed (both 32 and 64).

Those are the files being installed, the version of bzip2 is 1.0.8
```
/usr/include/bzlib.h
/usr/lib64/libbz2.so
/usr/lib64/pkgconfig/bzip2.pc
/usr/share/doc/packages/libbz2-devel
/usr/share/doc/packages/libbz2-devel/CHANGES
/usr/share/licenses/libbz2-devel
/usr/share/licenses/libbz2-devel/LICENSE
```

Any idea what might be missing?
