### ISSUE TITLE
Please add "short" symlinks for all tools in `bin/`

### ISSUE THREAD

**Issue by htgoebel** [tpoechtrager/osxcross#119]
"Short" symlinks like `o32-strip`, `o64-strings`, `o64h-ar` are missing in `bin/`. Please add them to simplify setup.

** Background**

I have a [project](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/Vagrantfile) using [waf](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/Vagrantfile) as build-system. The wscript-file (which is the analog to `configure` and the Makefile) tries to find `strip`.

When passing the compiler to `waf` (as required for cross-building) like this
```
python ./waf all CC=o32-clang
```
it fails with
```
  Checking for program 'o32-strip'         : not found 
  Could not find the program ['o32-strip']
```
The reason for this is, that there are no symlinks for `o32-strip` and `o64-strip` in `bin/`. So I need to use
```
python ./waf all CC=i386-apple-darwin15-clang
```
which is not only ugly but also over-specified (I don't care about the Darwin platform number).

**Comment by tpoechtrager** [comment]
The `o32-` and `o64-` symlinks are only meant to be used for quick testing. Consider using `xcrun <tool>` instead.
