### ISSUE TITLE
build_gcc fails for gcc 6.4

### ISSUE THREAD

**Issue by lemzwerg** [tpoechtrager/osxcross#122]
After some minutes the script aborts with

```
checking for x86_64-apple-darwin15-gcc... /home/wl/git/osxcross/build/gcc-6.4.0/build/./gcc/xgcc -B/home/wl/git/osxcross/build/gcc-6.4.0/build/./gcc/ -B/home/wl/git/osxcross/target/bin/../x86_64-apple-darwin15/bin/ -B/home/wl/git/osxcross/target/bin/../x86_64-apple-darwin15/lib/ -isystem /home/wl/git/osxcross/target/bin/../x86_64-apple-darwin15/include -isystem /home/wl/git/osxcross/target/bin/../x86_64-apple-darwin15/sys-include   
checking for suffix of object files... configure: error: in `/home/wl/git/osxcross/build/gcc-6.4.0/build/x86_64-apple-darwin15/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
Makefile:11763: recipe for target 'configure-target-libgcc' failed
```

**Comment by lemzwerg** [comment]
The same happens for me with building gcc 6.2 and 6.3.

Strange.

What data do yo need for analyzing the issue?  On my openSuSE GNU/Linux box, I have gcc 4.8.5, clang 3.8.0, and I use MaxOSX10.11.sdk.tar.xz together with current git of osxcross (6c5ff420).

**Comment by tpoechtrager** [comment]
I am able to build 6.4.0 and 7.1.0 without any problems. Check config.log.

**Comment by lemzwerg** [comment]
OK, my mistake.  I see the following
```
/home/wl/git/osxcross/target/bin/../bin/x86_64-apple-darwin15-as: assembler (/home/wl/git/osxcross/target/bin/
../libexec/as/x86_64/as or /home/wl/git/osxcross/target/bin/../local/libexec/as/x86_64/as) for architecture x8
6_64 not installed
/home/wl/git/osxcross/target/bin/../bin/x86_64-apple-darwin15-as: no assemblers installed
```

**Comment by lemzwerg** [comment]
I think I've found the reason: 'as' is installed in `.../git/osxcross/target/lib/as/x86_64/as`, but your script searches in `.../target/libexec` instead.  Maybe a specific 'feature' of the selected SDK?

I'll try to create a symlink.

**Comment by tpoechtrager** [comment]
You must be doing something wrong. You are the first one to report this.

How did you build OSXCross and how are you building GCC? (Path + the exact commands.)

**Comment by lemzwerg** [comment]
I've restarted a complete build from scratch with a cleaned-up git repository (`git clean -fdx`) using the following steps. Note that I don't have any Macports files on my computer.  The git repository is located at `/home/wl/git/osxcross`.

* Copy `MaxOSX10.11.sdk.tar.xz` into `tarballs`.
* Run `./build.sh`.  And indeed, I only get `target/lib/as/` and not `target/libexec/as/`.
* Do `s/.bz2/.xz/` in `build_gcc.sh`, then run `GCC_VERSION=6.4.0 ./build_gcc.sh`.

Attached are the log files.
[build.zip](https://github.com/tpoechtrager/osxcross/files/1220037/build.zip)
[build_gcc.zip](https://github.com/tpoechtrager/osxcross/files/1220039/build_gcc.zip)

**Comment by HinTak** [comment]
Hi @lemzwerg ! Just wonder why gcc, and also a somewhat old one?

Anyway, as you know I have a cross 4.2.1/llvm? setup with SDK 10.5, and looking at updating only the cross compiler part, to use gcc 5+ (or more recent clang ) feature for the freetype backend.

**Comment by lemzwerg** [comment]
@HinTak, you consider gcc 6.4 old?  This is the latest stable release.  I first suspected a problem with the 6.4 release (which is more recent than `build_gcc.sh`), so I tried both 6.3 and 6.2 later on.

I got a report that the clang binary of (TTY) ttfautohint doesn't run on OS X 10.5, immediately crashing (while working on OS X 10.9) – this shouldn't happen since I resolve all dependencies by compiling minimum versions of HarfBuzz and FreeType manually.  However, I then remembered that HarfBuzz is written in C++, and the osxcross documentation talks about issues with older C++ libraries, recommending to use gcc...

**Comment by lemzwerg** [comment]
... I've just discovered the following in cctool's log file:
```
configure:2325: loading site script /usr/share/site/x86_64-unknown-linux-gnu
| #!/bin/sh
| # Site script for configure. It is resourced via $CONFIG_SITE environment varaible.
| 
[...]
| # If user did not specify libexecdir, set the correct target:
| # Nor FHS nor openSUSE allow prefix/libexec. Let's default to prefix/lib.
| 
| if test "$libexecdir" = '${exec_prefix}/libexec' ; then
|       libexecdir='${exec_prefix}/lib'
| fi
```

In other words, the problem seems to be specific to openSuSE (I'm running Leap 42.2).

**Comment by HinTak** [comment]
But OS X 10.5 was largely still ppc based! Apple only started to support x86 hardware with 10.6. If you are trying to run ttfautohint on genuine apple hardware running 10.5, you likely need to build for 32-bit powerpc arch?

**Comment by lemzwerg** [comment]
* 10.5 is the default deployment version of osxcross.
* Support for x32 architecture was added in 10.4.4.
* osxcross doesn't support PPC.

It's not clear to me what you are arguing...

**Comment by lemzwerg** [comment]
Adding the soft link `libexec/as->lib/as` made the compilation of gcc 6.4 succeed – and it seems to work also :-)

The only thing which probably confuses a novice is the strange behaviour if you call the compiler without any arguments:
```
> PATH=/home/wl/git/osxcross/target/bin:$PATH o64-gcc
Undefined symbols for architecture x86_64:
  "_main", referenced from:
      start in crt1.10.5.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```
Any chance to suppress or improve this?

**Comment by HinTak** [comment]
If you have a report about ttfautohint not running on machine having 10.5, that machine is likely a powerpc hardware. That's a likely reason of not upgrading the OS for the hardware, since later OS dropped support for that hardware.

**Comment by HinTak** [comment]
Does os x cross not support ppc? I thought it is more a properto of the assembler - I.e. cctools and binutils?

**Comment by lemzwerg** [comment]
@HinTak, my friend is using 10.5.8 on an Intel platform – due to unfortunate circumstances he is no longer able to compile ttfautohint for me (which he always did in the last few years).  Alas, the universal binary which I now create with osxcross runs successfully on 10.9 but segfaults on his 10.5.8 box...

BTW, the segfault happens regardless the compiler clang or gcc, but it was good to eliminate one possible culprit.

**Comment by HinTak** [comment]
harfbuzz itself doesn't use c++ I think, but ttfautohint does. (at least that's how ttfautohint on linux depends). 
The apple equivalent of ldd is otool - it is a bit more powerful than ldd too:

darwinx-otool -L /usr/darwinx/SDKs/MacOSX10.5.sdk/usr/X11/lib/libpng.dylib
/usr/darwinx/SDKs/MacOSX10.5.sdk/usr/X11/lib/libpng.dylib:
	/usr/X11/lib/libpng.3.dylib (compatibility version 39.0.0, current version 39.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.3)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)

You probably want to run it against your segfault binary to see what libraries it depends on and what minimum versions it actually wants . (the compatibility part).

FWIW, fedora 26 ships "gcc version 7.1.1 20170622 (Red Hat 7.1.1-3) (GCC)" as native, the mingw cross tool chains reports itself as "gcc version 7.1.0 20170502 (Fedora MinGW 7.1.0-1.fc26) (GCC)", while my current darwin cross reports itself as "gcc version 4.2.1 (Apple Inc. build 5664)" . So I'd likely upgrade to a 7.1.x to stay in sync. fedora ships clang 4.0.0 .

**Comment by lemzwerg** [comment]
Well, the abovementioned TTY version of ttfautohint compiled with osxcross's gcc has the smallest possible dependencies:
```
ttfautohint (architecture x86_64):
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
ttfautohint (architecture i386):
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```
Since a native compilation on 10.5.8 worked fine half a year ago I suspect that either there is a bug somewhere in the cross compilation toolchain, or one of the statically linked stuff (FreeType, HarfBuzz, gnulib) got a change that triggers the segfault...

**Comment by lemzwerg** [comment]
BTW, HarfBuzz is written in C++.

**Comment by tpoechtrager** [comment]
> Any chance to suppress or improve this?

> Well, the abovementioned TTY version of ttfautohint compiled with osxcross's gcc has the smallest possible dependencies:

I am linking `libgcc` and `libstdc++` statically by default to avoid troubles. You can disable that behavior with `export OSXCROSS_GCC_NO_STATIC_RUNTIME=1`.

For the `as` issue you could try `USE_CLANG_AS=1 ./build.sh` as a workaround.

**Comment by HinTak** [comment]
I suppose harfbuzz does extern C everywhere - it does not depends on libstdc++ on linux.

**Comment by tpoechtrager** [comment]
It's C with classes. https://github.com/behdad/harfbuzz/tree/master/src

**Comment by lemzwerg** [comment]
OK, thanks.

What I now need is a guy who has an Intel OS 10.5.x box, and who is willing to test my ttfautohint binary (compiled with debugging symbols) within a debugger, to further explore the segfault...

**Comment by HinTak** [comment]
You think this relevant about sticking with libc++ 4.2 ?
 https://stackoverflow.com/questions/35599150/apple-clang-using-c11-with-libstdc

**Comment by lemzwerg** [comment]
I don't think so.  My friend was now able to produce a working binary on 10.5.8 (with Apple's gcc 4.0.1 compiler, which is the default on 10.5.8 – this is *not* a C11 compiler), using exactly the same source code as used for cross compiling.  This seems to rule out a source code issue.  @tpoechtrager, what do you recommend to get relevant information to find a solution?

**Comment by HinTak** [comment]
FYI, I have managed put clang 4.0 and gcc 6.2 next to my old cross-compile framework based on 10.5 SDK - I found an anomaly with the SDK's stdint.h header. It works for g++ but not clang++. So it could be code-related since g++ and clang++ use different stdint.h . I shall file a separate issue but feel free to listen in.

**Comment by HinTak** [comment]
I filed https://github.com/tpoechtrager/osxcross/issues/126 for the stdint.h issue.

**Comment by HinTak** [comment]
I managed to build gcc 7.2 (out a week ago) yesterday.

**Comment by tpoechtrager** [comment]
Closing this. @lemzwerg's issue will be solved by mail.
