### ISSUE TITLE
Use with makefiles

### ISSUE THREAD

**Issue by danmolitor** [tpoechtrager/osxcross#123]
I'm currently working on a project with different makefiles per OS. Let's just say for this instance we only have a makefile for OS X and a makefile for Linux. 

Is the idea that I would use osxcross with the Linux makefile and it would compile into something usable by OS X? Or would I still compile using the OS X makefile?

**Comment by HinTak** [comment]
It is likely a combination of both - you need a new makefile for cross-compilation.

**Comment by danmolitor** [comment]
What would need to change besides just setting the CXX / CC flag?

**Comment by HinTak** [comment]
depends on how complicated your Makefile is, really. Some runs shell commands for pkg-config to set include and lib flags, for example.

**Comment by danmolitor** [comment]
The problem I'm running into is that I'm getting:

`fatal error: 'openssl/bn.h' file not found`

OpenSSL is in /usr/include. If I run the Linux make normally, everything works fine.

But I've tried using x86_64-apple-darwin15-clang++-gstdc++, x86_64-apple-darwin15-clang++, x86_64-apple-darwin15-gcc, and others. 

Is there something different with these compilers when it comes to paths?

**Comment by HinTak** [comment]
You need to cross-compile openssl first and put the cross-compiled version of openssl where your cross-compiler can find it, if your software depends on it.

Basically if you software depends on any libraries, you need to cross-compile and provide those libraries too, because attempting to cross-compile your software.

**Comment by tpoechtrager** [comment]
Or use `osxcross-macports`. https://github.com/tpoechtrager/osxcross/blob/master/README.MACPORTS.md

**Comment by danmolitor** [comment]
I think we still need compatibility with osx 10.5, and osxcross-macports I guess requires 10.7 preferably. I'll see what works. Thanks!
