### ISSUE TITLE
unpatched llvm-dsymutil killed by signal 11, patch submitted upstream?

### ISSUE THREAD

**Issue by HinTak** [tpoechtrager/osxcross#125]
Probably nothing to act on, just posting this so that you are aware of it.
https://bugzilla.redhat.com/show_bug.cgi?id=1483261

**Comment by HinTak** [comment]
I got another 4 of those running `GCC_VERSION=6.4.0 ./build_gcc.sh`

**Comment by HinTak** [comment]
Got 6 of those with gcc 7.2

**Comment by HinTak** [comment]
@tpoechtrager "side-stream" at fedora asked ( https://bugzilla.redhat.com/show_bug.cgi?id=1483261#c16 ) whether you have tried submmitting https://github.com/tpoechtrager/llvm-dsymutil/commit/5e0fea25.patch to upstream?

**Comment by tpoechtrager** [comment]
No, I haven't submitted my patch upstream because Apple's `llvm-dsymutil` doesn't crash for some reason.

**Comment by Keno** [comment]
At least the first half of that patch seems certainly applicable, esp since the previous block explicitly checks for that field being non-null. I can submit this upstream for you if you want.

**Comment by tpoechtrager** [comment]
Would be great. Thanks!

**Comment by Keno** [comment]
https://reviews.llvm.org/D39336

**Comment by Keno** [comment]
Committed upstream
