### ISSUE TITLE
fedora's gcc 7 hides libgcc_s and all the libstdc++ bits for its private use.

### ISSUE THREAD

**Issue by HinTak** [tpoechtrager/osxcross#127]
I want to run this change through you to see what you think, and perhaps tidy it up and merge some of it.
Refering to my https://github.com/HinTak/osxcross/tree/fedora26-working fork, which is all the stuff I did to make it work on fedora 26, against an existing 10.5 SDK which I want to re-use.

So the whole changes : 
https://github.com/HinTak/osxcross/commit/f2a52a82081552e08a54b9c54d7a9f5d5a2c5c2e

consists of two parts you can ignore:

- it removes all the SDK unpack,adjusting part, since I want to re-use an existing SDK (see also https://github.com/tpoechtrager/osxcross/issues/126, however)

- I also have xar from the distro; no need to build my own.

Now, the two main problems are

- fedora's gcc 7 and libc++ has a rather strange layout: the *.a and *.so are hidden in the gcc-specific directory like this:

```
/usr/lib/libstdc++.so.6
/usr/lib/libstdc++.so.6.0.24
/usr/lib/gcc/i686-redhat-linux/7/libstdc++.a
/usr/lib/gcc/i686-redhat-linux/7/libstdc++.so
/usr/lib/gcc/i686-redhat-linux/7/libstdc++fs.a
/usr/lib/gcc/x86_64-redhat-linux/7/libstdc++.a
/usr/lib/gcc/x86_64-redhat-linux/7/libstdc++.so
/usr/lib/gcc/x86_64-redhat-linux/7/libstdc++fs.a
/usr/lib/gcc/x86_64-redhat-linux/7/32/libstdc++.a
/usr/lib/gcc/x86_64-redhat-linux/7/32/libstdc++.so
/usr/lib/gcc/x86_64-redhat-linux/7/32/libstdc++fs.a
/usr/lib64/libstdc++.so.5
/usr/lib64/libstdc++.so.5.0.7
/usr/lib64/libstdc++.so.6
/usr/lib64/libstdc++.so.6.0.24
```

and likewise for the c++ headers:

```
/usr/include/c++/7/i686-redhat-linux/bits/c++config.h
/usr/include/c++/7/x86_64-redhat-linux/32/bits/c++config.h
/usr/include/c++/7/x86_64-redhat-linux/bits/c++config.h
```
hence I have to add -I and -L in various places. But that feels really wrong to get clang to look inside gcc's private directories...

- try to get stdint.h where clang can find it, without touching the SDK ( https://github.com/tpoechtrager/osxcross/issues/126 )

So I guess this issue is mainly about what do you think on how to cope with the clang using stuff in gcc's private directory?

**Comment by HinTak** [comment]
The bare version-less libgcc_s is also hidden from clang!
```
/usr/lib/libgcc_s-7-20170622.so.1
/usr/lib/libgcc_s.so.1
/usr/lib/gcc/x86_64-redhat-linux/7/libgcc_s.so
/usr/lib/gcc/x86_64-redhat-linux/7/32/libgcc_s.so
/usr/lib64/libgcc_s-7-20170622.so.1
/usr/lib64/libgcc_s.so.1
```

**Comment by tpoechtrager** [comment]
Your system's C++ library has nothing to do with OSXCross. OSXCross uses the headers and libraries from the SDK.

**Comment by HinTak** [comment]
FWIW, this is a fedora anomaly - the fc31 bug I just filed https://bugzilla.redhat.com/show_bug.cgi?id=1824365
( based on the fc 30 bug filed / fixed elsewhere https://bugzilla.redhat.com/show_bug.cgi?id=1749971 ). Likely it is a similar bug in fc 26 which got unnoticed.
