### ISSUE TITLE
fixes fedora dependency checking

### ISSUE THREAD

**Issue by HinTak** [tpoechtrager/osxcross#129]
I was wondering whether you should check for clang's libcxx ( see also https://github.com/tpoechtrager/osxcross/issues/128 ) and adding libcxx and libcxx-devel to `tools/get_dependencies.sh`, and found that it has a few problems:

-  `grep -i fedora /etc/issue` isn't a test for fedora 26! Fedora 26's /etc/issue simply does not talk about fedora:

```
$ cat /etc/issue
\S
Kernel \r on an \m (\l)

```

on the other hand, there is a `/etc/fedora-release`:
```
$ cat /etc/fedora-release 
Fedora release 26 (Twenty Six)
```

- fedora recommends using `dnf` instead of `yum` for package management these days. all the options are mostly identical. (the internal implementations are different and faster, apparently).

and the question is, is clang libcxx libcxx-devel package relevant?

**Comment by tpoechtrager** [comment]
No, they aren't. See my statement in #127.
