### ISSUE TITLE
Header files for newer C++ features missing in SDK

### ISSUE THREAD

**Issue by Martchus** [tpoechtrager/osxcross#131]
I noticed that most SDK versions are missing `/usr/include/c++/v1` leading to the error handled here: https://github.com/tpoechtrager/osxcross/blob/master/wrapper/target.cpp#L577

Copying headers from regular (native Linux) `libc++` to my SDK directory fixes this (at least the library builds now):
```
cp -r /usr/include/c++/v1 /opt/osxcross/SDK/MacOSX10.11.sdk/usr/include/c++
```

How to deal with this issue (beside the mentioned workaround)? The only SDK having this directory is 10.7 (https://github.com/phracker/MacOSX-SDKs). Maybe it makes sense to copy files from there?

**Comment by HinTak** [comment]
The information about 10.7+ being required for libc++ is buried in the middle of the top level readme
( at https://github.com/tpoechtrager/osxcross#building-testcpp-with-libc ) . Hence my filing of https://github.com/tpoechtrager/osxcross/issues/128 - the different combos and requirement for c++ is rather scattered .

**Comment by Martchus** [comment]
Thanks for the quick reply. I've already read the requirement for 10.7+. In fact, I'm using the 10.11 SDK and set the required Mac OS X via `-mmacosx-version-min=10.9`.

**Comment by tpoechtrager** [comment]
Use this repo's packaging scripts to package the SDK properly. See "PACKAGING THE SDK:" @ https://github.com/tpoechtrager/osxcross for more.

**Comment by Martchus** [comment]
Thanks for the reply. I have already noticed that this packaging seems to be required but didn't do it because it requires XCode which requires an Apple developer account.

I'm wondering whether only these few header files are missing without packaging (or what this packaging actually does)? Seems like I have to get an Apple developer account.

**Comment by tpoechtrager** [comment]
It seems like only the header files are missing. For proper usage you should directly get them from the matching Xcode image.
