### ISSUE TITLE
osxcross: error: xcrun: cannot find 'ibtool' executable

### ISSUE THREAD

**Issue by ibash** [tpoechtrager/osxcross#134]
Hi,

I'm trying to get chromium to cross compile on a GCP instance.
I've got it to the point where I can generate the ninja build files, and start the build.
I'm stuck on `osxcross: error: xcrun: cannot find 'ibtool' executable` - do you know if it's possible to get the xcode command line tools to work on a non-mac machine?

**Comment by tpoechtrager** [comment]
You could try https://github.com/shinh/maloader. Not sure if `ibtool` will work though.
