### ISSUE TITLE
gen_cyglto_dll.sh broken with LLVM 4.0.1

### ISSUE THREAD

**Issue by osm0sis** [tpoechtrager/osxcross#141]
Causes a number of redefinition errors from the libLLVM4 dll vs. the included headers.

Downgrading LLVM to 3.9.1 resolved it, but it would be nice to be able to keep Cygwin up to date. Thanks!

Please also consider automatically pulling the SDKs from here: https://github.com/AaronWallace/MacOSX_SDKs

(note these do appear to be complete, as opposed to many of the "phracker" repo ones)

**Comment by tpoechtrager** [comment]
I will look into it.

For the SDK part: No, sorry, I won't pull SDKs from a third party repository. The SDKs aren't complete btw. For example the C++11 headers (libc++) are missing.

**Comment by tpoechtrager** [comment]
Cygwin is no longer supported by OSXCross.
