### ISSUE TITLE
build_gcc.sh issues on Cygwin

### ISSUE THREAD

**Issue by osm0sis** [tpoechtrager/osxcross#143]
```In file included from ../../gcc/cp/except.c:1013:0:
cfns.gperf: In function 'const char* libc_name_p(const char*, unsigned int)':
cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute
cfns.gperf:26:14: note: 'const char* libc_name_p(const char*, unsigned int)' previously declared here
cfns.gperf: At global scope:
cfns.gperf:26:14: warning: inline function 'const char* libc_name_p(const char*, unsigned int)' used but never defined
make[2]: *** [Makefile:1058: cp/except.o] Error 1
make[2]: *** Waiting for unfinished jobs....
rm gcc.pod
make[2]: Leaving directory '/home/Chris/osxcross/build/gcc-4.9.1/build/gcc'
make[1]: *** [Makefile:3977: all-gcc] Error 2
make[1]: Leaving directory '/home/Chris/osxcross/build/gcc-4.9.1/build'
make: *** [Makefile:866: all] Error 2
```

Is there a known working version of gcc on Cygwin I should be compiling instead? I went with 4.9.1 since most of the cross-compiling toolchains (e.g. crosstool-ng) seem to favor it for some reason.

**Comment by osm0sis** [comment]
Just realized you had a default of 6.2.0 in build_gcc.sh so I just let it run without any arguments/variables and it built completely. Perhaps would be good to add a lower range that it'll refuse to build below since you don't have patchsets ready? Thanks! I'll close the issue now. 😃

**Comment by osm0sis** [comment]
@tpoechtrager o64-g++ test failed, but only because of a script error copying over x86_64-*-base-g++.exe with the wrapper instead of it being the proper base. Replacing it with the working i386-*-base-g++.exe resolved it. 👍

**Comment by tpoechtrager** [comment]
Thank you for letting me know. I have no idea what's going on there. I came accross the same issue long time ago when I tested osxcross in Cygwin.

**Comment by egorpugin** [comment]
@osm0sis Did you resolve the issue?

> Replacing it with the working i386-*-base-g++.exe (since I noticed that's what you did for gcc) resolved it.

Could you please elaborate? Do not understand, sorry.

**Comment by osm0sis** [comment]
The actual issue with the build using the wrapper instead of the x86_64 exe still stands; it hasn't been fixed by @tpoechtrager, but my workaround does work just as I said: replace `x86_64-*-base-g++.exe` with `i386-*-base-g++.exe` since they're the same file in a working build.

**Comment by egorpugin** [comment]
For some reason it does not work for me.
i386 works, replacing, x86_64 does not work again.

**Comment by osm0sis** [comment]
You need to copy the i386 file over the x86_64 file. So in my case, in ~/osxcross/target/bin, `cp -f i386-apple-darwin11-base-g++.exe x86_64-apple-darwin11-base-g++.exe`

**Comment by egorpugin** [comment]
Strange... works now. Thanks!

**Comment by egorpugin** [comment]
...almost
Now it says:
```
./o64-g++ main.cpp
collect2: fatal error: cannot find 'nm'
compilation terminated.
```

**Comment by tpoechtrager** [comment]
Ensure target/bin is in `PATH`.

**Comment by egorpugin** [comment]
FYI:
I successfully crosscompiled to macos (the latest SDK 10.14) using clang+lld on windows.
I've added tapi library to ldd to read modern .dylib files.
I could publish more details and patches if you're interested.

**Comment by tpoechtrager** [comment]
Cygwin is no longer supported by OSXCross.
