### ISSUE TITLE
build.sh on linux fails with an error

### ISSUE THREAD

**Issue by aambati** [tpoechtrager/osxcross#147]
extracting MacOSX10.9.sdk.tar.xz ...
compiling wrapper ...

testing o32-clang ... ld: library not found for -lcrt1.10.5.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

exiting with abnormal exit code (1)
run 'OCDEBUG=1 ./build.sh' to enable debug messages
removing stale locks...
if it is happening the first time, then just re-run the script

**Comment by tpoechtrager** [comment]
Your SDK is broken - get a properly packaged one. Or use the methods described in the README.

**Comment by aambati** [comment]
I followed these steps:
```[Download Xcode **]
[Mount Xcode.dmg (Open With -> DiskImageMounter) ***]
Run: ./tools/gen_sdk_package.sh (from the OSXCross package)
Copy the packaged SDK (*.tar.* or *.pkg) on a USB Stick
(On Linux/BSD) Copy or move the SDK into the tarballs/ directory of OSXCross.```

but sdk on my machine is 10.13 darwin 1.7.4 , with this build.sh gave an error saying 10.13 sdk is not supported.

I got 10.9 sdk from https://github.com/phracker/MacOSX-SDKs, the error i posted came when i built with this sdk.

**Comment by tpoechtrager** [comment]
The phracker SDKs are known to be broken. 10.13 is indeed not (yet) supported. You could try the steps @ https://github.com/tpoechtrager/osxcross/issues/103#issuecomment-333948908 though.
