### ISSUE TITLE
osxcross cannot find libc++ headers

### ISSUE THREAD

**Issue by LinuxUserGD** [tpoechtrager/osxcross#150]
see https://github.com/godotengine/godot/issues/17888

I'm on Antergos OS (Arch Linux) and installed the package ```apple-darwin-osxcross```.
When I try to compile with OSXCross, I get this output:
```Swift
scons: Reading SConscript files ...
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  2%] Compiling ==> platform/osx/crash_handler_osx.mm
osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
scons: *** [platform/osx/crash_handler_osx.osx.tools.64.o] Error 1
scons: building terminated because of errors.
[user@user godot]$ 
```

**Comment by JAicewizard** [comment]
For any future people looking back at this: for those using osxcross-git (and probably the non-git package as well), you should bump the SDK version
