### ISSUE TITLE
WSL Ubuntu errors while creating sdk

### ISSUE THREAD

**Issue by nonnominandus** [tpoechtrager/osxcross#152]
I am trying to build the SDK on my ubuntu (windows subsytem for linux) and when I run the build sdk command "./tools/gen_sdk_package_darling_dmg.sh ~/Xcode_7.3.dmg" I get this error: /home/Douwe/osxcross/build/darling-dmg/src/DMGDecompressor.cpp:3:10: fatal error: 'bzlib.h' file not found
#include <bzlib.h>

I installed all packages I could find listed in the osxcross documentation (including libssl because I first also got "openssl not found"). I also tried installing bzip2 but it was already installed.

What did I miss?

Full output:
> ./tools/gen_sdk_package_darling_dmg.sh ~/Xcode_7.3.dmg
Using ubuntu, skipping fuse module check
Cloning into 'darling-dmg'...
remote: Counting objects: 633, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 633 (delta 1), reused 3 (delta 1), pack-reused 628
Receiving objects: 100% (633/633), 177.77 KiB | 285.00 KiB/s, done.
Resolving deltas: 100% (417/417), done.
Checking connectivity... done.
HEAD is now at 4e3a2ed Fix DMG mounting crashes (under Darling only)
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/Douwe/osxcross/build/darling-dmg/build
Scanning dependencies of target dmg
[  7%] Building CXX object CMakeFiles/dmg.dir/src/unichar.cpp.o
[ 11%] Building CXX object CMakeFiles/dmg.dir/src/FileReader.cpp.o
[ 15%] Building CXX object CMakeFiles/dmg.dir/src/Reader.cpp.o
[ 15%] Building CXX object CMakeFiles/dmg.dir/src/HFSVolume.cpp.o
[ 19%] Building CXX object CMakeFiles/dmg.dir/src/AppleDisk.cpp.o
[ 23%] Building CXX object CMakeFiles/dmg.dir/src/SubReader.cpp.o
[ 26%] Building CXX object CMakeFiles/dmg.dir/src/HFSBTree.cpp.o
[ 30%] Building CXX object CMakeFiles/dmg.dir/src/HFSFork.cpp.o
[ 34%] Building CXX object CMakeFiles/dmg.dir/src/HFSCatalogBTree.cpp.o
[ 38%] Building CXX object CMakeFiles/dmg.dir/src/HFSExtentsOverflowBTree.cpp.o
[ 42%] Building CXX object CMakeFiles/dmg.dir/src/HFSAttributeBTree.cpp.o
[ 46%] Building CXX object CMakeFiles/dmg.dir/src/DMGDisk.cpp.o
[ 50%] Building CXX object CMakeFiles/dmg.dir/src/DMGPartition.cpp.o
[ 53%] Building CXX object CMakeFiles/dmg.dir/src/DMGDecompressor.cpp.o
[ 57%] Building CXX object CMakeFiles/dmg.dir/src/adc.cpp.o
/home/Douwe/osxcross/build/darling-dmg/src/DMGDecompressor.cpp:3:10: fatal error: 'bzlib.h' file not found
#include <bzlib.h>
         ^
[ 61%] Building CXX object CMakeFiles/dmg.dir/src/HFSZlibReader.cpp.o
[ 65%] Building CXX object CMakeFiles/dmg.dir/src/MemoryReader.cpp.o
1 error generated.
CMakeFiles/dmg.dir/build.make:374: recipe for target 'CMakeFiles/dmg.dir/src/DMGDecompressor.cpp.o' failed
[ 69%] Building CXX object CMakeFiles/dmg.dir/src/GPTDisk.cpp.o
make[2]: *** [CMakeFiles/dmg.dir/src/DMGDecompressor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dmg.dir/all' failed
make[1]: *** [CMakeFiles/dmg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

> clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by HinTak** [comment]
The bzlib.h header is part of the bzip2-dev package or libbz2-dev . You need the -dev package.

**Comment by nonnominandus** [comment]
That definitively solved that problem. Thanks. I tried installing bzip2-dev but that was not available in the package manager.

But now I get this message:

>Using ubuntu, skipping fuse module check
Skipping partition of type Primary GPT Header
Skipping partition of type Primary GPT Table
Skipping partition of type Apple_Free
Skipping partition of type C12A7328-F81F-11D2-BA4B-00A0C93EC93B
Using partition Number 4 of type Apple_HFS
Everything looks OK, disk mounted
fuse: device not found, try 'modprobe fuse' first
fusermount: /tmp/kQFT3EaQu not mounted

I updated fuse and libfuse-dev and my version of ubuntu and all other packages, but it still gave this error.

**Comment by HinTak** [comment]
Have you tried literally what it says, I.e. modprobe fuse? In fact you need admin access to run modprobe, so you should do

sudo modprobe fuse

.

And then retry. And make sure your current user is in the fuse group, or a user with enough privilege to run fuse. You need to read up about fuse if you do not understand what I am saying.

**Comment by nonnominandus** [comment]
Okay I found that fuse is incompatible with windows drivers. So that explains the errors I am getting.
I will have to try it another way, but thanks a lot for helping me cope with the first problems.

**Comment by HinTak** [comment]
Oh, sorry I did not notice the WSL part. Anyway, I actually have osxcross working under WSL Ubuntu for a while now, using a transplanted SDK from a while back. Basically if you get your SDK by other means and then copy and unpack under WSL Ubuntu, it would work.

Sorry I should have noticed the WSL part - WSL has its own limitationa and does not support the deeper end of Linux's kernel. fuse is definitely something that one does not expect to work under WSL.

**Comment by nonnominandus** [comment]
Good to hear it should work when I transplant an sdk, that will keep the nice workflow with ubuntu on windows.
