### ISSUE TITLE
Can't build osxcross

### ISSUE THREAD

**Issue by DeadNumbers** [tpoechtrager/osxcross#154]
Hi, I'm trying to rebuild the package after updating my OS and have errors when building the package 
```osxcross: debug: === time spent in wrapper: 0.462343 ms
/home/user/Work/Git/osxcross-git/src/osxcross/target/bin/i386-apple-darwin15-ld: error while loading shared libraries: libicui18n.so.60: cannot open shared object file: No such file or directory
clang-6.0: error: unable to execute command: No such file or directory
clang-6.0: error: linker command failed due to signal (use -v to see invocation)
```
I created symbolic links to new versions of the libicu, libLTO, etc libraries, but I have some non-occurrence of some symbols in these libraries. So, I need to linked with new libraries.

My environment is -- clang 6, llvm 6, icu 61.1, Arch Linux

**Comment by HinTak** [comment]
I am afraid you need to re-build. Some of the dependent libraries obviously are not ABI-compatible after upgrade.
