### ISSUE TITLE
Cannot build gcc 8.1.0

### ISSUE THREAD

**Issue by kivadiu** [tpoechtrager/osxcross#156]
Hi,

I am trying to build gcc 8.1.0 on Fedora 27 but it fails. Note that I can build gcc 7.3.0.

These are the commands I use:
```
$ git clone https://github.com/tpoechtrager/osxcross.git osxcross-10.9
$ cd osxcross-10.9
$ cp ~sources/MacOSX10.9.sdk.tar.xz tarballs/
$ UNATTENDED=1 OSX_VERSION_MIN=10.9 ./build.sh > build.log 2>&1
$ OCDEBUG=1 GCC_VERSION=8.1.0 ./build_gcc.sh > build_gcc.log1 2>&1
# here it fails and I rerun the script as recommended:
$ OCDEBUG=1 GCC_VERSION=8.1.0 ./build_gcc.sh > build_gcc.log2 2>&1
```

I suspect that the problem is somewhere around this error:
`collect2: fatal error: ld terminated with signal 6 [Aborted], core dumped`

Logs are here:
[build.log.gz](https://github.com/tpoechtrager/osxcross/files/2175499/build.log.gz)
[build_gcc.log1.gz](https://github.com/tpoechtrager/osxcross/files/2175500/build_gcc.log1.gz)
[build_gcc.log2.gz](https://github.com/tpoechtrager/osxcross/files/2175501/build_gcc.log2.gz)

**Comment by ctubio** [comment]
just saying, i had no issues by today with `GCC_VERSION=8.2.0`

**Comment by kivadiu** [comment]
I still have the same problem with gcc 8.2.0 on Fedora 28 and 29: I cannot build gcc.

Here are the new logs:
`OCDEBUG=0`: [build_gcc.log1.gz](https://github.com/tpoechtrager/osxcross/files/2656584/build_gcc.log1.gz)
`OCDEBUG=1`: [build_gcc.log2.gz](https://github.com/tpoechtrager/osxcross/files/2656585/build_gcc.log2.gz)

This may be the main issue:
```
collect2: fatal error: ld terminated with signal 6 [Aborted], core dumped
compilation terminated.
x86_64-apple-darwin13-ld: macho_relocatable_file.cpp:1852: ld::relocatable::File *mach_o::relocatable::Parser<x86_64>::parse(const mach_o::relocatable::ParserOptions &) [A = x86_64]: Assertion `cfiStartsArray[i] != cfiStartsArray[i-1]' failed.
x86_64-apple-darwin13-ld: macho_relocatable_file.cpp:1852: ld::relocatable::File *mach_o::relocatable::Parser<x86_64>::parse(const mach_o::relocatable::ParserOptions &) [A = x86_64]: Assertion `cfiStartsArray[i] != cfiStartsArray[i-1]' failed.
make[2]: *** [Makefile:985: libgcc_s.dylib] Error 1
```

**Comment by tpoechtrager** [comment]
I noticed Apple finally(!) open sourced their latest linker. Maybe merging the latest sources will fix this issue. At least let's hope so...

**Comment by tpoechtrager** [comment]
Building latest GCC should work now.

**Comment by kivadiu** [comment]
Thanks, I will try now.

**Comment by kivadiu** [comment]
Thanks, I confirm that I can now build gcc-8.2.0!

**Comment by kivadiu** [comment]
I get the compiler but apparently the assembler does not work:
`x86_64-apple-darwin13-gcc -O2 -DNDEBUG -m64 -mmacosx-version-min=10.9 conftest.c`
gives
```
Assembler messages:
Fatal error: invalid listing option `r'
```
on file conftest.c:
```
int main() { return 0; }
```
what does that mean?

Using `x86_64-apple-darwin13-clang` instead does not give any error.

**Comment by tpoechtrager** [comment]
Try to build OSXCross with USE_CLANG_AS=1.

`USE_CLANG_AS=1 ./build.sh`

**Comment by kivadiu** [comment]
Still the same.
