### ISSUE TITLE
GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

### ISSUE THREAD

**Issue by ribasco** [tpoechtrager/osxcross#168]
Hello, 

My build is failing on Travis CI, but not on my local ubuntu machine.

**Error:**

 ```
  [exec]   Building C object CMakeFiles/cmTC_0590e.dir/testCCompiler.c.o
     [exec] 
     [exec]   /home/travis/build/[secure]/ucgdisplay/native/tools/osxcross/bin/o64-clang
     [exec]   -o CMakeFiles/cmTC_0590e.dir/testCCompiler.c.o -c
     [exec]   /home/travis/build/[secure]/ucgdisplay/native/modules/graphics/src/main/cpp/build/mac/amd64/CMakeFiles/CMakeTmp/testCCompiler.c
     [exec] 
     [exec] 
     [exec]   /home/travis/build/[secure]/ucgdisplay/native/tools/osxcross/bin/o64-clang:
     [exec]   relocation error:
     [exec]   /home/travis/build/[secure]/ucgdisplay/native/tools/osxcross/bin/o64-clang:
     [exec]   symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE,
     [exec]   version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time
     [exec]   reference
```

I have tried setting the compile flags as pointed out in Issue #98 but still no luck. Been at this the whole day, I must be missing something. Do you have any other suggestions?

```cmake
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -static-libstdc++")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static-libstdc++ -std=c++14")
```

Full app log: [here](https://api.travis-ci.org/v3/job/450825227/log.txt)
CMake toolchain file used: [OSXToolchain.cmake](https://github.com/ribasco/ucgdisplay/blob/branch-macosx/native/cmake/OSXToolchain.cmake)

**Comment by tpoechtrager** [comment]
You are using the wrong compiler. Use `clang++` or `clang++-libc++` instead of `clang`.

**Comment by tpoechtrager** [comment]
Sorry, I got this wrong. Please post the output of `ldd target/bin/osxcross`.

**Comment by ribasco** [comment]
Output from travis:
```
     [exec] 	linux-vdso.so.1 =>  (0x00007ffe8ef09000)
     [exec] 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f85dae22000)
     [exec] 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f85dab0c000)
     [exec] 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f85da806000)
     [exec] 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f85da5ee000)
     [exec] 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f85da225000)
     [exec] 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f85da007000)
     [exec] 	/lib64/ld-linux-x86-64.so.2 (0x00007f85db02a000)		
```

**Comment by tpoechtrager** [comment]
I have no clue what's going on then. Maybe you have a different `libstdc++` in `/usr/lib` or in `LD_LIBRARY_PATH` than you have built OSXCross against.

With `LDFLAGS="-static-libstdc++ ./build.sh` the output should be like this:

        linux-vdso.so.1 (0x00007ffd40252000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007fe971a0f000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007fe97188a000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fe971870000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fe9716ac000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe971b7b000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fe97168b000)

**Comment by ribasco** [comment]
Ok, this was very stupid of me...I completely misread the instructions on that issue. I was using the "-static-libstdc++" flag on the application side and not on the toolchain. I rebuilt the toolchain with what you suggested and now it works.

**Comment by tpoechtrager** [comment]
No worries. Happens to all of us. :-)
