### ISSUE TITLE
How can I use an uptodate standard C++ library with OSX SDK 10.9?

### ISSUE THREAD

**Issue by kivadiu** [tpoechtrager/osxcross#170]
I target OSX 10.9 because I want my programs to run on these machines but the standard library is pretty old in the SDK and with clang 7.0.0, `unordered_map` does not compile anymore (error in `__hash_table`, see below). Also, I cannot have C++17 which I would like to use.
So I would like to use another standard library, like the one that is shipped with my clang 7 on linux. Is it possible?
Note that up to know I've been using
`x86_64-apple-darwin13-clang++-libc++ -std=c++14 -m64 -mmacosx-version-min=10.9`
which apparently points to the standard library of the SDK.

```
In file included from /softs/osxcross-10.9-7.0.0/bin/../SDK/MacOSX10.9.sdk/usr/include/c++/v1/unordered_map:350:
/softs/osxcross-10.9-7.0.0/bin/../SDK/MacOSX10.9.sdk/usr/include/c++/v1/__hash_table:1165:43: error: exception specification in declaration does not match previous declaration
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table()
                                          ^
/softs/osxcross-10.9-7.0.0/bin/../SDK/MacOSX10.9.sdk/usr/include/c++/v1/__hash_table:852:5: note: previous declaration is here
    __hash_table()
    ^
/softs/osxcross-10.9-7.0.0/bin/../SDK/MacOSX10.9.sdk/usr/include/c++/v1/__hash_table:1233:43: error: exception specification in declaration does not match previous declaration
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table(__hash_table&& __u)
                                          ^
/softs/osxcross-10.9-7.0.0/bin/../SDK/MacOSX10.9.sdk/usr/include/c++/v1/__hash_table:866:5: note: previous declaration is here
    __hash_table(__hash_table&& __u)
    ^
2 errors generated.
```

**Comment by tpoechtrager** [comment]
Build GCC and use its C++ standard library. See README.

**Comment by kivadiu** [comment]
OK, thanks. If I build clang instead of using the one that comes with my linux, does it work the same?

**Comment by tpoechtrager** [comment]
No. The library must be built for macOS.

**Comment by Flow86** [comment]
Hi,
you can patch the bugged header file in the osx sdk without need to build a newer libc++ or anything:
https://github.com/tpoechtrager/osxcross/issues/171#issuecomment-453044540

**Comment by tpoechtrager** [comment]
See #184.
