### ISSUE TITLE
clang++ 7.0 fails to compile <unordered_map>

### ISSUE THREAD

**Issue by kivadiu** [tpoechtrager/osxcross#171]
I am using osxcross on Fedora to compile this simple program:
```
#include <unordered_map>
int main() { return 0; }
```
I use the following command to compile and link:

- with SDK 10.9: `x86_64-apple-darwin13-clang++-libc++ -std=c++14 -mmacosx-version-min=10.9 -o test-hash test-hash.cpp`
- with SDK 10.11: `x86_64-apple-darwin15-clang++-libc++ -std=c++14 -mmacosx-version-min=10.9 -o test-hash test-hash.cpp`

On F28 with clang++ 6.0 and SDK 10.9, it works fine.
On F29 with clang++ 7.0 and SDK 10.9 or 10.11, it fails with the following error:
```
In file included from test-hash.cpp:1:
In file included from /softs/osxcross-sdk10.11-min10.9-clang7.0.0/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/unordered_map:369:
SDK/MacOSX10.11.sdk/usr/include/c++/v1/__hash_table:1134:43: error: 
      exception specification in declaration does not match previous declaration
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table()
                                          ^
SDK/MacOSX10.11.sdk/usr/include/c++/v1/__hash_table:839:5: note: 
      previous declaration is here
    __hash_table()
    ^
SDK/MacOSX10.11.sdk/usr/include/c++/v1/__hash_table:1202:43: error: 
      exception specification in declaration does not match previous declaration
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table(__hash_table&& __u)
                                          ^
SDK/MacOSX10.11.sdk/usr/include/c++/v1/__hash_table:853:5: note: 
      previous declaration is here
    __hash_table(__hash_table&& __u)
    ^
2 errors generated.
```
This error is real: the exception specifications for the move constructor of `__hash_table` are different in the declaration and in the definition (and this is true for 10.9 and 10.11 SDK). With the 10.11 SDK, here is what we have:

- declaration:
```
_NOEXCEPT_(
    __node_traits::propagate_on_container_move_assignment::value &&
    is_nothrow_move_assignable<__node_allocator>::value &&
    is_nothrow_move_assignable<hasher>::value &&
    is_nothrow_move_assignable<key_equal>::value)
```
- definition:
```
_NOEXCEPT_(
    is_nothrow_move_constructible<__bucket_list>::value &&
    is_nothrow_move_constructible<__first_node>::value &&
    is_nothrow_move_constructible<hasher>::value &&
    is_nothrow_move_constructible<key_equal>::value)
 ```

I assume that it was not detected with clang 6 and is now blocking with clang 7.
I moved from SDK 10.9 to SDK 10.11. I have no idea what else to try unless forcing osxcross to use clang 6 instead of clang 7 if I can install both at the same time.

Thanks

**Comment by tpoechtrager** [comment]
You could try using the [latest libc++ headers](http://releases.llvm.org/7.0.0/libcxx-7.0.0.src.tar.xz). However, this could theoretically lead to linkage errors.

**Comment by tpoechtrager** [comment]
> But as you say, I may have linkage errors.
> By the way, how could I use those headers instead of the ones that come with the SDK?

They are ABI/API compatible. However, not everything might be implemented in the SDK's libc++ binary.

> Maybe those headers come with a newer SDK. Does osxcross work with SDK >7.3?

If you like hackish solutions, then yes. -> https://github.com/tpoechtrager/osxcross/issues/103#issuecomment-333948908. I just noticed he had to use a later SDK for the exact same reason. :-)

**Comment by kivadiu** [comment]
> If you like hackish solutions, then yes. -> #103 (comment). I just noticed he had to use a later SDK for the exact same reason. :-)

Well, I looked that that pretty long thread and it seems my first issue is to extract the SDK from the new .xip file format on linux or I need to update my Mac which currently I cannot do. Any idea on how to extract the SDK from Xcode >= 8?

**Comment by tpoechtrager** [comment]
xar -vxf Xcode.xip 
    pbzx -n Content | cpio -iv


    $ xar --version
    xar 1.6.1

    $ pbzx -v
    pbzx v1.0.2

**Comment by Flow86** [comment]
you could simply patch the header file

```
--- a/usr/include/c++/v1/__hash_table	2019-01-10 10:05:42.219730024 +0000
+++ b/usr/include/c++/v1/__hash_table	2019-01-10 10:09:08.881538038 +0000
@@ -1164,6 +1164,7 @@
     _NOEXCEPT_(
         is_nothrow_default_constructible<__bucket_list>::value &&
         is_nothrow_default_constructible<__first_node>::value &&
+        is_nothrow_default_constructible<__node_allocator>::value &&
         is_nothrow_default_constructible<hasher>::value &&
         is_nothrow_default_constructible<key_equal>::value)
     : __p2_(0),
@@ -1232,6 +1233,7 @@
         _NOEXCEPT_(
             is_nothrow_move_constructible<__bucket_list>::value &&
             is_nothrow_move_constructible<__first_node>::value &&
+            is_nothrow_move_constructible<__node_allocator>::value &&
             is_nothrow_move_constructible<hasher>::value &&
             is_nothrow_move_constructible<key_equal>::value)
     : __bucket_list_(_VSTD::move(__u.__bucket_list_)),
```

**Comment by kivadiu** [comment]
I do not like patching standard files...

I was finally able to extract SDK 10.13 from Xcode 9.4.1. The main difficulty was to find a version of pbxz that woks on linux (fedora). I used a python version because the C version did not build.

Now I tried to `./build.sh` with it but apprently osxcross is still not ready for it because I get the following error:
```
testing o32-clang ... + o32-clang /softs/build/osxcross-sdk10.13-min10.9-clang7.0.1-gcc8.2.0.build/oclang/test.c -O2 -Wall -o test
osxcross: debug: --> o32-clang /softs/build/osxcross-sdk10.13-min10.9-clang7.0.1-gcc8.2.0.build/oclang/test.c -O2 -Wall -o test~
osxcross: debug: <-- /usr/bin/clang-7 (clang) -target i386-apple-darwin17 -mlinker-version=274.2 -isystem /usr/bin/../lib64/clang/7.0.1/include -isysroot /softs/build/osxcross-sdk10.13-min10.9-clang7.0.1>
osxcross: debug: === time spent in wrapper: 0.186779 ms
ld: unexpected token: !tapi-tbd-v3 file '/softs/build/osxcross-sdk10.13-min10.9-clang7.0.1-gcc8.2.0.build/target/bin/../SDK/MacOSX10.13.sdk/usr/lib/libSystem.tbd' for architecture i386
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```
I find #103 solution quite difficult to follow. It seems that osxcross has already some of the proposed changes but not all of them.

**Comment by tpoechtrager** [comment]
See https://github.com/tpoechtrager/osxcross/issues/184.
