### ISSUE TITLE
clang 3.4's source tarball is clang-3.4.src.tar.gz, not cfe-3.4.src.tar.gz

### ISSUE THREAD

**Issue by sfackler** [tpoechtrager/osxcross#172]
build_clang.sh hits a 404 trying to download clang source when using an old GCC:

--2018-12-12 19:18:56--  http://llvm.org/releases/3.4/cfe-3.4.src.tar.gz
Resolving llvm.org... 54.67.122.174
Connecting to llvm.org|54.67.122.174|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://releases.llvm.org/3.4/cfe-3.4.src.tar.gz [following]
--2018-12-12 19:18:56--  http://releases.llvm.org/3.4/cfe-3.4.src.tar.gz
Resolving releases.llvm.org... 151.101.190.49, 2a04:4e42:2d::561
Connecting to releases.llvm.org|151.101.190.49|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-12-12 19:18:56 ERROR 404: Not Found.

The correct link is https://releases.llvm.org/3.4/clang-3.4.src.tar.gz.

**Comment by sfackler** [comment]
The real issue may be that CLANG_VERSION_PATCH is never actually used in the rest of the script: https://github.com/tpoechtrager/osxcross/blob/master/build_clang.sh#L44

**Comment by tpoechtrager** [comment]
CFE is correct. CFE stands for "clang front-end".

Anyway, that code is just used if an old GCC installation gets detected. Nevertheless, fixed.

Thank you for the hint!
