### ISSUE TITLE
Linkage error

### ISSUE THREAD

**Issue by nikobreu** [tpoechtrager/osxcross#177]
Thank you for making and maintaining this project!

I am running into an error during the build of the project on Ubuntu 18.04 LTS using the systems clang.  The linker can not find 'add_execute_list' and some other references when trying to create libstuff.a.

[here is the output](https://github.com/tpoechtrager/osxcross/files/2982640/output.txt)

**Comment by tpoechtrager** [comment]
Try uninstalling `lld`.

**Comment by nikobreu** [comment]
Thank you for the quick response.
I uninstalled `lld` and tried to run the build, but I am getting exactly the same error as before.

**Comment by tpoechtrager** [comment]
What's the output of `ld --version`?

**Comment by nikobreu** [comment]
The output is

> @(#)PROGRAM:ld  PROJECT:ld64-274.2
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 6.0.0
TAPI support using: Apple TAPI version 1.30.0

**Comment by tpoechtrager** [comment]
Did you install `ld64` to `/usr`? If so, reinstall ld and binutils.

**Comment by tpoechtrager** [comment]
You must have installed `ld64` (cctools-port) to `/usr/local/bin`. Remove the binaries in `/usr/local/bin`. That should fix the issue.

**Comment by tpoechtrager** [comment]
Remove these:

    ./share
    ./share/man
    ./share/man/man5
    ./share/man/man5/stab.5
    ./share/man/man5/ranlib.5
    ./share/man/man5/a.out.5
    ./share/man/man5/Mach-O.5
    ./share/man/man3
    ./share/man/man3/redo_prebinding.3
    ./share/man/man3/libsyminfo.3
    ./share/man/man3/NSObjectFileImage_priv.3
    ./share/man/man3/getsegbyname.3
    ./share/man/man3/getsectdatafromheader.3
    ./share/man/man3/getsectdata.3
    ./share/man/man3/getsectbynamefromheader.3
    ./share/man/man3/getsectbyname.3
    ./share/man/man3/end.3
    ./share/man/man3/get_end.3
    ./share/man/man3/arch.3
    ./share/man/man3/kld.3
    ./share/man/man3/dyld_debug.3
    ./share/man/man3/NSObjectFileImage.3
    ./share/man/man3/NSModule.3
    ./share/man/man3/dyld.3
    ./share/man/man1
    ./share/man/man1/mtoc.1
    ./share/man/man1/check_dylib.1
    ./share/man/man1/seg_addr_table.1
    ./share/man/man1/checksyms.1
    ./share/man/man1/indr.1
    ./share/man/man1/otool-classic.1
    ./share/man/man1/size-classic.1
    ./share/man/man1/nm-classic.1
    ./share/man/man1/llvm-otool.1
    ./share/man/man1/bitcode_strip.1
    ./share/man/man1/ctf_insert.1
    ./share/man/man1/codesign_allocate.1
    ./share/man/man1/install_name_tool.1
    ./share/man/man1/nmedit.1
    ./share/man/man1/redo_prebinding.1
    ./share/man/man1/pagestuff.1
    ./share/man/man1/cmpdylib.1
    ./share/man/man1/libtool.1
    ./share/man/man1/strip.1
    ./share/man/man1/size.1
    ./share/man/man1/segedit.1
    ./share/man/man1/ranlib.1
    ./share/man/man1/otool.1
    ./share/man/man1/nm.1
    ./share/man/man1/as.1
    ./share/man/man1/lipo.1
    ./share/man/man1/strings.1
    ./share/man/man1/dyld.1
    ./libexec
    ./libexec/as
    ./libexec/as/ppc64
    ./libexec/as/ppc64/as
    ./libexec/as/ppc
    ./libexec/as/ppc/as
    ./libexec/as/x86_64
    ./libexec/as/x86_64/as
    ./libexec/as/i386
    ./libexec/as/i386/as
    ./libexec/as/arm
    ./libexec/as/arm/as
    ./bin
    ./bin/machocheck
    ./bin/unwinddump
    ./bin/ObjectDump
    ./bin/dyldinfo
    ./bin/ld
    ./bin/otool
    ./bin/inout
    ./bin/cmpdylib
    ./bin/check_dylib
    ./bin/ctf_insert
    ./bin/bitcode_strip
    ./bin/codesign_allocate
    ./bin/ranlib
    ./bin/pagestuff
    ./bin/segedit
    ./bin/nmedit
    ./bin/strip
    ./bin/indr
    ./bin/install_name_tool
    ./bin/seg_hack
    ./bin/seg_addr_table
    ./bin/redo_prebinding
    ./bin/libtool
    ./bin/nm
    ./bin/strings
    ./bin/size
    ./bin/lipo
    ./bin/checksyms
    ./bin/as
    ./bin/ar

**Comment by nikobreu** [comment]
> All done! Now you can use o32-clang(++) and o64-clang(++) like a normal compiler.
Thanks a lot!  This solved the issue. And well done spotting the problem.
