### ISSUE TITLE
`ld: unexpected token: !tapi-tbd-v3 file`

### ISSUE THREAD

**Issue by robohack** [tpoechtrager/osxcross#181]
So, I'm trying to build an osx cross-compiler on a rather ancient linux machine with an ancient GCC and ancient CMake, and no Clang.

After some trials and issues I've managed to install a working GCC-9.1.1, as well as cmake-3.14.20190515-g38bed (from git), and finally after much fiddling I got `build_clang.sh` to build LLVM/Clang 8.0.0 (the old 3.9.1 Clang cannot be built with this new a GCC -- because, syntax errors).

These are all installed into my $HOME.

I also have MacOSX10.14.sdk.tar.xz

Then the attached happened.....

So, this is quite similar to #103 (and maybe #81 too) but not exactly the same and in arguably different circumstances.

I'm encouraged by some of what I read in #103, but extremely discouraged by the lack of viable integration back into the project (i.e. proper patches or pull requests), and without learning a lot more about this morass  I'm unable to make enough sense of what others have done, and what is actually wrong, to put together such patches myself.

I've tried installing apple-libtapi both in my `$HOME/lib` and `$HOME/include` as well as in the `target/lib` and `target/include`, but it doesn't seem to be picked up from either location by the build and nothing changes.

<pre>
++ osxcross-cmp 10.14 '<' 10.5
+ '[' 0 -eq 1 ']'
++ osxcross-cmp 10.5 '<' 10.4
+ '[' 0 -eq 1 ']'
+ echo 'installing CMake'
installing CMake
+ cp -f /home/gaw/work/osxcross/tools/toolchain.cmake /home/gaw/work/osxcross/target/
+ cp -f /home/gaw/work/osxcross/tools/osxcross-cmake /home/gaw/work/osxcross/target/bin/
+ chmod 755 /home/gaw/work/osxcross/target/bin/osxcross-cmake
+ create_symlink osxcross-cmake /home/gaw/work/osxcross/target/bin/i386-apple-darwin18-cmake
+ ln -sf osxcross-cmake /home/gaw/work/osxcross/target/bin/i386-apple-darwin18-cmake
+ create_symlink osxcross-cmake /home/gaw/work/osxcross/target/bin/x86_64-apple-darwin18-cmake
+ ln -sf osxcross-cmake /home/gaw/work/osxcross/target/bin/x86_64-apple-darwin18-cmake
+ unset MACOSX_DEPLOYMENT_TARGET
+ test_compiler o32-clang /home/gaw/work/osxcross/oclang/test.c
+ echo -ne 'testing o32-clang ... '
testing o32-clang ... + o32-clang /home/gaw/work/osxcross/oclang/test.c -O2 -Wall -o test
osxcross: debug: --> o32-clang /home/gaw/work/osxcross/oclang/test.c -O2 -Wall -o test 
osxcross: debug: <-- /home/gaw/bin/clang-8 (clang) -target i386-apple-darwin18 -mlinker-version=274.2 -isystem /home/gaw/bin/../lib/clang/8.0.0/include -isysroot /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk -cxx-isystem /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include/c++/4.2.1 -cxx-isystem /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include/c++/4.2.1/i386-apple-darwin18 -cxx-isystem /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include/c++/4.2.1/backward -mmacosx-version-min=10.5.0 -arch i386 -Wno-liblto /home/gaw/work/osxcross/oclang/test.c -O2 -Wall -o test 
osxcross: debug: === time spent in wrapper: 0.286387 ms
ld: unexpected token: !tapi-tbd-v3 file '/home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/lib/libSystem.tbd' for architecture i386
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
+ _exit
+ EC=1
+ '[' 1 -ne 0 ']'
+ test -z build.sh
+ echo ''

+ echo 'exiting with abnormal exit code (1)'
exiting with abnormal exit code (1)
+ test -n 1
+ declare -f -F remove_locks
+ echo 'removing stale locks...'
removing stale locks...
+ remove_locks
+ rm -rf /home/gaw/work/osxcross/build/have_cctools_8e9c3f2_0
+ echo 'if it is happening the first time, then just re-run the script'
if it is happening the first time, then just re-run the script
+ echo ''

+ test build.sh = build.sh
+ check_for_bug_1242300
+ '[' -e /etc/issue ']'
++ grep -i ubuntu.13.10 /etc/issue
+ '[' '' ']'
^?[1]+  Exit 1                  INSTALLPREFIX=$HOME OCDEBUG=1 ./build.sh > build.out 2>&1

</pre>

**Comment by robohack** [comment]
So, I finally clued into what the people discussing #103 were doing, i.e. simply re-building a newer cctools linked against a newer apple-libtapi and installing it over the one built by `osxcross/build.sh`.

This gets me quite a little further, but of course I'm trying with MacOSX10.14 so I'm guessing now that even the "2.0.0" branch of tpoechtrager/apple-libtapi is apparently still not new enough, I think, and perhaps cctools needs updating too?

(FYI, the hex in the error below is exactly the first line from the SDK's libSystem.tbd:  `--- !tapi-tbd-v3`, so the error message is a bit misleading still as it's nothing to do with "architecture" per se.)

<pre>
$ PATH=$PWD/target/bin:$PATH o64-clang -v oclang/test.c -O2 -Wall -o test
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-apple-darwin18
Thread model: posix
InstalledDir: /home/gaw/bin
 "/home/gaw/bin/clang-8" -cc1 -triple x86_64-apple-macosx10.5.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -faligned-alloc-unavailable -target-sdk-version=10.14 -target-cpu core2 -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 274.2 -v -resource-dir /home/gaw/lib/clang/8.0.0 -isystem /home/gaw/bin/../lib/clang/8.0.0/include -isysroot /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk -cxx-isystem /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include/c++/4.2.1 -cxx-isystem /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include/c++/4.2.1/x86_64-apple-darwin18 -cxx-isystem /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include/c++/4.2.1/backward -O2 -Wno-liblto -Wall -fdebug-compilation-dir /home/gaw/work/osxcross -ferror-limit 19 -fmessage-length 132 -stack-protector 1 -fblocks -fblocks-runtime-optional -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.5.0 -fobjc-dispatch-method=non-legacy -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/test-74689e.o -x c /home/gaw/work/osxcross/oclang/test.c
clang -cc1 version 8.0.0 based upon LLVM 8.0.0 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include/c++/4.2.1/x86_64-apple-darwin18"
ignoring nonexistent directory "/home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/local/include"
ignoring nonexistent directory "/home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/Library/Frameworks"
ignoring duplicate directory "/home/gaw/bin/../lib/clang/8.0.0/include"
#include "..." search starts here:
#include <...> search starts here:
 /home/gaw/bin/../lib/clang/8.0.0/include
 /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include
 /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/home/gaw/work/osxcross/target/bin/x86_64-apple-darwin18-ld" -demangle -lto_library /home/gaw/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.5.0 -syslibroot /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk -o test -lcrt1.10.5.o /tmp/test-74689e.o -lSystem
ld: warning: ignoring file /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /home/gaw/work/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture x86_64:
  "_exit", referenced from:
      start in crt1.10.5.o
  "_printf", referenced from:
      _main in test-74689e.o
ld: symbol(s) not found for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

**Comment by tpoechtrager** [comment]
What's the output of `ldd /home/gaw/work/osxcross/target/bin/x86_64-apple-darwin18-ld` and `/home/gaw/work/osxcross/target/bin/x86_64-apple-darwin18-ld -v`?

**Comment by robohack** [comment]
<pre>
$ ldd /home/gaw/work/osxcross/target/bin/x86_64-apple-darwin18-ld
	linux-vdso.so.1 =>  (0x00007ffee278f000)
	libstdc++.so.6 => /home/gaw/lib/../lib64/libstdc++.so.6 (0x00002b4fa3db7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00002b4fa41b5000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00002b4fa4437000)
	libLTO.so.8 => /home/gaw/lib/libLTO.so.8 (0x00002b4fa463c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00002b4fa7f9f000)
	libtapi.so => /home/gaw/lib/libtapi.so (0x00002b4fa81a3000)
	libgcc_s.so.1 => /home/gaw/lib/../lib64/libgcc_s.so.1 (0x00002b4fa83c0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00002b4fa85d9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00002b4fa87f5000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b4fa3b95000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00002b4fa8b83000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00002b4fa8d9a000)
</pre>

<pre>
$ /home/gaw/work/osxcross/target/bin/x86_64-apple-darwin18-ld -v
@(#)PROGRAM:ld  PROJECT:ld64-274.2
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 8.0.0
TAPI support using: Apple TAPI version 1.30.0</pre>

**Comment by tpoechtrager** [comment]
libtapi 1.30.0 does not support TAPIv3 stubs.

Greg A. Woods <notifications@github.com> schrieb am So., 26. Mai 2019,
00:15:

**Comment by robohack** [comment]
That's my point exactly!  :-)

Apparently neither is the 2.0.0 branch, though I probably should double-check that as it seems libtapi needs to be rebuilt earlier in the process (i.e. before the Clang build happens maybe?)

How do I get the upgraded, portable, apple-libtapi integrated into osxcross such that it will be used by all the relevant components, including Clang?

Are you able to work on porting the new version?  I'm not sure I'm able to do it, unless maybe any portability issues are simple enough and not too deeply tied to C++.  (I don't do C++)

**Comment by tpoechtrager** [comment]
The 2.0.0 branch supports TAPIv3. Ensure you don't have an old version of `libtapi` in `/usr/local` or similar.

I have ported `ld64 409.12` and `cctools 921` this weekend. But there are problems... I am trying my best to get all the latest stuff working. There are a lot of things to do to catch up. I haven't really worked on OSXCross for a very long time... And don't forget: I do this in my spare time.

**Comment by robohack** [comment]
I did not expect the 2.0.0 branch to support TAPIv3 -- that's good news I think!

OK, I'll try a rebuild from scratch of Clang and osxcross after cleaning everything out and ensuring only the 2.0.0 branch of libtapi is installed.

Thanks very much for your efforts -- I'm currently doing this for work, but it is mostly a side project as only a couple of us use MacOS for daily development and customer-wise we don't really do anything but demos on MacOS (no deliverables).  However having a stable and up-to-date cross-compiler on our central shared Linux build machines should alleviate a problem we've had with using some libraries built on an ancient macos and linking them to use on current macos.  (Though if it ended up working for our iOS app too, that would be good!)

**Comment by tpoechtrager** [comment]
I have merged the latest sources. If things work well I will update OSXCross too. There might be some issues. One issue I am ware of is that otool **might** fail to build because of a dependency issue on libobjc2. It may or may not happen during building. I had no time to do a lot of testing.

https://github.com/tpoechtrager/apple-libtapi/tree/2.0.0
https://github.com/tpoechtrager/cctools-port/tree/921-ld64-409.12

**Comment by robohack** [comment]
Hopefully I'll have time tomorrow to kick off some rebuilds of those!

**Comment by tpoechtrager** [comment]
See https://github.com/tpoechtrager/osxcross/issues/184.
