### ISSUE TITLE
gen_sdk_package_p7zip.sh fails with invalid value 'gnu++03' 

### ISSUE THREAD

**Issue by sha-256** [tpoechtrager/osxcross#182]
Getting following error while running gen_sdk_package_p7zip.sh on debian:
`"invalid value 'gnu++03' in -std=gnu++03"`
The sdk packaging completes just fine if "-std=gnu++03" removed from gen_sdk_package_p7zip.sh for both "CC" and "CXX". 
Would appreciate any better than patching "gen_sdk_package_p7zip.sh" to overcome it.

**Comment by tpoechtrager** [comment]
What compiler are you using? Need the output of `--version`.

I don't have any problems with:

    g++ --version
    g++ (GCC) 9.1.0
    Copyright (C) 2019 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    clang++ --version
    clang version 8.0.0 (tags/RELEASE_800/final)
    Target: x86_64-pc-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin

**Comment by tpoechtrager** [comment]
See https://github.com/tpoechtrager/osxcross/issues/184.
