### ISSUE TITLE
testing branch

### ISSUE THREAD

**Issue by tpoechtrager** [tpoechtrager/osxcross#184]
I have added a `testing` branch with the following changes:

New:
* Added support for TAPIv3 stubs (including `zippering` target)
* Added support for MacOSX SDKs up to 10.14
* Added new SDK packaging script for SDKs that end with `.xip` (`tools/gen_sdk_package_pbzx.sh <xcode.xip>`) (tested up to Xcode 10.2.1)
* Updated cctools to 921 and ld64 to 409.12

Fixed:
* Implemented fix for https://github.com/tpoechtrager/osxcross/issues/171
* Implemented fix for https://github.com/tpoechtrager/osxcross/issues/178
* Implemented fix for https://github.com/tpoechtrager/osxcross/issues/182

Changed:
* `cctools`, `ld64`, `apple-libtapi` and `xar` are now `git clone`'d and no longer come with OSXCross.

Removed:
* Support for Cygwin and *BSD (besides FreeBSD)
* Support for building OSXCross with GCC

It would be great if I could get some feedback. I will merge the testing branch into master once I am sure everything works well.

**Comment by Calinou** [comment]
Thanks for the great work! I don't have time to test this right now but this sounds very nice.

**Comment by kivadiu** [comment]
Thanks a lot for these changes.

I tested `tools/gen_sdk_package_pbzx.sh` on Xcode 9.4.1 and it worked well. I obtained SDK 10.13, the same as I got it when I did it by hand some months ago following a much more complicated procedure.

I then tested `OCDEBUG=1 UNATTENDED=1 OSX_VERSION_MIN=10.9 ./build.sh` with it and obtained the cross compiler `darwin17`.

Finally, I tried to compile on linux the following program:
```#include <iostream>
#include <string>
#include <unordered_map>

int main() {
  std::unordered_map<int, std::string> m;
  m[0] = "0";
  m[1] = "1";
  m[2] = "2";
  for (auto i = 0; i < 3; ++i) {
    std::cout << i << ':' << m[i] << '\n';
  }
  return 0;
}
```
with the following command:
`target/bin/x86_64-apple-darwin17-clang++-libc++ -std=c++14 -mmacosx-version-min=10.9 -o unordered unordered.cpp`

It compiled without warning and ran correctly on El Capitan.

So, this works perfectly well for me.

A great thanks.

**Comment by kivadiu** [comment]
I also tried to build gcc 8.3.0 with `GCC_VERSION=8.3.0 ./build_gcc.sh`. I got no error message but when I try to compile the above program with
`target/bin/x86_64-apple-darwin17-g++ -std=c++14 -mmacosx-version-min=10.9 -o unordered unordered.cpp`
I get the following error message:
`x86_64-apple-darwin17-g++: error trying to exec 'cc1plus': execvp: No such file or directory`
I get the same error with `target/bin/x86_64-apple-darwin17-g++-libc++`.

**Comment by tpoechtrager** [comment]
> I get the following error message:
x86_64-apple-darwin17-g++: error trying to exec 'cc1plus': execvp: No such file or directory

`target/bin` must be in `PATH`.

Thanks for your feedback.

**Comment by kivadiu** [comment]
> `target/bin` must be in `PATH`.

Thanks, now both `target/bin/x86_64-apple-darwin17-g++-libc++` and `target/bin/x86_64-apple-darwin17-g++` compile, link and give a binary that runs on El Capitan.

The only small issue is that with `target/bin/x86_64-apple-darwin17-g++`, I get the following warning:
```
ld: warning: direct access in function 'operator new(unsigned long, std::nothrow_t const&) [clone .cold.0]' from file '/softs/build/osxcross-testing/target/bin/../lib/gcc/x86_64-apple-darwin17/8.3.0/../../../../x86_64-apple-darwin17/lib/libstdc++.a(new_opnt.o)' to global weak symbol 'operator new(unsigned long, std::nothrow_t const&)' from file '/softs/build/osxcross-testing/target/bin/../lib/gcc/x86_64-apple-darwin17/8.3.0/../../../../x86_64-apple-darwin17/lib/libstdc++.a(new_opnt.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

**Comment by tpoechtrager** [comment]
I know. It's a GCC issue. I can't do anything about it.

**Comment by kivadiu** [comment]
> I know. It's a GCC issue. I can't do anything about it.

do you know if it is harmful?

**Comment by tpoechtrager** [comment]
I think it just means `new` and `delete` cannot be overriden during runtime. For example by sanitizers.

**Comment by tpoechtrager** [comment]
Merged into master branch.
