### ISSUE TITLE
AVX/SSE Support

### ISSUE THREAD

**Issue by Hacksawfred3232** [tpoechtrager/osxcross#185]
So, after several hours of figuring out why all of the libraries i am building are failing yet Mingw and the standard GCC compiler works flawlessly, it turns out the AVX and maybe SSE instructions support is not supported. Why!? I don't want to spend the massive amount of money on a computer that has OSX just to do development work. So really hoping that this is just some glitch and there is a way to enable support for this when building the toolkit. Otherwise, this may kill my ability to build programs for OSX.

**Comment by tpoechtrager** [comment]
It's not a glitch. Use `x86_64h-` instead of `x86_64-`.

https://github.com/llvm/llvm-project/blob/2946cd701067404b99c39fb29dc9c74bd7193eb3/clang/lib/Driver/ToolChains/Arch/X86.cpp#L72

```
$ x86_64-apple-darwin19-clang -dM -E - < /dev/null | egrep "SSE|AVX" | sort
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE3__ 1
#define __SSE_MATH__ 1
#define __SSSE3__ 1
```
```
$ x86_64h-apple-darwin19-clang -dM -E - < /dev/null | egrep "SSE|AVX" | sort
#define __AVX__ 1
#define __AVX2__ 1
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSE_MATH__ 1
#define __SSSE3__ 1
```

Or specify `-march`.

```
$ x86_64-apple-darwin19-clang -march=skylake-avx512 -dM -E - < /dev/null | egrep "SSE|AVX" | sort
#define __AVX__ 1
#define __AVX2__ 1
#define __AVX512BW__ 1
#define __AVX512CD__ 1
#define __AVX512DQ__ 1
#define __AVX512F__ 1
#define __AVX512VL__ 1
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE3__ 1
#define __SSE4_1__ 1
#define __SSE4_2__ 1
#define __SSE_MATH__ 1
#define __SSSE3__ 1
```

**Comment by Hacksawfred3232** [comment]
Uhm, i am using the GCC tools, not clang. What i am building requires me to use GCC.

**Comment by Hacksawfred3232** [comment]
Nvm, just tried march and it works. One more question before i close this issue, will the skylake-avx512 option work for everything, or do i need to change it per program? And if it is program dependent, how do list the processor specific arches?

**Comment by tpoechtrager** [comment]
You can compile everything with `-march=skylake-avx512` as long as the target Mac supports it.

**Comment by Hacksawfred3232** [comment]
Okay. Thanks.
