### ISSUE TITLE
A few issues building Qt

### ISSUE THREAD

**Issue by jschultz** [tpoechtrager/osxcross#187]
Hello,

First the good news, using the osxcross toolchain and a slightly [hacked version](https://github.com/jschultz/mxe/tree/x86_64-apple-darwin18) of the MXE cross-building environment I have managed to cross-build Qt for Mac in a voidlinux Docker container. Not quite ready for public consumption but you can find the scripts [here](https://github.com/jschultz/kde-static/tree/master/osxcross). I was very impressed with how well osxcross just worked out of the box.

I did find a couple of smallish issue linked to osxcross. I'm happy to make pull requests but wanted to discuss first, given the possibility of breaking so many other things.

First, and this might be an issue with the build environment, but I found it does things like `xcrun -find x86_64-apple-darwin18-clang` to locate the compiler. The problem there is that xcrun returns `.../bin/x86_64-apple-darwin18-wrapper` which cannot actually be used for compilation. Is it possible that xcrun should not follow symbolic links to the toolchain wrapper?

Second, also connected with xcrun, is that it spits out warning like `osxcross: warning: xcrun: ignoring environment variable 'DEVELOPER_DIR'` which interrupt the build scripts picking up the output from xcrun. Could those warnings be disabled, at least via a command-line option?

Third, linking a test executable using SDK 10.14 found a missing symbol `isOSVersionAtLeast`. As described [here](https://jonnyzzz.com/blog/2018/06/13/link-error-3/) this symbol is defined in the library `libclang_rt.osx.a` which is part of the XCode but not packaged into the SDK by the script `gen_sdk_package.sh`. Is there any good reason why this library cannot be packaged into the SDK tarball?

**Comment by tpoechtrager** [comment]
`xcrun` is no longer following symlinks. I have added `OSXCROSS_XCRUN_NO_ENV_WARNING=1` (env var) to silence the warning. 

> Third, linking a test executable using SDK 10.14 found a missing symbol `isOSVersionAtLeast`. As described [here](https://jonnyzzz.com/blog/2018/06/13/link-error-3/) this symbol is defined in the library `libclang_rt.osx.a` which is part of the XCode but not packaged into the SDK by the script `gen_sdk_package.sh`. Is there any good reason why this library cannot be packaged into the SDK tarball?

The compiler-rt libraries must match the compiler version. You can use `./build_compiler_rt.sh` to build them.

**Comment by jschultz** [comment]
Thanks for the tips. I seem to be having troubles with `./build_compiler_rt.sh` The first error I can see is:

> CMake Error at cmake/Modules/CompilerRTUtils.cmake:309 (string):
>  string sub-command REPLACE requires at least four arguments.

which looks like `COMPILER_RT_DEFAULT_TARGET_TRIPLE` didn't get defined. 

After that there are many CMake errors.

I could do some more digging but hope that you will know immediately what the problem is.

Thanks!

**Comment by tpoechtrager** [comment]
You need to provide more details. Need the OS version and the version of your CMake installation.

**Comment by jschultz** [comment]
> $ cmake --version
> cmake version 3.14.5

The OS a bit more complicated. I'm using Void Linux, which runs a rolling release, inside a docker container on a Debian/sid host. Kernel is `4.19.0-5-amd64`

**Comment by tpoechtrager** [comment]
I have the same CMake version and it works just fine. That's kinda strange. What's your clang version?

**Comment by jschultz** [comment]
> $ clang --version
> clang version 8.0.0 (tags/RELEASE_800/final)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /usr/sbin

**Comment by tpoechtrager** [comment]
Do you have `llvm` installed?

**Comment by jschultz** [comment]
No, but installing it fixed the problem. Thank you!

**Comment by tpoechtrager** [comment]
No problem.

**Comment by baptx** [comment]
@jschultz If I understand correctly, with your fork https://github.com/jschultz/mxe/tree/x86_64-apple-darwin18, we can successfully cross-compile Qt apps from Linux to MacOS? Did you try to include your changes in the official repository? I created an issue here: https://github.com/mxe/mxe/issues/2727

**Comment by jschultz** [comment]
That is correct. It worked back when I last used it to cross-build some KDE apps (well one really - Okular) on Linux for MacOS. I never made any pull requests. And I never tried using it outside of Docker.
