### ISSUE TITLE
Building Clang/LLVM fails

### ISSUE THREAD

**Issue by TechComet** [tpoechtrager/osxcross#188]
./build_clang.sh

It is highly recommended to uninstall previous clang versions first:
-> /usr/bin/clang

Building Clang/LLVM 8.0.0 may take a long time.
Installation Prefix: /usr/local

Press enter to start building.

--2019-07-06 19:07:29--  http://releases.llvm.org/8.0.0/llvm-8.0.0.src.tar.xz
Resolving releases.llvm.org (releases.llvm.org)... 151.101.114.49, 2a04:4e42:1b::561
Connecting to releases.llvm.org (releases.llvm.org)|151.101.114.49|:80... connected.
HTTP request sent, awaiting response... 416 Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2019-07-06 19:07:30--  http://releases.llvm.org/8.0.0/cfe-8.0.0.src.tar.xz
Resolving releases.llvm.org (releases.llvm.org)... 151.101.114.49, 2a04:4e42:1b::561
Connecting to releases.llvm.org (releases.llvm.org)|151.101.114.49|:80... connected.
HTTP request sent, awaiting response... 416 Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

cleaning up ...
extracting llvm-8.0.0.src.tar.xz ...
extracting cfe-8.0.0.src.tar.xz ...

-- The C compiler identification is unknown
-- The CXX compiler identification is Clang 6.0.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /opt/cmake-3.14.5-Linux-x86_64/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/techcomet/Downloads/macosx/osxcross/build/llvm-8.0.0.src/build_stage1/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_40b84/fast 
    /usr/bin/make -f CMakeFiles/cmTC_40b84.dir/build.make CMakeFiles/cmTC_40b84.dir/build
    make[1]: Entering directory '/home/techcomet/Downloads/macosx/osxcross/build/llvm-8.0.0.src/build_stage1/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_40b84.dir/testCCompiler.c.o
    /usr/bin/cc    -o CMakeFiles/cmTC_40b84.dir/testCCompiler.c.o   -c /home/techcomet/Downloads/macosx/osxcross/build/llvm-8.0.0.src/build_stage1/CMakeFiles/CMakeTmp/testCCompiler.c
    fatal error: as: unknown host architecture (can't determine which assembler to run)
    CMakeFiles/cmTC_40b84.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_40b84.dir/testCCompiler.c.o' failed
    make[1]: *** [CMakeFiles/cmTC_40b84.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/techcomet/Downloads/macosx/osxcross/build/llvm-8.0.0.src/build_stage1/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_40b84/fast' failed
    make: *** [cmTC_40b84/fast] Error 2
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:39 (project)

-- Configuring incomplete, errors occurred!
See also "/home/techcomet/Downloads/macosx/osxcross/build/llvm-8.0.0.src/build_stage1/CMakeFiles/CMakeOutput.log".
See also "/home/techcomet/Downloads/macosx/osxcross/build/llvm-8.0.0.src/build_stage1/CMakeFiles/CMakeError.log".

exiting with abnormal exit code (1)
run 'OCDEBUG=1 ./build_clang.sh' to enable debug messages

**Comment by tpoechtrager** [comment]
Your compiler is broken. I hope you didn't just do `rm -f /usr/bin/cc`... Reinstall your OS compiler and ignore the _"It is highly recommended to uninstall previous clang versions first"_ message.

**Comment by kmatheussen** [comment]
This can happen for cmake if you have installed a custom compiler.

I have to give these arguments to cmake:
gcc:
-DCMAKE_CXX_COMPILER=`which g++` -DCMAKE_C_COMPILER=`which gcc`
clang:
-DCMAKE_CXX_COMPILER=`which clang++` -DCMAKE_C_COMPILER=`which clang`

I don't know how you would give these arguments to ./build_clang.sh though.
Maybe you can edit the script manually, or perhaps this works:
CMAKE_CXX_COMPILER=`which g++` CMAKE_C_COMPILER=`which gcc` ./build_clang.sh
