### ISSUE TITLE
Building gcc 9 with 10.14 SDK fails

### ISSUE THREAD

**Issue by kivadiu** [tpoechtrager/osxcross#190]
Line 213 of build_gcc.sh:
```
test_compiler o64-gcc $BASE_DIR/oclang/test.c
```
gives the following error with SDK 10.14 (and gcc 9.2.0):
```
testing o64-gcc ... + o64-gcc /softs/build/osxcross/oclang/test.c -O2 -Wall -o test
osxcross: debug: --> o64-gcc /softs/build/osxcross/oclang/test.c -O2 -Wall -o test 
osxcross: debug: <-- /softs/osxcross-sdk10.13-min10.9-clang8.0.0-gcc9.1.0/bin/x86_64-apple-darwin17-base-gcc (x86_64-apple-darwin17-gcc) -static-libgcc -static-libstdc++ -Wl,-no_compact_unwind -isystem /softs/osxcross-sdk10.13-min10.9-clang8.0.0-gcc9.1.0/bin/../SDK/MacOSX10.13.sdk -mmacosx-version-min=10.13.0 -m64 /softs/build/osxcross/oclang/test.c -O2 -Wall -o test 
osxcross: debug: === time spent in wrapper: 285.903 ms
Assembler messages:
Fatal error: invalid listing option `r'
```
Built on Linux Fedora 30.

It seems that lines 213 and 214 should be enclosed by:
```
if [ $(osxcross-cmp $OSXCROSS_SDK_VERSION "<=" 10.13) -eq 1 ]; then
...
fi
```

**Comment by tpoechtrager** [comment]
It looks like you have moved the `OSXCross` directory after building. Don't do that.
Or try adjusting `--with-ld` and `--with-as` in `build_gcc.sh`.

**Comment by kivadiu** [comment]
No, I did not move anything. I just did the following from the source directory of osxcross:
```
UNATTENDED=1 OSX_VERSION_MIN=10.9 ./build.sh
GCC_VERSION=9.2.0 ./build_gcc.sh
```

**Comment by tpoechtrager** [comment]
Or symlinked. I don't know.

`/softs/build/osxcross` != `/softs/osxcross-sdk10.13-min10.9-clang8.0.0-gcc9.1.0`

**Comment by kivadiu** [comment]
Oh, I see, this is the previous version I built and it was still in the path.
I removed it and it builds.
Thanks
