### ISSUE TITLE
building cctools/otool fails on linux with clang-8.0.0

### ISSUE THREAD

**Issue by robohack** [tpoechtrager/osxcross#192]
I'm finally back to working on this, but I'm having trouble building `cctools/otool` in my environment, which is an older Debian system.

Let me know if I should re-post this issue in cctools-port or if there's any other information that might be helpful.

I'm working from the following commit:
<pre>
osxcross:
commit f67ce5033d0a01292c9ef156b95c025a3e1edcbc
</pre>

and this checks out the following:
<pre>
cctools-port:
commit 8bd2c684ac84c33849ef169ef6b9f84e9afeb3fa
</pre>

I've installed clang-8.0.0 in $HOME:

<pre>
$ clang --version
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/gaw/bin
</pre>

Note there are two quite different errors killing the compile here, one with a macro vs. variable name that seems be be inherent in the cctools-port source, and another with the `fpclassify()` declaration mismatch which seems to be a portability problem with my build host:

<pre>
Making all in otool
make.x64-linux[1]: Entering directory `/home/gaw/work/osxcross/build/cctools-port/cctools/otool'
clang -DPACKAGE_NAME=\"cctools\" -DPACKAGE_TARNAME=\"cctools\" -DPACKAGE_VERSION=\"921\" -DPACKAGE_STRING=\"cctools\ 921\" -DPACKAGE_BUGREPORT=\"t.poechtrager@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DEMULATED_HOST_CPU_TYPE=16777223 -DEMULATED_HOST_CPU_SUBTYPE=3 -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -DHAVE_EXECINFO_H=1 -DHAVE_UUID_UUID_H=1 -DHAVE_UTIMENSAT=1 -DHAVE_STAT_ST_MTIM=1 -DHAVE_XAR_XAR_H=1 -I.   -I/home/gaw/include -isystem /home/gaw/work/osxcross/target/include -isystem /home/gaw/work/osxcross/target/include -I../include -I../include/foreign -I../libstuff -I../libobjc2 -Wall -Wno-long-long -Wno-import -Wno-format -Wno-deprecated -Wno-unused-variable -Wno-unused-private-field -Wno-unused-function -Wno-invalid-offsetof -Wno-int-conversion -Wno-char-subscripts -Wno-shift-negative-value -DLTO_SUPPORT -D_DARWIN_C_SOURCE -D__DARWIN_UNIX03 -D__LITTLE_ENDIAN__=1 -DOTOOL -DEFI_SUPPORT -O3 -isystem /usr/local/include -isystem /usr/pkg/include -c -o otool-main.o `test -f 'main.c' || echo './'`main.c
In file included from main.c:44:
In file included from ../include/stuff/llvm.h:4:
In file included from /home/gaw/include/llvm-c/Disassembler.h:18:
/home/gaw/include/llvm-c/DisassemblerTypes.h:42:59: error: expected ')'
typedef int (*LLVMOpInfoCallback)(void *DisInfo, uint64_t PC,
                                                          ^
../include/architecture/sparc/reg.h:43:13: note: expanded from macro 'PC'
#define PC      (1)
                 ^
/home/gaw/include/llvm-c/DisassemblerTypes.h:42:59: note: to match this '('
../include/architecture/sparc/reg.h:43:12: note: expanded from macro 'PC'
#define PC      (1)
                ^
In file included from main.c:44:
In file included from ../include/stuff/llvm.h:4:
/home/gaw/include/llvm-c/Disassembler.h:102:59: error: expected ')'
                             uint64_t BytesSize, uint64_t PC,
                                                          ^
../include/architecture/sparc/reg.h:43:13: note: expanded from macro 'PC'
#define PC      (1)
                 ^
/home/gaw/include/llvm-c/Disassembler.h:102:59: note: to match this '('
../include/architecture/sparc/reg.h:43:12: note: expanded from macro 'PC'
#define PC      (1)
                ^
main.c:4187:1: error: conflicting types for '__fpclassify'
__fpclassify(long double x)
^
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:346:20: note: previous declaration is here
__MATHDECL_1 (int, __fpclassify,, (_Mdouble_ __value))
                   ^
3 errors generated.
make.x64-linux[1]: *** [otool-main.o] Error 1
make.x64-linux[1]: Leaving directory `/home/gaw/work/osxcross/build/cctools-port/cctools/otool'
make.x64-linux: *** [all-recursive] Error 1

exiting with abnormal exit code (2)
run 'OCDEBUG=1 ./build.sh' to enable debug messages
</pre>

**Comment by tpoechtrager** [comment]
What's your Debian version?

**Comment by robohack** [comment]
<pre>
$ lsb_release  -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
</pre>

**Comment by tpoechtrager** [comment]
I can build `OSXCross` on `Wheezy` without a problem with:

https://github.com/llvm/llvm-project/releases/download/llvmorg-8.0.1/clang+llvm-8.0.1-x86_64-linux-sles11.3.tar.xz

```
# clang -v
clang version 8.0.1 (tags/RELEASE_801/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /root/clang+llvm-8.0.1-x86_64-linux-sles11.3/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.6.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7.2
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.7
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
```

```
...

## Building wrapper ##


patching file usr/include/c++/v1/__hash_table

testing o32-clang++ -stdlib=libc++ -std=c++11 ... works
testing o64-clang++ -stdlib=libc++ -std=c++11 ... works

testing o32-clang ... works
testing o32-clang++ ... works

testing o64-clang ... works
testing o64-clang++ ... works

...
```

```
export PATH=/opt/clang+llvm-8.0.1-x86_64-linux-sles11.3/bin/:$PATH
export LD_LIBRARY_PATH=/opt/clang+llvm-8.0.1-x86_64-linux-sles11.3/lib
export CXX="clang++ -stdlib=libc++"

./build.sh
```

**Comment by robohack** [comment]
So, Clang 8.0.1 is one difference...  But another big difference is where it's installed and which GCC libraries it selects.

I'm also loathe to set `LD_LIBRARY_PATH` -- that's never the right way to build something, especially if you need to be able to install the result on another machine and use it, which is my ultimate goal.

I also didn't set `CXX`....

Hmmm.... so many variables.

If that Clang binary release you linked to can be relocated to `$HOME` I'll try that first (otherwise it takes a very long time to build a new version of Clang!).

<pre>
$ clang -v
clang version 8.0.0 (tags/RELEASE_800/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/gaw/bin
Found candidate GCC installation: /home/gaw/lib/gcc/x86_64-pc-linux-gnu/9.1.1
Selected GCC installation: /home/gaw/lib/gcc/x86_64-pc-linux-gnu/9.1.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
</pre>

**Comment by robohack** [comment]
Success, and without `LD_LIBRARY_PATH`!

I installed the release version of clang-8.0.1 in $HOME, and it works fine there.

Thanks very much for your patience and the clues that helped me along!

I was then able to use the following command to build osxcross:

<pre>
CXX="clang++ -stdlib=libc++" PATH=$HOME/clang+llvm-8.0.1-x86_64-linux-sles11.3/bin:$PATH LDFLAGS="-L$HOME/clang+llvm-8.0.1-x86_64-linux-sles11.3/lib -Wl,-R$HOME/clang+llvm-8.0.1-x86_64-linux-sles11.3/lib" UNATTENDED=1 INSTALLPREFIX=$HOME ./build.sh > build.out 2>&1
</pre>

From the tail of `build.out`:

<pre>
testing o64-clang++ -stdlib=libc++ -std=c++11 ... works

testing o64-clang ... works
testing o64-clang++ ... works

Do not forget to add

/home/gaw/work/osxcross/target/bin

to your PATH variable.

All done! Now you can use o32-clang(++) and o64-clang(++) like a normal compiler.

Example usage:

Example 1: CC=o32-clang ./configure --host=i386-apple-darwin18
Example 2: CC=i386-apple-darwin18-clang ./configure --host=i386-apple-darwin18
Example 3: o64-clang -Wall test.c -o test
Example 4: x86_64-apple-darwin18-strip -x test

Your SDK does not support i386 anymore.
Use <= 10.13 SDK if you rely on i386 support.

Your SDK does not support libstdc++ anymore.
Use <= 10.13 SDK if you rely on libstdc++ support.

</pre>
