### ISSUE TITLE
Fix for #211 makes another bug

### ISSUE THREAD

**Issue by JulyIghor** [tpoechtrager/osxcross#212]
After this fix #211 

Qt5 no longer compiled on Linux x86_64

```
 5506 Undefined symbols for architecture x86_64:
5507   "std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000000ll> > >)", referenced from:
5508       std::__1::cv_status std::__1::condition_variable::wait_for<long long, std::__1::ratio<1ll, 1000000000ll> >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000000ll> > const&) in qwebglcontext.o
5509 ld: symbol(s) not found for architecture x86_64
```

**Comment by tpoechtrager** [comment]
Are you sure the fix for #211 is the cause of the linker errors? I have `diff`'d the header sources and I wouldn't know what would cause this.

**Comment by JulyIghor** [comment]
yes I do confirm, tried many times, git checkout 542acc2ef6 solves problem
openssl, zlib, mariadb compiled fine in latest commit, but Qt 5.14.1 is not

**Comment by tpoechtrager** [comment]
I have reverted the "fix". What's the exact SDK version you are using? What xcode image did you use to create the SDK from?

**Comment by tpoechtrager** [comment]
Fixed the fix. :-)

Thank you for reporting this.
