### ISSUE TITLE
MacOSSDK 10.15 with minimum target lower than 10.14 works incorrectly

### ISSUE THREAD

**Issue by JulyIghor** [tpoechtrager/osxcross#214]
I'm compiling Qt5.14.1 with osxcross and the only successful build was with minimum target 10.14
But, I can do successful builds of Qt5 in the real macOS with minimum target 10.13, so it is looks like something wrong with header defines in osxcross.
I'm getting errors like unresolved functions that available only from sdk 10.14
Any advice to fix that?

**Comment by tpoechtrager** [comment]
It would be of help if you could post the error messages and the exact SDK you are using.

**Comment by JulyIghor** [comment]
SDK latest, 10.15

Here is error output:
```
Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      qt_mac_applicationIsInDarkMode() in libQt5Core.a(qcore_mac_objc.o)
      QMacStylePrivate::cocoaControl(QMacStylePrivate::CocoaControl) const in libqmacstyle.a(qmacstyle_mac.o)
      qt_mac_createSystemPalette() in libqcocoa.a(qcocoatheme.o)
      qt_mac_createRolePalettes() in libqcocoa.a(qcocoatheme.o)
      std::__1::__function::__func<QCocoaTheme::QCocoaTheme()::$_0, std::__1::allocator<QCocoaTheme::QCocoaTheme()::$_0>, void ()>::operator()() in libqcocoa.a(qcocoatheme.o)
```
Here is source of the function that couldn't compile https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qcore_mac_objc.mm#n223

**Comment by tpoechtrager** [comment]
Install compiler-rt.

`./build_compiler_rt.sh`

**Comment by JulyIghor** [comment]
> Install compiler-rt.
> 
> `./build_compiler_rt.sh`

And what if I'm getting this error?

`CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1163   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1164   function named: get_compiler_rt_output_dir
1165 Call Stack (most recent call first):
1166   lib/stats/CMakeLists.txt:23 (add_compiler_rt_runtime)
1167 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1168   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1169   function named: get_compiler_rt_install_dir
1170 Call Stack (most recent call first):
1171   lib/stats/CMakeLists.txt:23 (add_compiler_rt_runtime)
1172 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1173   set_target_output_directories Function invoked with incorrect arguments for
1174   function named: set_target_output_directories
1175 Call Stack (most recent call first):
1176   lib/stats/CMakeLists.txt:23 (add_compiler_rt_runtime)
1177 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1178   install TARGETS given no LIBRARY DESTINATION for shared library target
1179   "clang_rt.stats_osx_dynamic".
1180 Call Stack (most recent call first):
1181   lib/stats/CMakeLists.txt:23 (add_compiler_rt_runtime)
1182 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1183   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1184   function named: get_compiler_rt_output_dir
1185 Call Stack (most recent call first):
1186   lib/stats/CMakeLists.txt:37 (add_compiler_rt_runtime)
1187 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1188   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1189   function named: get_compiler_rt_install_dir
1190 Call Stack (most recent call first):
1191   lib/stats/CMakeLists.txt:37 (add_compiler_rt_runtime)
1192 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1193   set_target_output_directories Function invoked with incorrect arguments for
1194   function named: set_target_output_directories
1195 Call Stack (most recent call first):
1196   lib/stats/CMakeLists.txt:37 (add_compiler_rt_runtime)
1197 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1198   install TARGETS given no ARCHIVE DESTINATION for static library target
1199   "clang_rt.stats_client_osx".
1200 Call Stack (most recent call first):
1201   lib/stats/CMakeLists.txt:37 (add_compiler_rt_runtime)
1202 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1203   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1204   function named: get_compiler_rt_output_dir
1205 Call Stack (most recent call first):
1206   lib/lsan/CMakeLists.txt:48 (add_compiler_rt_runtime)
1207 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1208   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1209   function named: get_compiler_rt_install_dir
1210 Call Stack (most recent call first):
1211   lib/lsan/CMakeLists.txt:48 (add_compiler_rt_runtime)
1212 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1213   set_target_output_directories Function invoked with incorrect arguments for
1214   function named: set_target_output_directories
1215 Call Stack (most recent call first):
1216   lib/lsan/CMakeLists.txt:48 (add_compiler_rt_runtime)
1217 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1218   install TARGETS given no LIBRARY DESTINATION for shared library target
1219   "clang_rt.lsan_osx_dynamic".
1220 Call Stack (most recent call first):
1221   lib/lsan/CMakeLists.txt:48 (add_compiler_rt_runtime)
1222 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1223   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1224   function named: get_compiler_rt_output_dir
1225 Call Stack (most recent call first):
1226   lib/ubsan/CMakeLists.txt:90 (add_compiler_rt_runtime)
1227 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1228   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1229   function named: get_compiler_rt_install_dir
1230 Call Stack (most recent call first):
1231   lib/ubsan/CMakeLists.txt:90 (add_compiler_rt_runtime)
1232 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1233   set_target_output_directories Function invoked with incorrect arguments for
1234   function named: set_target_output_directories
1235 Call Stack (most recent call first):
1236   lib/ubsan/CMakeLists.txt:90 (add_compiler_rt_runtime)
1237 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1238   install TARGETS given no LIBRARY DESTINATION for shared library target
1239   "clang_rt.ubsan_osx_dynamic".
1240 Call Stack (most recent call first):
1241   lib/ubsan/CMakeLists.txt:90 (add_compiler_rt_runtime)
1242 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1243   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1244   function named: get_compiler_rt_output_dir
1245 Call Stack (most recent call first):
1246   lib/ubsan/CMakeLists.txt:104 (add_compiler_rt_runtime)
1247 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1248   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1249   function named: get_compiler_rt_install_dir
1250 Call Stack (most recent call first):
1251   lib/ubsan/CMakeLists.txt:104 (add_compiler_rt_runtime)
1252 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1253   set_target_output_directories Function invoked with incorrect arguments for
1254   function named: set_target_output_directories
1255 Call Stack (most recent call first):
1256   lib/ubsan/CMakeLists.txt:104 (add_compiler_rt_runtime)
1257 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1258   install TARGETS given no ARCHIVE DESTINATION for static library target
1259   "clang_rt.ubsan_osx".
1260 Call Stack (most recent call first):
1261   lib/ubsan/CMakeLists.txt:104 (add_compiler_rt_runtime)
1262 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1263   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1264   function named: get_compiler_rt_output_dir
1265 Call Stack (most recent call first):
1266   lib/asan/CMakeLists.txt:171 (add_compiler_rt_runtime)
1267 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1268   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1269   function named: get_compiler_rt_install_dir
1270 Call Stack (most recent call first):
1271   lib/asan/CMakeLists.txt:171 (add_compiler_rt_runtime)
1272 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1273   set_target_output_directories Function invoked with incorrect arguments for
1274   function named: set_target_output_directories
1275 Call Stack (most recent call first):
1276   lib/asan/CMakeLists.txt:171 (add_compiler_rt_runtime)
1277 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1278   install TARGETS given no LIBRARY DESTINATION for shared library target
1279   "clang_rt.asan_osx_dynamic".
1280 Call Stack (most recent call first):
1281   lib/asan/CMakeLists.txt:171 (add_compiler_rt_runtime)
1282 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1283   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1284   function named: get_compiler_rt_output_dir
1285 Call Stack (most recent call first):
1286   lib/tsan/CMakeLists.txt:124 (add_compiler_rt_runtime)
1287 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1288   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1289   function named: get_compiler_rt_install_dir
1290 Call Stack (most recent call first):
1291   lib/tsan/CMakeLists.txt:124 (add_compiler_rt_runtime)
1292 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1293   set_target_output_directories Function invoked with incorrect arguments for
1294   function named: set_target_output_directories
1295 Call Stack (most recent call first):
1296   lib/tsan/CMakeLists.txt:124 (add_compiler_rt_runtime)
1297 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1298   install TARGETS given no LIBRARY DESTINATION for shared library target
1299   "clang_rt.tsan_osx_dynamic".
1300 Call Stack (most recent call first):
1301   lib/tsan/CMakeLists.txt:124 (add_compiler_rt_runtime)
1302 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1303   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1304   function named: get_compiler_rt_output_dir
1305 Call Stack (most recent call first):
1306   lib/ubsan_minimal/CMakeLists.txt:27 (add_compiler_rt_runtime)
1307 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1308   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1309   function named: get_compiler_rt_install_dir
1310 Call Stack (most recent call first):
1311   lib/ubsan_minimal/CMakeLists.txt:27 (add_compiler_rt_runtime)
1312 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1313   set_target_output_directories Function invoked with incorrect arguments for
1314   function named: set_target_output_directories
1315 Call Stack (most recent call first):
1316   lib/ubsan_minimal/CMakeLists.txt:27 (add_compiler_rt_runtime)
1317 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1318   install TARGETS given no ARCHIVE DESTINATION for static library target
1319   "clang_rt.ubsan_minimal_osx".
1320 Call Stack (most recent call first):
1321   lib/ubsan_minimal/CMakeLists.txt:27 (add_compiler_rt_runtime)
1322 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1323   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1324   function named: get_compiler_rt_output_dir
1325 Call Stack (most recent call first):
1326   lib/ubsan_minimal/CMakeLists.txt:35 (add_compiler_rt_runtime)
1327 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1328   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1329   function named: get_compiler_rt_install_dir
1330 Call Stack (most recent call first):
1331   lib/ubsan_minimal/CMakeLists.txt:35 (add_compiler_rt_runtime)
1332 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1333   set_target_output_directories Function invoked with incorrect arguments for
1334   function named: set_target_output_directories
1335 Call Stack (most recent call first):
1336   lib/ubsan_minimal/CMakeLists.txt:35 (add_compiler_rt_runtime)
1337 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1338   install TARGETS given no LIBRARY DESTINATION for shared library target
1339   "clang_rt.ubsan_minimal_osx_dynamic".
1340 Call Stack (most recent call first):
1341   lib/ubsan_minimal/CMakeLists.txt:35 (add_compiler_rt_runtime)
1342 -- Performing Test COMPILER_RT_TARGET_HAS_ATOMICS
1343 -- Performing Test COMPILER_RT_TARGET_HAS_ATOMICS - Success
1344 -- Performing Test COMPILER_RT_TARGET_HAS_FCNTL_LCK
1345 -- Performing Test COMPILER_RT_TARGET_HAS_FCNTL_LCK - Success
1346 -- Performing Test COMPILER_RT_TARGET_HAS_UNAME
1347 -- Performing Test COMPILER_RT_TARGET_HAS_UNAME - Success
1348 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1349   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1350   function named: get_compiler_rt_output_dir
1351 Call Stack (most recent call first):
1352   lib/profile/CMakeLists.txt:115 (add_compiler_rt_runtime)
1353 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1354   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1355   function named: get_compiler_rt_install_dir
1356 Call Stack (most recent call first):
1357   lib/profile/CMakeLists.txt:115 (add_compiler_rt_runtime)
1358 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1359   set_target_output_directories Function invoked with incorrect arguments for
1360   function named: set_target_output_directories
1361 Call Stack (most recent call first):
1362   lib/profile/CMakeLists.txt:115 (add_compiler_rt_runtime)
1363 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1364   install TARGETS given no ARCHIVE DESTINATION for static library target
1365   "clang_rt.profile_osx".
1366 Call Stack (most recent call first):
1367   lib/profile/CMakeLists.txt:115 (add_compiler_rt_runtime)
1368 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1369   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1370   function named: get_compiler_rt_output_dir
1371 Call Stack (most recent call first):
1372   lib/xray/CMakeLists.txt:197 (add_compiler_rt_runtime)
1373 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1374   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1375   function named: get_compiler_rt_install_dir
1376 Call Stack (most recent call first):
1377   lib/xray/CMakeLists.txt:197 (add_compiler_rt_runtime)
1378 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1379   set_target_output_directories Function invoked with incorrect arguments for
1380   function named: set_target_output_directories
1381 Call Stack (most recent call first):
1382   lib/xray/CMakeLists.txt:197 (add_compiler_rt_runtime)
1383 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1384   install TARGETS given no ARCHIVE DESTINATION for static library target
1385   "clang_rt.xray_osx".
1386 Call Stack (most recent call first):
1387   lib/xray/CMakeLists.txt:197 (add_compiler_rt_runtime)
1388 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1389   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1390   function named: get_compiler_rt_output_dir
1391 Call Stack (most recent call first):
1392   lib/xray/CMakeLists.txt:209 (add_compiler_rt_runtime)
1393 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1394   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1395   function named: get_compiler_rt_install_dir
1396 Call Stack (most recent call first):
1397   lib/xray/CMakeLists.txt:209 (add_compiler_rt_runtime)
1398 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1399   set_target_output_directories Function invoked with incorrect arguments for
1400   function named: set_target_output_directories
1401 Call Stack (most recent call first):
1402   lib/xray/CMakeLists.txt:209 (add_compiler_rt_runtime)
1403 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1404   install TARGETS given no ARCHIVE DESTINATION for static library target
1405   "clang_rt.xray-fdr_osx".
1406 Call Stack (most recent call first):
1407   lib/xray/CMakeLists.txt:209 (add_compiler_rt_runtime)
1408 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1409   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1410   function named: get_compiler_rt_output_dir
1411 Call Stack (most recent call first):
1412   lib/xray/CMakeLists.txt:219 (add_compiler_rt_runtime)
1413 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1414   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1415   function named: get_compiler_rt_install_dir
1416 Call Stack (most recent call first):
1417   lib/xray/CMakeLists.txt:219 (add_compiler_rt_runtime)
1418 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1419   set_target_output_directories Function invoked with incorrect arguments for
1420   function named: set_target_output_directories
1421 Call Stack (most recent call first):
1422   lib/xray/CMakeLists.txt:219 (add_compiler_rt_runtime)
1423 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1424   install TARGETS given no ARCHIVE DESTINATION for static library target
1425   "clang_rt.xray-basic_osx".
1426 Call Stack (most recent call first):
1427   lib/xray/CMakeLists.txt:219 (add_compiler_rt_runtime)
1428 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1429   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1430   function named: get_compiler_rt_output_dir
1431 Call Stack (most recent call first):
1432   lib/xray/CMakeLists.txt:229 (add_compiler_rt_runtime)
1433 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1434   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1435   function named: get_compiler_rt_install_dir
1436 Call Stack (most recent call first):
1437   lib/xray/CMakeLists.txt:229 (add_compiler_rt_runtime)
1438 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1439   set_target_output_directories Function invoked with incorrect arguments for
1440   function named: set_target_output_directories
1441 Call Stack (most recent call first):
1442   lib/xray/CMakeLists.txt:229 (add_compiler_rt_runtime)
1443 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1444   install TARGETS given no ARCHIVE DESTINATION for static library target
1445   "clang_rt.xray-profiling_osx".
1446 Call Stack (most recent call first):
1447   lib/xray/CMakeLists.txt:229 (add_compiler_rt_runtime)
1448 -- Performing Test HAS_THREAD_LOCAL
1449 -- Performing Test HAS_THREAD_LOCAL - Success
1450 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1451   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1452   function named: get_compiler_rt_output_dir
1453 Call Stack (most recent call first):
1454   lib/fuzzer/CMakeLists.txt:104 (add_compiler_rt_runtime)
1455 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1456   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1457   function named: get_compiler_rt_install_dir
1458 Call Stack (most recent call first):
1459   lib/fuzzer/CMakeLists.txt:104 (add_compiler_rt_runtime)
1460 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1461   set_target_output_directories Function invoked with incorrect arguments for
1462   function named: set_target_output_directories
1463 Call Stack (most recent call first):
1464   lib/fuzzer/CMakeLists.txt:104 (add_compiler_rt_runtime)
1465 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1466   install TARGETS given no ARCHIVE DESTINATION for static library target
1467   "clang_rt.fuzzer_osx".
1468 Call Stack (most recent call first):
1469   lib/fuzzer/CMakeLists.txt:104 (add_compiler_rt_runtime)
1470 CMake Error at cmake/Modules/AddCompilerRT.cmake:197 (get_compiler_rt_output_dir):
1471   get_compiler_rt_output_dir Function invoked with incorrect arguments for
1472   function named: get_compiler_rt_output_dir
1473 Call Stack (most recent call first):
1474   lib/fuzzer/CMakeLists.txt:112 (add_compiler_rt_runtime)
1475 CMake Error at cmake/Modules/AddCompilerRT.cmake:198 (get_compiler_rt_install_dir):
1476   get_compiler_rt_install_dir Function invoked with incorrect arguments for
1477   function named: get_compiler_rt_install_dir
1478 Call Stack (most recent call first):
1479   lib/fuzzer/CMakeLists.txt:112 (add_compiler_rt_runtime)
1480 CMake Error at cmake/Modules/AddCompilerRT.cmake:301 (set_target_output_directories):
1481   set_target_output_directories Function invoked with incorrect arguments for
1482   function named: set_target_output_directories
1483 Call Stack (most recent call first):
1484   lib/fuzzer/CMakeLists.txt:112 (add_compiler_rt_runtime)
1485 CMake Error at cmake/Modules/AddCompilerRT.cmake:302 (install):
1486   install TARGETS given no ARCHIVE DESTINATION for static library target
1487   "clang_rt.fuzzer_no_main_osx".
1488 Call Stack (most recent call first):
1489   lib/fuzzer/CMakeLists.txt:112 (add_compiler_rt_runtime)`

**Comment by tpoechtrager** [comment]
Always post as much information as possible.

The OS you are on and its version, **exact** compiler version, CMake version, ...

**Comment by JulyIghor** [comment]
Thanks for the fast answer.
I'm using docker, debian:latest, debian:stretch updated, (both same effect)
Linux a597891216d9 4.14.154-boot2docker #1 SMP Thu Nov 14 19:19:08 UTC 2019 x86_64 GNU/Linux
cmake version 3.13.4 and also tried to update it to 3.16.5
So I'm just using latest Debian Buster and this script
`export DEBIAN_FRONTEND=noninteractive
export SDK_VERSION=${OSX_SDK_VERSION}
export OSX_VERSION_MIN=${OSX_DEPLOYMENT_VERSION}
export UNATTENDED=1

apt-get update > /dev/null && apt-get upgrade -yy  > /dev/null && apt-get install -yy \
        automake            \
        bison               \
        curl                \
        file                \
        flex                \
        git                 \
        libtool             \
        pkg-config          \
        python              \
        texinfo             \
        cmake               \
        wget                \
        libxml2-dev         \
        libssl-dev libz-dev \
        gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev > /dev/null || exit 1

cd "$START_DIR"
git clone https://github.com/tpoechtrager/osxcross > /dev/null && rm -rf ./.git || exit 1

cd ./osxcross

wget -nc -nv -O "${START_DIR}/osxcross/tarballs/MacOSX${OSX_SDK_VERSION}.sdk.tar.xz" "${CDN_URL}/macOS/MacOSX${OSX_SDK_VERSION}.sdk.tar.xz" || exit 1

yes | PORTABLE=true ./build.sh > /dev/null || exit 1

PATH=/opt/osxcross/target/bin:$PATH \
./build_compiler_rt.sh > /dev/null || exit 1`

**Comment by tpoechtrager** [comment]
Next time also append the CMake log. Now I had to install Buster via deboostrap just figure out a symlink is missing.

    -- Detecting CXX compile features - done
    -- Looking for unwind.h
    -- Looking for unwind.h - found
    -- Looking for rpc/xdr.h
    -- Looking for rpc/xdr.h - not found
    CMake Warning at cmake/Modules/CompilerRTUtils.cmake:211 (message):
    UNSUPPORTED COMPILER-RT CONFIGURATION DETECTED: llvm-config not found.

    Reconfigure with -DLLVM_CONFIG_PATH=path/to/llvm-config.
    Call Stack (most recent call first):
    CMakeLists.txt:77 (load_llvm_config)


    -- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
    CMake Error at cmake/Modules/CompilerRTUtils.cmake:317 (string):
    string sub-command REPLACE requires at least four arguments.
    Call Stack (most recent call first):
    CMakeLists.txt:106 (construct_compiler_rt_default_triple)


    -- Looking for fopen in c
    -- Looking for fopen in c - found
    -- Looking for __gcc_personality_v0 in gcc_s
    -- Looking for __gcc_personality_v0 in gcc_s - not found


`ln -sf /usr/bin/llvm-config-10 /usr/bin/llvm-config`

**Comment by JulyIghor** [comment]
Thanks! I successfully installed compiler_rt, but the error is here anyway

```00 Undefined symbols for architecture x86_64:
5301   "___isOSVersionAtLeast", referenced from:
5302       qt_mac_applicationIsInDarkMode() in libQt5Core.a(qcore_mac_objc.o)
5303       QMacStylePrivate::cocoaControl(QMacStylePrivate::CocoaControl) const in libqmacstyle.a(qmacstyle_mac.o)
5304       qt_mac_createSystemPalette() in libqcocoa.a(qcocoatheme.o)
5305       qt_mac_createRolePalettes() in libqcocoa.a(qcocoatheme.o)
5306       std::__1::__function::__func<QCocoaTheme::QCocoaTheme()::$_0, std::__1::allocator<QCocoaTheme::QCocoaTheme()::$_0>, void ()>::operator()() in libqcocoa.a(qcocoatheme.o)
5307 ld: symbol(s) not found for architecture x86_64
5308 clang: error: linker command failed with exit code 1 (use -v to see invocation)
5309 make[3]: *** [Makefile:143: ../../bin/qml.app/Contents/MacOS/qml] Error 1
5310 make[2]: *** [Makefile:161: sub-qml-make_first] Error 2
5311 make[1]: *** [Makefile:81: sub-tools-make_first] Error 2
5312 make: *** [Makefile:280: module-qtdeclarative-make_first] Error 2```

**Comment by tpoechtrager** [comment]
Verify compiler-rt is correctly installed.

https://github.com/tpoechtrager/osxcross/blob/master/README.COMPILER-RT.md#installation

__isOSVersionAtleast() is defined in compiler-rt
https://github.com/llvm-mirror/compiler-rt/blob/69445f095c22aac2388f939bedebf224a6efcdaf/lib/builtins/os_version_check.c#L204


Ighor July <notifications@github.com> schrieb am Do., 5. März 2020, 21:56:

**Comment by JulyIghor** [comment]
I see, It failed because I made own xcrun, and osxcross does have own xcrun command.
But with xcrun command from the osxcross I'm unable to compile Qt since it not recognizes some commands.
I'll fix it by myself, but if you want to fix it in the osxcross itself, here is info:

`xcrun --sdk macosx --show-sdk-platform-path`
osxcross: `osxcross: error: xcrun: unknown argument: '--show-sdk-platform-path'`
macOS: `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform`

xcrun -find xcodebuild
osxcross: `osxcross: error: xcrun: cannot find 'xcodebuild' executable`
macOS: `/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild`

xcrun -sdk macosx -find actoolxcrun
this one shows errors on both so it should be not important

**Comment by JulyIghor** [comment]
Well, it is not xcrun fault.
Test `echo "int main(void){return 0;}" | xcrun clang -xc -o/dev/null -v - 2>&1 | \
  grep "libclang_rt" 1>/dev/null && echo "Success"` always failed

Here is script that I used to compile everything on clean Docker from debian:latest

````
#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
export OSX_SDK_VERSION=10.15
export OSX_VERSION_MIN=10.13
export UNATTENDED=1

export SDK_URL='https://mycdn/macOS/MacOSX'${OSX_SDK_VERSION}'.sdk.tar.xz'

echo Installing clang-10

apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get upgrade -yy && \
DEBIAN_FRONTEND=noninteractive apt-get install -yy gpg wget software-properties-common && \
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && \
apt-add-repository "deb http://apt.llvm.org/buster/ llvm-toolchain-buster-10 main" && \
apt-get update && \
apt-get -y install clang-10 lldb-10 || exit 1

for lnk in /usr/bin/*-10; do ln -sf ${lnk} ${lnk%*-10}; done


apt-get install -yy \
        automake            \
        bison               \
        curl                \
        file                \
        flex                \
        git                 \
        libtool             \
        pkg-config          \
        python              \
        texinfo             \
        cmake               \
        wget                \
        libxml2-dev         \
        libssl-dev libz-dev \
        gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev || exit 1

cd '/opt'
git clone https://github.com/tpoechtrager/osxcross && rm -rf ./.git || exit 1

cd ./osxcross

echo Downloading "${SDK_URL}" ..

wget -nc -nv -O "/opt/osxcross/tarballs/MacOSX${OSX_SDK_VERSION}.sdk.tar.xz" "${SDK_URL}" || exit 1

echo Building osxcross ..
yes | PORTABLE=true ./build.sh || exit 1

echo Building compiler rt ..
PATH=/opt/osxcross/target/bin:$PATH \
./build_compiler_rt.sh || exit 1

echo 'int main(void){return 0;}' | /opt/osxcross/target/bin/xcrun clang -xc -o/dev/null -v - 2>&1 | \
  grep "libclang_rt" 1>/dev/null && echo "clang_rt test Success" || { echo "clang_rt tests Failed"; exit 1; }
````

**Comment by JulyIghor** [comment]
Thank you very much for your time and help!

**Comment by tpoechtrager** [comment]
I will add them to `xcrun`. How did you fix the `-find xcbodebuild` issue?

**Comment by JulyIghor** [comment]
I just used latest xcode version, looks like it is really not important for the Qt, it just needs any non empty values.

XCODE_VERSION='11.3.1'
XCODE_BUILD='11C504'

echo -e "Xcode ${XCODE_VERSION}\nBuild version ${XCODE_BUILD}"
