### ISSUE TITLE
[Question] toolchain portability

### ISSUE THREAD

**Issue by sgulls** [tpoechtrager/osxcross#215]
is the $OSXCROSS/target directory able to be tarballed and moved to different locations in the system or are there certain hard links that break if moved from the original build/install directory?

**Comment by tpoechtrager** [comment]
Yes, it can be moved. However, GCC isn't portable due to hardcoded paths.

As an alternative you could set `TARGET_DIR` before building (`TARGET_DIR=path ./build.sh`). Should work with GCC too.
