### ISSUE TITLE
tools/gen_sdk_package_darling_dmg.sh does not work out of the box

### ISSUE THREAD

**Issue by jamie-pate** [tpoechtrager/osxcross#221]
As of 42afa173689bdb8658548442ed13c1185b104ee8 :

Trying to reset to the specified commit doesn't work because it's not referenced by the project's master branch?

The following to forces it to work:

```diff
diff --git a/tools/gen_sdk_package_darling_dmg.sh b/tools/gen_sdk_package_darling_dmg.sh
index 3f7a9da..22ad426 100755
--- a/tools/gen_sdk_package_darling_dmg.sh
+++ b/tools/gen_sdk_package_darling_dmg.sh
@@ -54,6 +54,7 @@ FULL_CLONE=1 \
 
 if [ $f_res -eq 1 ]; then
   pushd $CURRENT_BUILD_PROJECT_NAME &>/dev/null
+  git fetch origin 5f64bc9a3795e0a1c307e9beb099f9035fdd864f
   git reset --hard 5f64bc9a3795e0a1c307e9beb099f9035fdd864f
   mkdir -p build
   pushd build &>/dev/null

```

https://github.com/tpoechtrager/osxcross/blob/2f02baaf90edb802242387d0ad844e5cb2c7240a/tools/gen_sdk_package_darling_dmg.sh#L57

**Comment by jamie-pate** [comment]
The second time I ran it it said 'fatal: refusing to merge unrelated histories'

maybe this would work better?
```
git fetch origin 5f64bc9a3795e0a1c307e9beb099f9035fdd864f
git checkout 5f64bc9a3795e0a1c307e9beb099f9035fdd864f
```

**Comment by tpoechtrager** [comment]
Should be fixed.
