### ISSUE TITLE
build.sh failed, stopped after ## Building xar (master) ##

### ISSUE THREAD

**Issue by nuzillard** [tpoechtrager/osxcross#223]
I typed ./build_sh after having build clang and stored the SDK in tarballs.
"where git" says  /usr/bin/git.
I am trying to install gcc cross compiler for Mac under WSL Ubuntu.

Output in [build_sh_error.txt](https://github.com/tpoechtrager/osxcross/files/4479459/build_sh_error.txt)

Thank you in advance for any suggestion.

**Comment by tpoechtrager** [comment]
I don't know what's wrong. Ensure `git` works. Maybe also try a new clone.

I was able to build OSXCross on WSL without a problem.

**Comment by nuzillard** [comment]
Installing git correctly and restarting installation from scratch solved the problem.
