### ISSUE TITLE
Metal support

### ISSUE THREAD

**Issue by ecumene** [tpoechtrager/osxcross#224]
I'm building a project using `gfx-rs`, and unsuccessfully trying to cross-compile it on a linux machine for a Darwin target. 

Is it possible to configure osxcross so `xcrun` has a metal executable included?

Here is the exact error

`xcrun: cannot find 'metal' executable`

**Comment by Gcenx** [comment]
Outside of using a real mac [darling](https://github.com/darlinghq/darling) mentions Metal compilation support (just some examples), it’s possible some of there would could be incorporated into OSXCROSS?

If `gfx-rx `provided a prebuilt dylib this wouldn’t be required

**Comment by ecumene** [comment]
Apparently I didn't research hard enough, I'll try to see if darling's metal emulation works... If so, it'll be a dream come true

`gfx-rs` requires metal for shader compilation, that is it needs the Xcode dev tools and all. Should they be providing a library a shared library for it? I'm new to linking binaries and such

**Comment by K0bin** [comment]
Darling does not emulate Metal yet. You might be able to get the XCode command line tools running to compile something with Metal but it certainly wont run on Linux.

**Comment by Gcenx** [comment]
@ecumene I didn’t say run Metal just compilation of Metal they tested some basic examples, as @K0bin says you can’t run Metal based applications on darling (yet)

If your needing to not just come like but also test your application then you’ll be needing a real Mac.

The alternative for compilation is using an Azure pipeline, they have Mojave and above images still in service. While you could change the deployment target it will also depend on what version of Metal your targeting.

**Comment by ecumene** [comment]
Yes! That's exactly what I need... XCode CLI tools for shader compilation. The intention isn't to make it run on linux, it's to compile it quickly in the cloud. What I meant by metal emulation was these tools, sorry if it was unclear.

I just did a test of azure pipelines and I don't believe it will work. It's far too slow with the job waiting in queue for ~12 seconds and the Hello World job running in more than 5. I'll attempt to get the xcode tools to work in darling.

My actual goal is to compile my app in the cloud on a more powerful machine than my laptop and download to run it locally. For positive returns on this endeavour the time to compile needs to be less than 10 seconds.

I have a new laptop on the way, but in times like these it could be weeks before it gets here so I'm occupying myself with this!
