### ISSUE TITLE
Question about sdks

### ISSUE THREAD

**Issue by demhademha** [tpoechtrager/osxcross#231]
Hi, so I visited this github repo: https://github.com/phracker/MacOSX-SDKs would a macosx10.15.sdk work from here? Or would I have to use the provided script?
Any help would be appreciated

**Comment by HinTak** [comment]
I think 10.15 is a bit too recent...( 10.14 / 10.13 better ) though I am not the author.

**Comment by tpoechtrager** [comment]
Up to 10.15 works. The phracker SDKs should be avoided because they tend to be broken.
