### ISSUE TITLE
Issue with cmake and build_clang.sh

### ISSUE THREAD

**Issue by demhademha** [tpoechtrager/osxcross#232]
System: ubuntu 20.04 
When running ./build_clang.sh I get the following error:
cleaning up ...
extracting llvm-9.0.0.src.tar.xz ...
extracting cfe-9.0.0.src.tar.xz ...
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler
    "/usr/bin/cc"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: /home/ahmed/osxcross/build/llvm-9.0.0.src/build_stage1/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_f3c52/fast && /usr/bin/make -f CMakeFiles/cmTC_f3c52.dir/build.make CMakeFiles/cmTC_f3c52.dir/build
    make[1]: Entering directory '/home/ahmed/osxcross/build/llvm-9.0.0.src/build_stage1/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_f3c52.dir/testCCompiler.c.o
    /usr/bin/cc    -o CMakeFiles/cmTC_f3c52.dir/testCCompiler.c.o   -c /home/ahmed/osxcross/build/llvm-9.0.0.src/build_stage1/CMakeFiles/CMakeTmp/te
stCCompiler.c
    fatal error: as: unknown host architecture (can't determine which assembler to run)
    make[1]: *** [CMakeFiles/cmTC_f3c52.dir/build.make:66: CMakeFiles/cmTC_f3c52.dir/testCCompiler.c.o] Error 1
    make[1]: Leaving directory '/home/ahmed/osxcross/build/llvm-9.0.0.src/build_stage1/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_f3c52/fast] Error 2
    
    
  
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:49 (project)
-- Configuring incomplete, errors occurred!
See also "/home/ahmed/osxcross/build/llvm-9.0.0.src/build_stage1/CMakeFiles/CMakeOutput.log".
See also "/home/ahmed/osxcross/build/llvm-9.0.0.src/build_stage1/CMakeFiles/CMakeError.log".
exiting with abnormal exit code (1)
run 'OCDEBUG=1 ./build_clang.sh' to enable debug messages

Cc is installed.

**Comment by tpoechtrager** [comment]
https://github.com/tpoechtrager/cctools-port/issues/87#issuecomment-661117000
