### ISSUE TITLE
Gcc

### ISSUE THREAD

**Issue by demhademha** [tpoechtrager/osxcross#234]
Hi, when typing in "./build.sh" 
I get the following error:
Checking for gcc...clang
Error: c compiler cannot make executables,
Gcc is is installed, and in addition typing "CC=gcc ./build.sh" doesn't fix the issue, 
Gcc is working fine. 
Thanks for the support.

**Comment by tpoechtrager** [comment]
`clang` is the required compiler for building `OSXCross`. Have a look at the [README](https://github.com/tpoechtrager/osxcross#installation) please.

**Comment by demhademha** [comment]
Hi @tpoechtrager clang is already installed, running OCDEBUG=1 ./build.sh gives the folllowing output:

$ OCDEBUG=1 ./build.sh
+ git fetch origin master
From https://github.com/tpoechtrager/xar
 * branch            master     -> FETCH_HEAD
+ git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
+ git pull origin master
From https://github.com/tpoechtrager/xar
 * branch            master     -> FETCH_HEAD
Already up to date.
++ git rev-parse HEAD
+ local new_hash=2b9a4ab7003f1db8c54da4fea55fcbb424fdecb0
+ local old_hash=
+ local hash_file=/home/ahmed/Downloads/osxcross/build/.xar_git_hash
+ '[' -f /home/ahmed/Downloads/osxcross/build/.xar_git_hash ']'
++ cat /home/ahmed/Downloads/osxcross/build/.xar_git_hash
+ old_hash=2b9a4ab7003f1db8c54da4fea55fcbb424fdecb0
+ echo -n 2b9a4ab7003f1db8c54da4fea55fcbb424fdecb0
+ '[' 2b9a4ab7003f1db8c54da4fea55fcbb424fdecb0 '!=' 2b9a4ab7003f1db8c54da4fea55fcbb424fdecb0 ']'
+ f_res=0
+ popd
+ '[' 0 -eq 1 ']'
+ '[' -f /home/ahmed/Downloads/osxcross/build/._build_complete ']'
+ rm -f /home/ahmed/Downloads/osxcross/build/._build_complete
+ f_res=1
+ '[' 1 -eq 1 ']'
+ pushd xar/xar
+ CFLAGS=' -w'
+ ./configure --prefix=/home/ahmed/Downloads/osxcross/target
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/home/ahmed/Downloads/osxcross/build/xar/xar':
configure: error: C compiler cannot create executables
See `config.log' for more details
+ _exit
+ EC=77
+ '[' 77 -ne 0 ']'
+ test -z build.sh
+ echo ''
+ echo 'exiting with abnormal exit code (77)'
exiting with abnormal exit code (77)
+ test -n 1
+ '[' -n xar ']'
+ rm -f 'build/*_built_successfully'
+ echo ''
+ test build.sh = build.sh
+ check_for_bug_1242300
+ '[' -e /etc/issue ']'
++ grep -i ubuntu.13.10 /etc/issue
+ '[' '' ']'

**Comment by tpoechtrager** [comment]
`clang` must be in `PATH` too. That's why the compiler is not found.

https://en.wikipedia.org/wiki/PATH_(variable)
