### ISSUE TITLE
Fix for FreeBSD build failing on 'stdarg.h' file not found 

### ISSUE THREAD

**Issue by hojothum** [tpoechtrager/osxcross#239]
Fixed (maybe not the right way) by copying `stdarg.h` to `./oclang/quirks/`:
`cp ./target/SDK/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/stdarg.h  ./oclang/quirks/`

---

Build error:
```
+ echo -ne 'testing x86_64-apple-darwin19-clang++ ... '
testing x86_64-apple-darwin19-clang++ ... + x86_64-apple-darwin19-clang++ /home/jenkins/osxcross/oclang/test.cpp -O2 -Wall -o test
osxcross: debug: --> x86_64-apple-darwin19-clang++ /home/jenkins/osxcross/oclang/test.cpp -O2 -Wall -o test 
osxcross: debug: <-- /usr/bin/clang++ (clang++) -target x86_64-apple-darwin19 -mlinker-version=530 -isystem /usr/bin/../lib/clang/8.0.1/include -isysroot /usr/home/jenkins/osxcross/target/bin/../SDK/MacOSX10.15.sdk -stdlib=libc++ -nostdinc++ -Qunused-arguments -cxx-isystem /usr/home/jenkins/osxcross/target/bin/../SDK/MacOSX10.15.sdk/usr/include/c++/v1 -mmacosx-version-min=10.9.0 -arch x86_64 -Wno-liblto /home/jenkins/osxcross/oclang/test.cpp -O2 -Wall -o test 
osxcross: debug: === time spent in wrapper: 0.247 ms
In file included from /home/jenkins/osxcross/oclang/test.cpp:1:
In file included from /usr/home/jenkins/osxcross/target/bin/../SDK/MacOSX10.15.sdk/usr/include/c++/v1/iostream:37:
In file included from /usr/home/jenkins/osxcross/target/bin/../SDK/MacOSX10.15.sdk/usr/include/c++/v1/ios:214:
In file included from /usr/home/jenkins/osxcross/target/bin/../SDK/MacOSX10.15.sdk/usr/include/c++/v1/iosfwd:95:
In file included from /usr/home/jenkins/osxcross/target/bin/../SDK/MacOSX10.15.sdk/usr/include/c++/v1/wchar.h:118:
/usr/home/jenkins/osxcross/target/bin/../SDK/MacOSX10.15.sdk/usr/include/wchar.h:89:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>
         ^~~~~~~~~~
1 error generated.
```

System info:
```
$ uname -a
FreeBSD freebsd 12.1-RELEASE-p8 FreeBSD 12.1-RELEASE-p8 GENERIC  amd64
```

```
$ clang --version
FreeBSD clang version 8.0.1 (tags/RELEASE_801/final 366581) (based on LLVM 8.0.1)
Target: x86_64-unknown-freebsd12.1
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by HinTak** [comment]
`stdarg.h` was in POSIX 2008... If it is missing, the OS is probably a bit old...

**Comment by hojothum** [comment]
It does exist at `/usr/include/stdarg.h`

**Comment by HinTak** [comment]
On my system (fedora 32), they exist as compiler-specific headers, `/usr/lib/gcc/<arch-triplet>/<version>/include/stdarg.h` (I have 5, the host plus arm and win 32-/64- cross) and `/usr/lib64/clang/<version>/include/stdarg.h` for clang. So it would appear that FreeBSD's has the compiler missing part of its install or not finding its own parts?

**Comment by hojothum** [comment]
Aside from the osxcross directories, here are all the locations where `stdarg.h` is found:
```
/usr/include/machine/stdarg.h
/usr/include/x86/stdarg.h
/usr/include/stdarg.h
/usr/local/lib/gcc9/include/c++/tr1/stdarg.h
/usr/local/lib/gcc9/gcc/x86_64-portbld-freebsd12.1/9.3.0/include/stdarg.h
```

clang/llvm is the system compiler.  gcc9 was installed separately.  

osxcross is being built with clang.

I assumed the Mac OS X SDK `stdargs.h` should be used when cross-compiling.  Is my assumption incorrect?

**Comment by HinTak** [comment]
Xcode / Mac OS SDK ships a `stdarg.h` under `Kernel.framework/Headers` (plus symlinks to other part of Kernel.Framework). My osxcross-gcc also has its private copy under `target/lib/gcc/x86_64-apple-darwinX/<version>/include/stdarg.h` though.

**Comment by tpoechtrager** [comment]
`stdarg.h` usually comes with the compiler:

    $ echo "#include <stdarg.h>" | xcrun clang -xc -E -
    # 1 "<stdin>"
    # 1 "<built-in>" 1
    # 1 "<built-in>" 3
    # 350 "<built-in>" 3
    # 1 "<command line>" 1
    # 1 "<built-in>" 2
    # 1 "<stdin>" 2
    # 1 "/opt/llvm/llvm-11/bin/../lib/clang/11.0.0/include/stdarg.h" 1 3
    # 14 "/opt/llvm/llvm-11/bin/../lib/clang/11.0.0/include/stdarg.h" 3
    typedef __builtin_va_list va_list;
    # 32 "/opt/llvm/llvm-11/bin/../lib/clang/11.0.0/include/stdarg.h" 3
    typedef __builtin_va_list __gnuc_va_list;
    # 2 "<stdin>" 2

Should be fixed.
