### ISSUE TITLE
error: thread-local storage is not supported for the current target

### ISSUE THREAD

**Issue by abrodkin** [tpoechtrager/osxcross#244]
```
$ cat <<EOF > test.c
_Thread_local int x;
EOF

$ o64-clang -c test.c
test.c:1:1: error: thread-local storage is not supported for the current target
_Thread_local int x;
^
1 error generated.

$ o64-clang --version
clang version 10.0.1 (/osxcross/build/llvm-10.0.1.src/tools/clang 29500b20934615b8b96790839f88802ef641f5a1)
Target: x86_64-apple-darwin14
Thread model: posix
```

That I figured out when failed to configure recent libusb (https://github.com/libusb/libusb/) which after https://github.com/libusb/libusb/commit/9a1bc8cafb904c20a869c74ad6d657686a1c4bb1 checks for C11 that way (extract from `config.log`):
```
| _Thread_local int x;
| int
| main ()
| {
| x = 42;
|   ;
|   return 0;
| }
configure:15510: result: no
configure:15517: checking if o64-clang supports -std=c11
configure:15530: o64-clang -c -std=c11  conftest.c >&5
conftest.c:23:1: error: thread-local storage is not supported for the current target
_Thread_local int x;
^
1 error generated.
```

FWIW I built `osxcross` with `SDK_VERSION=10.10 OSX_VERSION_MIN=10.6` maybe SDK or OSX version are just too "conservative"?

**Comment by tpoechtrager** [comment]
I think think `_Thread_local` requires at least 10.7 or 10.8.

`o64-clang -c test.c -mmacosx-version-min=10.7` or `export MACOSX_DEPLOYMENT_TARGET=10.7`.

**Comment by abrodkin** [comment]
Indeed adding (or exporting) of `MACOSX_DEPLOYMENT_TARGET=10.7` fixes configuration & building of recent libusb.
Thanks for the suggestion!
