### ISSUE TITLE
Gtk-WARNING **: 21:50:20.454: cannot open display: :0

### ISSUE THREAD

**Issue by efa** [tpoechtrager/osxcross#252]
I'm generating QT macOS packages, where the dylibs point all to:
@executable_path
and work.

But I made a test using GTK, here the package:
https://drive.google.com/file/d/1pzhY3U9JZtQfzN6qo_lEynq5ecjLibLx
and I got this error:

$ DISPLAY=:0; export DISPLAY
$ cairo
Gtk-WARNING **: 21:50:20.454: cannot open display: :0

and the app does not start.

Apparently the GTK app depend on XQuartz instead of Quartz, some one can help me to fix this?
thank you

**Comment by HinTak** [comment]
I think it is a build configuration of GTK to use CoreGraphics instead of X11. Your GTK is likely mis-built at the configure stage.

**Comment by efa** [comment]
I used macports GTK.
I'm buiilding with:
x86_64-apple-darwin20-clang cairo.c -o cairo `x86_64-apple-darwin20-pkg-config --cflags --libs gtk+-2.0`
How can I fix this?

**Comment by efa** [comment]
$OSX is the path of osxcross

$ $OSX/target/bin/x86_64-apple-darwin20-pkg-config --cflags --libs gtk+-2.0

-D_REENTRANT -I$OSX/target/macports/pkgs/opt/local/include/gtk-2.0 -I$OSX/target/macports/pkgs/opt/local/lib/gtk-2.0/include -I$OSX/target/macports/pkgs/opt/local/include/pango-1.0 -I$OSX/target/macports/pkgs/opt/local/include/gio-unix-2.0/ -I$OSX/target/macports/pkgs/opt/local/include -I$OSX/target/macports/pkgs/opt/local/include/cairo -I$OSX/target/macports/pkgs/opt/local/include/atk-1.0 -I$OSX/target/macports/pkgs/opt/local/include/cairo -I$OSX/target/macports/pkgs/opt/local/include/pixman-1 -I$OSX/target/macports/pkgs/opt/local/include -I$OSX/target/macports/pkgs/opt/local/include/gdk-pixbuf-2.0 -I$OSX/target/macports/pkgs/opt/local/include/pango-1.0 -I$OSX/target/macports/pkgs/opt/local/include/harfbuzz -I$OSX/target/macports/pkgs/opt/local/include -I$OSX/target/macports/pkgs/opt/local/include/pango-1.0 -I$OSX/target/macports/pkgs/opt/local/include/fribidi -I$OSX/target/macports/pkgs/opt/local/include/glib-2.0 -I$OSX/target/macports/pkgs/opt/local/lib/glib-2.0/include -I$OSX/target/macports/pkgs/opt/local/include -I$OSX/target/macports/pkgs/opt/local/include/ossp -I$OSX/target/macports/pkgs/opt/local/include/freetype2 -I$OSX/target/macports/pkgs/opt/local/include/libpng16 -I$OSX/target/macports/pkgs/opt/local/include -L$OSX/target/macports/pkgs/opt/local/lib -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -lgio-2.0 -lXrender -lXinerama -lXi -lXrandr -lXcursor -lXcomposite -lXdamage -lXfixes -lX11 -lXext -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation -lfontconfig -lfreetype

**Comment by HinTak** [comment]
Well, you answered your own question: all those `-lgtk-x11-2.0` etc can't be right. You need to contact macport, really.

**Comment by efa** [comment]
so apparently macports's GTK package is build with X target?
That require to install an Xserver, but Xquartz is 32 bit only and so don't work on current macOS.
Can GTK be cross-built for Quartz target using osxcross?

**Comment by HinTak** [comment]
Again, your questions are better addressed by the macport people. They also provide an up-to-date 64-bit xorg x11 server, apparently.

**Comment by efa** [comment]
I had to correct me, current Xquartz is universal binary, are the recent macOS that support only 64 bit apps.
More, current GTK native backend for Quartz is feature incomplete and buggy, probably this is why Macport's GTK target X.
A GTK app built for 64 bit and using a serverX should work

**Comment by efa** [comment]
> I think it is a build configuration of GTK to use CoreGraphics instead of X11. Your GTK is likely mis-built at the configure stage

Can we keep this issue to track macport's GTK bundled by osxcross,
the one spoken here: https://github.com/tpoechtrager/osxcross/blob/master/README.MACPORTS.md
was compiled with XQuartz backend in configure, I think the default should be Quartz

**Comment by HinTak** [comment]
`tools/osxcross-macports` is just a shell script... I think it just download from official macports and unpack to osxcross locations, and it does not build gtk from source.

**Comment by efa** [comment]
I saw that macports distribute precompiled packages for both gtk2 and gtk3:
https://ports.macports.org/port/gtk2
https://ports.macports.org/port/gtk3
in two "variants":
1) x11 is the one for Xquartz backend
2) quartz is the one for the native macOS interface

As Quartz backend works well, is lighter and require much less dependancies,
I think osxcross should default to Quartz variant

**Comment by HinTak** [comment]
If the official macports offers both, they must have a way of distinguishing them. You may just need to run osxcross-macports with a different argument or something. You need to ask the official macports people. (as I wrote a few times...)

**Comment by efa** [comment]
the official documentation of macports 'port':
https://guide.macports.org/chunked/using.variants.html
say:
1) to see package variants use command variants
2) to select or deselect a package variants use +variant or -variant
but 'osxcross-macports' do not support neither of the two option, if I will ask to macports people as you suggested, surely they can't help me.
So should be a different argument specific to 'osxcross-macports', but documentation in README.MACPORTS does not help.
And this is why I wrote the previous post, to find a working solution

**Comment by HinTak** [comment]
Well, what you want is for osxcross-macports to offer the variants option (at least for the special case of gtk). You still need to find out from the macports people how that option works...

**Comment by efa** [comment]
How the macports option for variants works is well documented in the previous post link, and works on a true macOS.
I don't think I need to ask more about that to macports people.
What I can't do is select a variant of a package with osxcross-macports

**Comment by HinTak** [comment]
Yes you do - you need to find out how that option is **implemented** ...

**Comment by efa** [comment]
parsing "osxcross-macports" I saw the variants options is not implemented

**Comment by HinTak** [comment]
It will likely stay unimplemented if nobody tries to find out how genuine macports implements it...sigh...

**Comment by efa** [comment]
I think macports's port command is opensource
