### ISSUE TITLE
timestamp mismatch warning from compiler when building with '-g' and NFS

### ISSUE THREAD

**Issue by jlsantiago0** [tpoechtrager/osxcross#253]
I get warnings from the compiler when compiling some code. The cwd is mounted over NFS so that may be the root cause. Do you know where in the code I can disable that warning? The object file is in /tmp/ as a temproary file and the debug file is being stored in an NFS mounted directory and the resolution of the NFS timestamps are not as exact as those for local filesystems.

```
oa64e-clang++ -O3 -Wall -std=c++14 -g \
   "toolchain-test/tctest01/test03-c++14-19-reverse-iterators.cpp" \
   -o test03-c++14-19-reverse-iterators.oa64e.clang++.libc++

warning: /tmp/test03-c++14-19-reverse-iterators-b8ff8f.o: timestamp mismatch between object file (2021-01-20 15:35:13.385226924) and debug map (2021-01-20 15:35:13.000000000)
warning: /tmp/test03-c++14-19-reverse-iterators-b8ff8f.o: timestamp mismatch between object file (2021-01-20 15:35:13.385226924) and debug map (2021-01-20 15:35:13.000000000)


```

**Comment by tpoechtrager** [comment]
Update your LLVM installation. The issue has been fixed yesterday https://reviews.llvm.org/rGf354b87df23799ee0b6c718894140c846eafc82d

**Comment by jlsantiago0** [comment]
Thank you . will give it a shot.
