### ISSUE TITLE
compiler_rt is not created for arm64

### ISSUE THREAD

**Issue by s-ag** [tpoechtrager/osxcross#258]
Hello,

even when using the MacOSX11.0.sdk and build_clang.sh to build a brand new compiler, build_rt only seems to create the runtime library with slices for x86_64 and x86_64h.

Thanks,
Holger

And by the way, thank you for the great work you are doing!

**Comment by etrinh** [comment]
Here is the patch I use, if it can be helpful... The idea is to invoke the cmake for arm and lipo the outputs.

[build_compiler_rt_arm64.txt](https://github.com/tpoechtrager/osxcross/files/5957411/build_compiler_rt_arm64.txt)

**Comment by etrinh** [comment]
The patch disable sanitizer for  #259 compilation issue as well

**Comment by s-ag** [comment]
Thanks a lot, that worked very well

**Comment by ancwrd1** [comment]
With clang 12 it worked by just adding additional architectures:

```bash
    CC=$(xcrun -f clang) CXX=$(xcrun -f clang++) $CMAKE .. \
      -DDARWIN_osx_ARCHS="x86_64;x86_64h;arm64" \
      -DDARWIN_osx_BUILTIN_ARCHS="x86_64;x86_64h;arm64" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_SYSTEM_NAME=Darwin \
      -DCMAKE_LIPO=$(xcrun -f lipo) \
      -DCMAKE_OSX_SYSROOT=$(xcrun --show-sdk-path) \
      -DCMAKE_AR=$(xcrun -f ar)
```
