### ISSUE TITLE
Emulate Xcode12 default behavior when using 11.x SDK

### ISSUE THREAD

**Issue by Gcenx** [tpoechtrager/osxcross#264]
Xcode12 by default enables '-Werror,-Wimplicit-function-declaration' (49917738)\
https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes

Is there any way to emulate this behavior within osxcross so it gives accurate results when compared against compiling a project natively on macOS when using Xcode12?

**Comment by Gcenx** [comment]
I understand it’s not desirable but if osxcross is used with an 11.x SDK it should produce the same results as if compiled using Xcode12 and later.

Without this any automated builder that use this would incorrectly assume the issue is on the users end and not the project.

**Comment by tpoechtrager** [comment]
I have added an environment variable to control it. I don't want to enable it by default because it will break a lot of open source libraries that won't see an update any time soon.

    $ x86_64-apple-darwin20.4-clang ~/tmp/test.c
    /home/thomas/tmp/test.c:4:3: warning: implicitly declaring library function 'printf' with type 'int (const char *, ...)' [-Wimplicit-function-declaration]
    printf("Hello World!");
    ^
    /home/thomas/tmp/test.c:4:3: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
    1 warning generated.


    $ export OSXCROSS_ENABLE_WERROR_IMPLICIT_FUNCTION_DECLARATION=1
    $ x86_64-apple-darwin20.4-clang ~/tmp/test.c
    /home/thomas/tmp/test.c:4:3: error: implicitly declaring library function 'printf' with type 'int (const char *, ...)' [-Werror,-Wimplicit-function-declaration]
    printf("Hello World!");
    ^
    /home/thomas/tmp/test.c:4:3: note: include the header <stdio.h> or explicitly provide a declaration for 'printf'
    1 error generated.

**Comment by Gcenx** [comment]
@tpoechtrager thank you, could you add this into the README?

It would be good to make it a known export to emulate the Xcode12 behavior, that’s (currently?) disabled by default for compatibility’s sake.

Also you might want to look at #257 OSXCROSS it’s self is affected by this problem when building using Xcode12.

**Comment by tpoechtrager** [comment]
I updated the README.

Regarding #257 I will have a look at it and fix it soon.

**Comment by Gcenx** [comment]
Thank you.
