### ISSUE TITLE
arm64 toolchain not working with cmake on WSL2

### ISSUE THREAD

**Issue by flriancu** [tpoechtrager/osxcross#268]
Hi @tpoechtrager ,

I'm having some issues producing `arm64` targets on a WSL2 host.

Configuration:
```sh
$ cat /etc/*release | grep PRETTY_NAME
PRETTY_NAME="Ubuntu 20.04.2 LTS"

$ uname -r
4.19.104-microsoft-standard

$ cmake --version | grep version
cmake version 3.20.0

osxcross$ git show
commit dd4f8f329de5b5491cdfaded1c4ca6d12fbcd997 (HEAD -> master, origin/master, origin/HEAD)

osxcross$ ls tarballs/
MacOSX11.1.sdk.tar.xz
```

Build steps:

```sh
git clone https://github.com/tpoechtrager/osxcross

# Get macOS 11.1 SDK archive, this one seems to have been built specifically for use with osxcross
cd osxcross/tarballs/
wget https://github.com/joseluisq/macosx-sdks/releases/download/11.1/MacOSX11.1.sdk.tar.xz
cd ..

# fix newlines in all shell scripts
find . -name '*.sh' -type f -print0 | xargs -0 -n 1 -P 4 dos2unix

# this command runs successfully
UNATTENDED=1 ./build.sh
```

Usage steps for producing a target:

```sh
eval $(${OSXCROSS_ROOT}/tools/osxcross_conf.sh)
export LD_LIBRARY_PATH=${OSXCROSS_ROOT}/target/lib

# producing x86_64 targets has no issues
cmake -B build/macos-x86_64 -S. -D CMAKE_TOOLCHAIN_FILE=toolchain-macos-x86_64.cmake
cmake --build build/macos-x86_64

# producing arm64 targets fails
cmake -B build/macos-arm64 -S. -D CMAKE_TOOLCHAIN_FILE=toolchain-macos-arm64.cmake
cmake --build build/macos-arm64
```

Error message (some paths are redacted):
- full version: https://pastebin.com/BE2its91
- tl;dr: `/usr/bin/ld: unrecognized option '-dynamic'`

Toolchain files:
- x86_64: https://pastebin.com/fLA98yNU
- arm64: https://pastebin.com/qc79gAJk

The project is a simple shared library.

Please let me know if you need more information, for example the project's `CMakeLists.txt`. Thank you!

**Comment by tpoechtrager** [comment]
Either `target/bin` is not in `PATH` or your compiler is broken.

**Comment by Gcenx** [comment]
Did you compile the Apple Clang/LLVM from source?

**Comment by flriancu** [comment]
@Gcenx It worked! I had completely missed the custom cmake. I got it working without any toolchain files:
```
arm64-apple-${OSXCROSS_TARGET}-cmake -B build/macos-arm64 -S. -D CMAKE_BUILD_TYPE=Release
cmake --build build/macos-arm64
```

Note that the custom cmake gives the error below, that's why I used the stock cmake on my machine.
```
CMake Error: Unknown argument --build
```

Feel free to close this ticket, although I'd suggest to keep it open for now. I'd like to spend some more time looking into these issues.

**Comment by Gcenx** [comment]
Here’s the full command when I build `FAudio`
```
x86_64-apple-darwin17-cmake /root/faudio/FAudio
make
make install DESTDIR=install/
```

I never directly call `cmake`

**Comment by Gcenx** [comment]
@flriancu if `--build` is a standard `cmake` flag I might be a good idea to alter this ticket to reflect this missing function so @tpoechtrager can potentially look into possibly supporting this option.

**Comment by realnc** [comment]
This is now fixed: https://github.com/tpoechtrager/osxcross/issues/315

**Comment by flriancu** [comment]
Can confirm.
