### ISSUE TITLE
Ubuntu build fails

### ISSUE THREAD

**Issue by MageSlayer** [tpoechtrager/osxcross#283]
Hi

Trying to build under Ubuntu 20.04.2 via ./build.sh fails with :
```
ln: failed to create symbolic link 'lib/.libs/libxar.so': Operation not permitted
make: *** [lib/Makefile.inc:184: lib/libxar.la] Error 1
```
See build.log.

[build.log](https://github.com/tpoechtrager/osxcross/files/6796559/build.log)

**Comment by tpoechtrager** [comment]
Try to do a fresh clone. There seems to be something wrong with the permissions. Are you on WSL?

**Comment by MageSlayer** [comment]
Yes. It looks like it's related to my attempt building off "shared folder" under VirtualBox.
Cloning right inside VM filesystem solved the issue.
Sorry for noise.
