### ISSUE TITLE
compiler_rt is not being built for SDK 10.5

### ISSUE THREAD

**Issue by dvirtz** [tpoechtrager/osxcross#289]
the check on https://github.com/tpoechtrager/osxcross/blob/551d192714e075f0ec23e48fead7a60b0caf565e/build_compiler_rt.sh#L173 causes the script to skip building compiler_rt for SDK < 11.0

**Comment by tpoechtrager** [comment]
Oh sorry, I forgot to move the `else` when I added another `if` there.
