### ISSUE TITLE
Clarify install prefix for osxcross build.sh script

### ISSUE THREAD

**Issue by mcandre** [tpoechtrager/osxcross#296]
Can I override the default location for osxcross `build.sh` script with a `INSTALLPREFIX` environment variable, similar to the environment variable for `build_clang.sh`?

**Comment by tpoechtrager** [comment]
Yes, there is `TARGET_DIR`.

**Comment by mcandre** [comment]
Confirmed, this works.

I managed to find this clue by browsing the changelog.

Could we update the README to clarify this environment variable?

I initially tried `INSTALLPREFIX`, but that appears to be used only for `build_clang.sh`.

**Comment by tpoechtrager** [comment]
Yes, the README needs some updating. Feel free to file a PR if you want to.

**Comment by mcandre** [comment]
Happily!
