### ISSUE TITLE
'cannot find clang intrinsic headers' warning with clang-3.5 and llvm-3.5-dev

### ISSUE THREAD

**Issue by joostwim** [tpoechtrager/osxcross#30]
I'm using the Ubuntu clang 3.5 packages on Ubuntu 14.04, installed with: `apt-get install clang-3.5 llvm-3.5-dev` (not from the LLVM APT repository)

Symlinks are set up in /usr/local/bin:

```
ls -l /usr/local/bin
lrwxrwxrwx 1 root root 18 Feb 21 13:11 clang -> /usr/bin/clang-3.5
lrwxrwxrwx 1 root root 20 Feb 21 13:11 clang++ -> /usr/bin/clang++-3.5
```

I performed the build with `OCDEBUG=1 ./build.sh &>build.log` and can provide you with the `build.log` if you're interested.

In the final build phase, while performing tests, I receive this message multiple times:

```
cannot find clang intrinsic headers, please report this issue to the OSXCross project
```

One of the full compiler command lines:

```
clang++ -target x86_64-apple-darwin13 -mlinker-version=241.9 -isysroot /root/osxcross/target/bin/../SDK/MacOSX10.9.sdk -stdlib=libstdc++ -cxx-isystem /root/osxcross/target/bin/../SDK/MacOSX10.9.sdk/usr/include/c++/4.2.1 -cxx-isystem /root/osxcross/target/bin/../SDK/MacOSX10.9.sdk/usr/include/c++/4.2.1/x86_64-apple-darwin13 -mmacosx-version-min=10.5.0 -arch x86_64 -o test /root/osxcross/oclang/test.cpp -O2 -Wall
```

If I'm correct, it is testing the existence of `xmmintrin.h` on the include path. This file exists on my system:

```
find / -type f -name "xmmintrin.h"
/usr/lib/llvm-3.5/lib/clang/3.5.0/include/xmmintrin.h
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/xmmintrin.h
```

Why is the wrapper not able to find the file? Should I explicitly add the directory to my include path somewhere?

**Comment by tpoechtrager** [comment]
I think the symlinks in `/usr/local` is confusing the wrapper, try moving the symlinks to `/usr/bin` instead.
Also please note that `clang 3.5` in `Ubuntu 14.04` is not the final version.

Maybe you want to try the official clang binaries for 14.04: http://llvm.org/releases/3.5.1/clang+llvm-3.5.1-x86_64-linux-gnu.tar.xz instead.

**Comment by joostwim** [comment]
Moving the symlinks to `/usr/bin` did indeed solve the problem. Thanks!

I tried the clang 3.5.1 binaries for Ubuntu 14.04 earlier, but ran into some trouble because they depend on `libstdc++.so.6.0.20` and the version on my system (all packages up to date) is `libstdc++.so.6.0.19`. However, this is not related to OSXCross.

**Comment by tpoechtrager** [comment]
No problem.

However, you should really consider upgrading to the release version, because that pre-release is more than 10.000 commits behind.

You can use my clang build script `./build_clang.sh` to build clang 3.5 (without weird `libstdc++.so.6.0.20` problems).

Just run: `INSTALLPREFIX=<prefix> ./build_clang.sh`.

**Comment by joostwim** [comment]
Thanks for the suggestion!

After my initial problems, I found http://llvm.org/apt/ was providing packages for a newer version than the Ubuntu package repository itself. I now have:

`clang version 3.5.1-svn225255-1~exp1 (branches/release_35) (based on LLVM 3.5.1)`

Would you still advise using `./build_clang.sh` to create a custom clang 3.5.1 build? Should I notice any differences?

**Comment by tpoechtrager** [comment]
No, not worth it - `3.5.1-svn225255` should be fine.

**Comment by efa** [comment]
the same error happen to me today.
osxcross worked perfectly in the past with Debian 10, it is installed in /opt/osxcross
Now I upgraded to Debian 11, I do not know if was the update that broke the /opt installation, the file are there 3.5 GB not touched.
See the error below:

```
efa@08i7-2500:~/c$ osxcross-var
ODVER ___________:18
OHOST ___________:x86_64-apple-darwin18
OCROSS __________:x86_64-apple-darwin18-
OSXROOT _________:/opt/osxcross
OSX _____________:/opt/osxcross/target/bin
OSXDEPS _________:/opt/osxcross/target/macports
PATH:/opt/osxcross/target/bin:.:/home/efa/script:/home/efa/bin:/home/efa/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/usr/local/sbin:/usr/sbin:/sbin
OSXCROSS_PKG_CONFIG_USE_NATIVE_VARIABLES:1
PKG_CONFIG_LIBDIR:/opt/osxcross/target/macports/pkgs/opt/local/lib/pkgconfig:/opt/osxcross/target/macports/pkgs/opt/local/share/pkgconfig
PKG_CONFIG_PATH _:/opt/osxcross/target/macports/pkgs/opt/local/lib/pkgconfig:/opt/osxcross/target/macports/pkgs/opt/local/share/pkgconfig
OSXCROSS_TARGET _:darwin18
SDK_VERSION _____:10.14

efa@08i7-2500:~/c$ x86_64-apple-darwin18-clang -D GNU_SOURCE=1 -O3 -std=gnu99 -Wall hello.c -lm -o hello.macOS64
osxcross: warning: cannot find clang intrinsic headers; please report this issue to the OSXCross project
osxcross: error: invoking compiler failed
osxcross: debug: --> x86_64-apple-darwin18-clang -D GNU_SOURCE=1 -O3 -std=gnu99 -Wall hello.c -lm -o hello.macOS64 
osxcross: debug: <-- clang -target x86_64-apple-darwin18 -mlinker-version=530 -isysroot /opt/osxcross/target/bin/../SDK/MacOSX10.14.sdk -cxx-isystem /opt/osxcross/target/bin/../SDK/MacOSX10.14.sdk/usr/include/c++/v1 -mmacosx-version-min=10.9.0 -arch x86_64 -D GNU_SOURCE=1 -O3 -std=gnu99 -Wall hello.c -lm -o hello.macOS64 

efa@08i7-2500:~/c$ distro
---
Distro: LMDE 5 (elsie) elsie
based on Debian 11 Bullseye 14 August 2021
---

efa@08i7-2500:~/c$ ls -l /usr/local/bin/clan*
ls: cannot access '/usr/local/bin/clan*': No such file or directory

```
I have no link in /usr/local/bin/clan*
