### ISSUE TITLE
Clang versions > 11.0.0 cannot be built using build_clang.sh

### ISSUE THREAD

**Issue by cschol** [tpoechtrager/osxcross#303]
For Clang versions > 11.0.0, the format of the website to acquire the tarball download links has changed. This means the parser implemented in `build_clang.sh` will fail to download the specific Clang version > 11.0.0.

See [https://releases.llvm.org/download.html](https://releases.llvm.org/download.html).

For versions > 11.0.0 the links are now obtained from a release page on Github (for example: [https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.1](https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.1)).

Since **all** versions seem to be available on Github now, the parser in `build_clang.sh` could be rewritten to always use the Github links, even in cases < 11.0.0.

~I can provide a PR if desired.~ PR submitted.

**Comment by tpoechtrager** [comment]
Thanks for the PR. :-)
