### ISSUE TITLE
After strip debug symbols, arm64 binaries stopped working on M1 mac

### ISSUE THREAD

**Issue by vanc** [tpoechtrager/osxcross#305]
For a simple helloworld program, use arm64-apple-darwin20.4-cc to generate a executable, named hello.

Copy the file to hello.stripped, then strip all debug symbols with:
```
cp hello hello.stripped
arm64-apple-darwin20.4-strip -S -x -u hello.stripped
```

Transfer both files to M1 mac, and run them.

```
$ ./hello
Hello World
$ ./hello.stripped
Killed: 9
```

If strip symbols on the M1 mac itself, everything works fine. I can also resign the stripped binary on mac (even Intel mac), the binary will also work well.

```
$ codesign -s - hello.stripped
```

The strip command from osxcross complained about invalidating codesign signatures. That should be the reason. But on macOS (including Intel and M1 models), the strip tool will regenerate the ad-hoc signature.

I tried [zsign](https://github.com/zhlynn/zsign), but it didn't solve the issue.

Any way in osxcross to regenerate the ad-hoc codesign signatures?

**Comment by vanc** [comment]
This issue might share the same root cause as #279.

**Comment by tpoechtrager** [comment]
You could try to sign the binary again with https://github.com/thefloweringash/sigtool

**Comment by HinTak** [comment]
I wrote some python code which can analyze and remove the signatures (and allow binaries to be resigned) at https://github.com/HinTak/mono-modification , they run on linux to analyze them. You might be able to adapt them to add an ad-hoc signature.

The context is that signatures are appended to binaries. But mono also has a way of making self-contained executable, such that the mono runtime looks at itself, and find extra things at the end of itself. So I wrote some scripts to make the two systems co-exist.

If you can attach the stripped and broken binary and the re-signed and fixed binary here for me to have a look?

**Comment by vanc** [comment]
> You could try to sign the binary again with https://github.com/thefloweringash/sigtool

Thank you @tpoechtrager. That's exactly what I needed. Tried on a few binaries, and all of them could run properly on M1 mac after re-signed with sigtool.

Very appreciated for the pointer!

**Comment by vanc** [comment]
Hope sigtool or an equivalent could be merged to osxcross. Thanks again.

**Comment by tpoechtrager** [comment]
I will once I find the time for it.
