### ISSUE TITLE
Multiple Sdks

### ISSUE THREAD

**Issue by lmtr0** [tpoechtrager/osxcross#312]
Hi there, good day,

is possible to compile for multiple sdks?
like I have 2 sdks in the tarballs directory, if I build.sh twice and will I have both installed?

**Comment by Flow86** [comment]
you can simply set an environment variable for this afterwards:

e.g
```sh
# OSXCROSS_SDKROOT=/path/to/SDKs/MacOSX13.1.sdk /opt/osxcross/bin/osxcross-conf
...
export OSXCROSS_SDK=/path/to/SDKs/MacOSX13.1.sdk
export OSXCROSS_SDK_DIR=/path/to/SDKs/MacOSX13.1.sdk/..
export OSXCROSS_SDK_VERSION=13.1
...
```

**Comment by lmtr0** [comment]
got it, thx
