### ISSUE TITLE
cmake doesn't work, produces "unknown argument" errors

### ISSUE THREAD

**Issue by realnc** [tpoechtrager/osxcross#315]
After successfully installing osxcross, I can't get anything that uses cmake to build. Configuration succeeds, but building fails with either:

```
CMake Error: Unknown argument -j
```

Or:

```
CMake Error: Unknown argument --build
```

Example cmake invocation:

```
x86_64-apple-darwin21.1-cmake --build . --config Release --target install -j `nproc`
```

**Comment by tpoechtrager** [comment]
That's not how `cmake` works. 🙂

    x86_64-apple-darwin21.1-cmake . -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX:PATH=target
    make -j ...

**Comment by realnc** [comment]
> That's not how `cmake` works. slightly_smiling_face
> 
> ```
> x86_64-apple-darwin21.1-cmake . -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX:PATH=target
> make -j ...
> ```

That only works for makefiles. When using the cmake Ninja generator, or the Visual Studio one, or the XCode project one, then this doesn't work.

This is why cmake has a `--build` option. However, I found the issue. Since cmake 3.20, `-D` prevents build arguments from working. Previously, they would be silently ignored.

I'll clone the repo and push a fix shortly.

**Comment by tpoechtrager** [comment]
You are right. Thanks for the PR. 👍

**Comment by realnc** [comment]
Thanks! :)
