### ISSUE TITLE
Defaulting to installed XCode SDK 

### ISSUE THREAD

**Issue by pgatt** [tpoechtrager/osxcross#325]
I'm running `./tools/gen_sdk_package.sh Xcode_12.4.xip` but it's defaulting (or at least I think it is) to the XCode I have installed (13.2.1) and thus trying to package MacOSX12.1 instead of using the .xip provided.

Any advice?

**Comment by tpoechtrager** [comment]
Mount the xip. Then use `XCODEDIR=<path> ./tools/gen_sdk_package.sh`

**Comment by pgatt** [comment]
Thanks!
