### ISSUE TITLE
New SDK packing method on Linux (was: Outdated information?)

### ISSUE THREAD

**Issue by BioMike** [tpoechtrager/osxcross#33]
I just started packing the SDK on Linux, but I tried it with XCode 5.1.1 (which was reported not to work). While the mount script didn't work for me, I manually executed the commands that it performs. I was able to mount the generated image (no modprobe on loop for creating a loopback device in the script) and execute the gen_sdk_package.sh script. This generated two files: MacOSX10.8.sdk.tar.xz and .MacOSX10.9.sdk.tar.xz

According to the documentation I shouldn't have gotten this far with this XCode version. Does this mean the documentation is outdated?

**Comment by BioMike** [comment]
I was wrong. I ran into issue 29.

**Comment by BioMike** [comment]
I've looked into ways of extracting the SDK from newer XCode dmg archives on Linux and was able to to so with Xcode 5.1.1 (newer versions might also work) by using HFSExplorer version 0.23 (which build and runs on Linux): http://sourceforge.net/projects/catacombae/files/HFSExplorer/

I've manually extracted the data into a new directory (skipped all man page errors), and packed the directory into a tar.xz file. I used this in the build process. So far it seems it worked.

**Comment by tpoechtrager** [comment]
`HFSExplorer` seems to be a great tool, but to be honest, I am not really happy about the `java` / `ant` dependency.

However, thanks for posting this, I will update the packaging scripts soon.

**Comment by tpoechtrager** [comment]
`HFSExplorer` is totally broken, there are tons of uncaught exceptions and the command line utility doesn't even care about symlinks.

I am not sure if I really want to use such a tool.

**Comment by tpoechtrager** [comment]
I have added your method to the README (but plainly marked it as unsupported :smile:).

**Comment by BioMike** [comment]
Thank you!

**Comment by BioMike** [comment]
I found a new and more elegant "unsupported" method. This one uses https://github.com/LubosD/darling-dmg, which allows compressed DMG files to be mounted through FUSE. This one doesn't add dependencies for java (but it does for FUSE though) and doesn't give nagging pop-ups about inaccessible files (there is however one bug report about inaccessable files/directories). I'm going to give this method a try.

**Comment by tpoechtrager** [comment]
`darling-dmg` seems to be the best method by far.

I will add a script for it once I am sure it really works the way it should.

I have marked the `hfsexplorer` method "unsupported" because the chance to end up with a working SDK isn't very high...

**Comment by geoff-codes** [comment]
```sh
7z x *.dmg "*/*/*/*/*/MacOSX/*/*/*.sdk"; mv $(find . -name \*.sdk -type d) .; rm -rf Xcode
# ... or similar.
```
Using [p7zip 9.38.1](http://sourceforge.net/projects/p7zip/files/p7zip/9.38.1).
YMMV with 9.20.1 - it's a little clunkier, and chokes on larger DMGs for me.

**Comment by tpoechtrager** [comment]
p7zip 9.38.1 seems to have problems with xcode 6.3.2:

    testing o32-clang ... ld: file too small (length=17) file '[...]/SDK/MacOSX10.10.sdk/usr/lib/libSystem.dylib' for architecture i386
    clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zarvox** [comment]
There's also libdmg-hfsplus which requires neither Java nor FUSE nor privilege escalation.  [My fork of libdmg-hfsplus](https://github.com/zarvox/libdmg-hfsplus) supports bzip2-compressed DMGs, extracting symbolic links, and fixes some memory leaks, which most of the others in the libdmg-hfsplus repo graph don't.

I'll see if I can get a working SDK and write up the appropriate instructions.

**Comment by zarvox** [comment]
Hmm, I appear to have spoken too soon - looks like libdmg-hfsplus doesn't support HFS+ compression yet.  I'll poke at making that work.

**Comment by BioMike** [comment]
I tried the p7zip option as well, didn't work for me as well.

@zarvox, might be good to collaborate with the darling team? (seems to be a one man show for now) to have a uniform lib and a FUSE FS access and the extraction tool that both use it. The FUSE FS access has currently still some problems (about accessing some files/dirs) that might be worthwile to investigate into.

**Comment by geoff-codes** [comment]
@BioMike @tpoechtrager
Sorry, (I never realized this before) but it looks like p7zip doesn't create proper symlinks, it creates a text file with the target of the symlink. But it _does_ handle HFS+ compression!

Try something like this script on for size:
```sh
#!/bin/sh
here=$PWD
7z x "$1" "*/*/*/*/*/Mac*/*/*/*.sdk"
mv $(find . -name \*.sdk) .
rm -rf Xcode */usr/share/man
find . -empty -delete

for symlink in $(find . -type f -size -1k); do
  if [ $(wc -l < "$symlink") = 0 ]; then
    target=$(cat "$symlink")

    link=$(basename "$symlink")
    cd "$(dirname "$symlink")"
    [ -e "$target" ] && rm "$(basename "$link")" && ln -s "$target" "$link"
  fi
  cd "$here"
done
```

**Comment by tpoechtrager** [comment]
@geoff-codes
I have tried a smiliar way yesterday and ran into lots of problems...

    function fix_symlink() {
      dst=$(cat $1)
      [ $(echo "$dst" | wc -l | tr -d ' ') -ne 1 ] && return
      ([[ "$dst" == *\ * ]] || [[ "$dst" == \#* ]]) && return
      dst=$(cat $1)
      echo "fixing symlink: $1 -> $dst"
      rm $1 && ln -s $dst $1
    }

    export -f fix_symlink

    find $TMP -type f -size -4096c -exec \
      /usr/bin/env bash -c 'fix_symlink "$0"' {} \;

I have now [modified p7zip](https://github.com/tpoechtrager/p7zip) instead, not very elegant, but it seems to work...
Luckily p7zip [doesn't depend on any libraries](https://www.archlinux.org/packages/extra/x86_64/p7zip/), so a C/C++ compiler is all you need (more or less).

--

@zarvox
I have already tried libdmg-hfsplus a while ago and it didn't work out so well.
However, [hdutil](https://github.com/zarvox/libdmg-hfsplus/tree/master/hdutil) indeed supports hfs+, but I am getting an Input/Output error rather quickly.

**Comment by zarvox** [comment]
@tpoechtrager I confirm success using your patched p7zip to produce working SDK tarballs, so I think that's probably the lowest-friction path forward for users.

```bash
git clone https://github.com/tpoechtrager/p7zip
cd p7zip && make 7z && cd ..
./p7zip/bin/7z x /path/to/Xcode_6.3.2.dmg
XCODEDIR=./Xcode ./tools/gen_sdk_package.sh
```

**Comment by maci0** [comment]
+1
Great to see this progressing!

**Comment by fdelapena** [comment]
Thank you for the patched p7zip, our building bot VPS uses OpenVZ and the FUSE module for the darling-dmg method is not available because the host exposed kernel does not have it enabled and can't be installed from the guest. The new method helped a lot :+1:.

**Comment by Godin** [comment]
@tpoechtrager Thank you for the patched p7zip - works like a charm! Any chance that it will be accepted into upstream project eventually?

**Comment by tpoechtrager** [comment]
@Godin: You are welcome. I am not sure whether they would accept such a patch, my implementation is just a quick & dirty hack for OSXCross :smile:. Try to create a feature request ticket @ http://sourceforge.net/p/p7zip/feature-requests/?source=navbar and maybe point them to my p7zip repository - so they don't have to start from zero.
