### ISSUE TITLE
ccache + osxcross: warning: cannot find clang intrinsic headers

### ISSUE THREAD

**Issue by noscript** [tpoechtrager/osxcross#34]
I have enabled ccache by creating symlinks for `*-apple-*-clang` and `*-apple-*-clang++`. This is what I get when I use ccache:

```
osxcross: warning: cannot find clang intrinsic headers, please report this issue to the OSXCross project
osxcross: warning: cannot find clang intrinsic headers, please report this issue to the OSXCross project
clang: warning: argument unused during compilation: '-cxx-isystem /home/builder/osxcross.git/target/bin/../SDK/MacOSX10.6.sdk/usr/include/c++/4.2.1'
clang: warning: argument unused during compilation: '-cxx-isystem /home/builder/osxcross.git/target/bin/../SDK/MacOSX10.6.sdk/usr/include/c++/4.2.1/i386-apple-darwin10'
clang: warning: argument unused during compilation: '-I /home/builder/osxcross.git/target/bin/../SDK/MacOSX10.6.sdk/usr/X11/include'
```

Clangs is known to throw such wanning when used with ccache, they can be suppressed with `-Qunused-arguments`. But I still get `osxcross: warning: cannot find clang intrinsic headers`, which bothers me more.

**Comment by tpoechtrager** [comment]
Does [this](https://gist.github.com/tpoechtrager/b4a3d3f286bad519fb09) patch fix the problem for you?

    git apply proposed-fix-for-34.patch
    wrapper/build.sh

**Comment by noscript** [comment]
Thanks for the patch, no warnings now. I will still test if ccache works properly.

**Comment by noscript** [comment]
Works great, please apply the patch to master.
