### ISSUE TITLE
Cannot Build compiler-rt With Clang 14

### ISSUE THREAD

**Issue by nephatrine** [tpoechtrager/osxcross#347]
I was getting a lot of errors trying to run `build_compiler_rt.sh` using clang-14 from Ubuntu jammy.

Just updating `build_compiler_rt.sh` to use `BRANCH=release/14.x` instead of `BRANCH=main` seems to have corrected everything though. I guess maybe it wasn't split off into its own branch yet when you did the initial 14.x support?

[build_log.txt](https://github.com/tpoechtrager/osxcross/files/8757658/build_log.txt)

**Comment by akien-mga** [comment]
Duplicate of #340, fixed by #341.

**Comment by akien-mga** [comment]
Also worth noting, I actually got invalid macOS and iOS binaries when compiling osxcross against Clang 14 (with the above patch). I haven't investigated in depth but it seems to me like as of Xcode 13.3.1, the SDKs aren't ready for Clang 14 yet.

**Comment by nephatrine** [comment]
I don't have a macOS device myself to test the binaries on, but I'll have to have someone take a look and see if I run into the same thing with them not being valid binaries.

Looks like the actual issue reported though is fixed at least.

**Comment by nephatrine** [comment]
As a follow-up, the binaries I am generating with Clang 14 seems to work fine on actual macOS hardware.

**Comment by akien-mga** [comment]
Which Xcode version fid you build against?
