### ISSUE TITLE
cflag -fobjc-arc does not work.

### ISSUE THREAD

**Issue by thomasf** [tpoechtrager/osxcross#35]
I'm not sure if/how it's supposed to work:..

clang says:
```
clang: error: unknown argument: '-fobjc-arc'
 ```

**Comment by thomasf** [comment]
I've also tried to set CLANG_ENABLE_OBJC_ARC=YES but it does not seem to do anything. Don't know if it should.

**Comment by thomasf** [comment]
Sorry to disturb, my problem was that that deployment target was not correctly specfied..

I did get this error which lead me in the right direction:
```
clang: error: -fobjc-arc is not supported on versions of OS X prior to 10.6
```

For the time being I just added this to the Dockerfile:

```
env MACOSX_DEPLOYMENT_TARGET 10.9
```

Thanks for a great project btw :+1:

**Comment by tpoechtrager** [comment]
> Thanks for a great project btw :+1:

Thanks / You are welcome!
