### ISSUE TITLE
No 32 bit binaries being built

### ISSUE THREAD

**Issue by lharmantwdb** [tpoechtrager/osxcross#368]
I used the ./tools/gen_sdk_package_pbzx.sh <xcode>.xip file when packing the sdk and followed the installation instructions. However The target/bin directory only includes 64 bit compilers.

Is there any tweak I could do to get the o32-clang compiler built? Should I fall back to a older sdk?

**Comment by philippe44** [comment]
I think the log explicitly mentions that after SDK 11, 32-bits compilers will not be built

**Comment by lharmantwdb** [comment]
Thanks, philippe44
