### ISSUE TITLE
Your manual isn't clear...

### ISSUE THREAD

**Issue by DomiKamu** [tpoechtrager/osxcross#373]
...for example : Packaging the SDK on macOS (Xcode)
1/ Download Xcode
2/ Mount Xcode.dmg ---> but the downloaded file is **.xip**, not **.dmg** !

What's difference between Packaging and Packing?

Now: **Packing the SDK on Linux - Method 1 (Xcode > 8.0):**
These packages can't be found for installation: **libssl-devel**, **lzma-devel** and **libxml2-devel**
Explanation? -dev instead of -devel?

**Comment by delasy** [comment]
To workaround **Xcode.xip** I used:

1. First double-click **Xcode.xip**, it will get extracted to: `~/Downloads`
2. Run in terminal:

```shell
XCODEDIR=~/Downloads tools/gen_sdk_package.sh
```

**Comment by DomiKamu** [comment]
> To workaround **Xcode.xip** I used:
> 
>     1. First double-click **Xcode.xip**, it will get extracted to: `~/Downloads`
> 
>     2. Run in terminal:
> 
> 
> ```shell
> XCODEDIR=~/Downloads tools/gen_sdk_package.sh
> ```

Hi, it was solved, I'm using plugin-toolchain since weeks, I've forgotten this issue, sorry, I ask for close/solved.
