### ISSUE TITLE
Fail on ./build.sh "can't touch 'have_cctools_repos/osxcross/tarballs/cctools-862...'"

### ISSUE THREAD

**Issue by Wohlstand** [tpoechtrager/osxcross#39]
I have many attempts to build cross compiler and I have been failed.
On Linux Mint 17.1
![-terminal-5](https://cloud.githubusercontent.com/assets/6751442/8512104/799dba48-232c-11e5-9e08-0b8b9ab16ae2.png)
On Linux Mint 17.2 (after upgrade)
![2015-07-05 18 08 53](https://cloud.githubusercontent.com/assets/6751442/8512208/c9c6fca6-2330-11e5-8769-f6e0de1c2a02.png)

1) I built clang 3.6 via ./build_clang.sh script under root
2) I made chown -R vitaly:vitaly osxcross
3) Xcode 6.3.2, target OSX versions 10.10 and minimal 10.9
4) I working under Linux Mint 17.1 and now under 17.2

I think, this is a bug in the script code or I do something wrong :stuck_out_tongue_winking_eye:
I wanna run this wonderful project at me because too hard for me to get Mac OS machine yet

**Comment by tpoechtrager** [comment]
Need the whole build log.

Run: `SDK_VERSION=10.10 OCDEBUG=1 UNATTENDED=1 ./build.sh &>build.log`

Then upload build.log to https://gist.github.com/.

**Comment by Wohlstand** [comment]
Made: https://gist.github.com/Wohlstand/abaf4404428082b5a866

**Comment by tpoechtrager** [comment]
Hmm, no idea where

` CCTOOLS_REVHASH=repos/osxcross/tarballs/cctools-862-ld64-241`

comes from.

What's in tarballs/? Does does [this](https://gist.github.com/tpoechtrager/37ee39e787680eff1c39) help?

**Comment by Wohlstand** [comment]
1) taballs/
![2015-07-05 21 49 39](https://cloud.githubusercontent.com/assets/6751442/8512958/a2fb4706-2350-11e5-9961-fd05ffe4ba17.png)

2) patch < meow.diff gives me:
```text
vitaly@WHL-PC-001L ~/_git_repos/osxcross $ patch < meow.diff
patching file build.sh
Hunk #1 succeeded at 154 (offset -9 lines).
Hunk #2 FAILED at 231.
1 out of 2 hunks FAILED -- saving rejects to file build.sh.rej
```
and still same 
"touch: cannot touch 'have_cctools_repos/osxcross/tarballs/cctools-862-ld64-241_darwin14': No such file or directory"

**Comment by tpoechtrager** [comment]
Should be fixed.

**Comment by Wohlstand** [comment]
Yay! Than has been fixed! :smile: 
Thank you!
![2015-07-05 22 10 46](https://cloud.githubusercontent.com/assets/6751442/8513002/8e6763cc-2352-11e5-94a5-94da723c69ff.png)
