### ISSUE TITLE
osxcross-macports infinite loops when installing install curl-ca-bundle

### ISSUE THREAD

**Issue by nephatrine** [tpoechtrager/osxcross#399]
When I try to install `curl` (or anything that ends up installing `curl-ca-bundle`), this happens:

```
 candidates for curl-ca-bundle:
  curl-ca-bundle-7.88.1_0.any_any.noarch.tbz2
  curl-ca-bundle-7.88.1_0.any_any.noarch.tbz2
  curl-ca-bundle-8.0.1_0.any_any.noarch.tbz2
  curl-ca-bundle-8.0.1_0.any_any.noarch.tbz2
  curl-ca-bundle-8.1.0_0.any_any.noarch.tbz2
  curl-ca-bundle-8.1.0_0.any_any.noarch.tbz2
  curl-ca-bundle-8.1.2_0.any_any.noarch.tbz2
  curl-ca-bundle-8.1.2_0.any_any.noarch.tbz2
  curl-ca-bundle-8.2.0_0.any_any.noarch.tbz2
  curl-ca-bundle-8.2.0_0.any_any.noarch.tbz2
  curl-ca-bundle-8.2.0_1.any_any.noarch.tbz2
  curl-ca-bundle-8.2.0_1.any_any.noarch.tbz2
  curl-ca-bundle-8.2.1_0.any_any.noarch.tbz2
  curl-ca-bundle-8.2.1_0.any_any.noarch.tbz2
  curl-ca-bundle-8.3.0_0.any_any.noarch.tbz2
  curl-ca-bundle-8.3.0_0.any_any.noarch.tbz2
  curl-ca-bundle-8.4.0_0.any_any.noarch.tbz2
  curl-ca-bundle-8.4.0_0.any_any.noarch.tbz2
 selected:
  no suitable version found for darwin_22
 ```
 
 It then tries `curl-ca` and `curl` and eventually will try to grab `curl-ca-bundle` again and start all over again.
 
 ```
searching package curl-ca-bundle ...
no suitable version found for darwin_22
trying curl-ca instead ...
searching package curl-ca ...
no package found
trying curl instead ...
searching package curl ...
getting curl-8.4.0_0+http2+ssl.darwin_22.x86_64.tbz2 ...
verifying file integrity of curl-8.4.0_0+http2+ssl.darwin_22.x86_64.tbz2 ...
installing curl ...
searching package libpsl-0.21.2 ...
no package found
trying libpsl instead ...
searching package curl-ca-bundle ...
no suitable version found for darwin_22
trying curl-ca instead ...
searching package curl-ca ...
no package found
```

I've submitted PR https://github.com/tpoechtrager/osxcross/pull/398 which should correct this specific issue and allow any_any packages to be selected, but it would be nice if the script could detect such infinite/circular loops and bail out in case any similar corner cases are found in the future.

**Comment by efa** [comment]
I got similar results installing:
```
$ omp install gtk2
$ omp install gtk3
$ omp install qt4-mac boost boost-build libzip
```
and also with:
`$ omp upgrade`
remain stacked on an xorg package

**Comment by lilggamegenius** [comment]
Did macports change something again? The changes in your PR doesn't seem to work even though i'm trying to install the same package.

**Comment by efa** [comment]
seems work with: $ omp fake-install curl-ca-bundle

**Comment by lilggamegenius** [comment]
fake-install didn't seem to do anything for me, it just prints "done" without allowing the normal install to work.

**Comment by efa** [comment]
then restart the prev omp install command that got stuck installing curl-ca-bundle. In my case, as it find already fake installed, proceed and finish installation. This is not the ideal situation, but work
