### ISSUE TITLE
cross compiler stopped working

### ISSUE THREAD

**Issue by niksah** [tpoechtrager/osxcross#40]
I built the cross compiler with FORTRAN support in late 2014 and it worked fine for about half a year.  It stopped working a couple of months ago.  What may have caused this?  The errors that I am currently getting when trying to compile are of the form:

f951: internal compiler error: Illegal instruction
0x9467af crash_signal
        ../../gcc/toplev.c:337
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.

Interestingly, I don't get this error for all files that I try to compile; in many cases, compilation goes through just fine.

**Comment by tpoechtrager** [comment]
Hard to say what's wrong.

Maybe the following links are of some help:

http://archive.linuxfromscratch.org/mail-archives/lfs-dev/2015-February/069923.html
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64364
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61558

Have you tried a recent version of gcc?

**Comment by niksah** [comment]
I've upgraded gcc to 5.2.0 but the problem persists.

**Comment by tpoechtrager** [comment]
What compiler did you use to compile gcc? clang?

I remember clang 3.5 compiled gcc to crash randomly during libstdc++ compilation.

Ensure

    $ x86_64-apple-darwin14-gcc test.c -v
    
prints something like

    compiled by GNU C version

**Comment by niksah** [comment]
x86_64-apple-darwin14-gcc test.c -v

gives me

compiled by GNU C version 4.8.2 20140120 (Red Hat 4.8.2-16), GMP version 
5.1.1, MPFR version 3.1.1, MPC version 1.0.1

I have determined that the problem is not with the cross compiler but 
with my gcc installation.  Even a native built with gcc/gfortran leads 
to the same crash.

**Comment by tpoechtrager** [comment]
Closing this as this is not an OSXCross issue.
