### ISSUE TITLE
make it ccache friendly

### ISSUE THREAD

**Issue by pisto** [tpoechtrager/osxcross#43]
It seems customary in linux distros to install ccache symlinks in /usr/lib or /usr/lib64. osxcross seems to forcibly ignore those paths.

**Comment by tpoechtrager** [comment]
Yes, the wrapper is ignoring ccache symlinks while searching for the clang executable ([to prevent breakage](https://github.com/tpoechtrager/osxcross/issues/34)).

The proper way is to create `x86_64-apple-darwin*-[clang|gcc]` ccache symlinks,

e.g.:

    cd /usr/lib64/ccache

    ln -sf $(which ccache) x86_64-apple-darwin14-clang
    ln -sf $(which ccache) x86_64-apple-darwin14-clang++
    ln -sf $(which ccache) o32-clang
    ln -sf $(which ccache) o32-clang++
    ln -sf $(which ccache) o64-clang
    ln -sf $(which ccache) o64-clang++
    ln -sf $(which ccache) x86_64-apple-darwin14-gcc
    ln -sf $(which ccache) x86_64-apple-darwin14-g++
    [... and so on]

**Comment by pisto** [comment]
I guess that can work.

**Comment by pisto** [comment]
No it doesn't work, I get the same issue as in #34 if I append the osxcross path and create the appropriate ccache symlinks.

**Comment by tpoechtrager** [comment]
It *does* work, that warnings are not an OSXCross issue, you get them for other targets too.
