### ISSUE TITLE
libxar.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zijiren233** [tpoechtrager/osxcross#430]
When the target directory is moved to another place after the compilation is successful, an error will occur: `ld: error while loading shared libraries: libxar.so.1: cannot open shared object file: No such file or directory`

How to find libxar from relative directory

**Comment by mauricelos** [comment]
You can do something like this:

`patchelf --set-runpath '$ORIGIN/../lib' <Name of Linker Binary>`

Since the linker is in the bin folder you need to move up one folder and them enter the lib folder in this relative path.

**Comment by zijiren233** [comment]
thanks
