### ISSUE TITLE
Invalid SDK Version

### ISSUE THREAD

**Issue by pacmac** [tpoechtrager/osxcross#48]
I have edited this as I started again and the second time around hit a different error:

./build.sh
found SDK version 10.11 at tarballs/MacOSX10.11.sdk.tar.bz2
verified at tarballs/MacOSX10.11.sdk.tar.bz2
Invalid SDK Version

Is 10.11 not supported ?

edit
--

OK, I added  this to build:
    10.11*) TARGET=darwin15; X86_64H_SUPPORTED=1; ;;

But then it fails with:

	extracting MacOSX10.11.sdk.tar.bz2 ...
	compiling wrapper ...
	
	testing o32-clang ... /osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1:25: warning: unknown attribute 'extern_c' [-Wignored-attributes]
	module Darwin [system] [extern_c] {
	                        ^
	/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1561:21: warning: unknown attribute 'extern_c' [-Wignored-attributes]
	module os [system] [extern_c] {
	                    ^
	/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1577:26: warning: unknown attribute 'extern_c' [-Wignored-attributes]
	module libkern [system] [extern_c] {
	                         ^
	/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1602:23: warning: unknown attribute 'extern_c' [-Wignored-attributes]
	module ldap [system] [extern_c] {
	                      ^
	/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1635:23: warning: unknown attribute 'extern_c' [-Wignored-attributes]
	module krb5 [system] [extern_c] {
	                      ^
	/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1662:22: warning: unknown attribute 'extern_c' [-Wignored-attributes]
	module XPC [system] [extern_c] {
	                     ^
	6 warnings generated.
	ld: library not found for -lSystem
	clang: error: linker command failed with exit code 1 (use -v to see invocation)
	
	exiting with abnormal exit code (1)

**Comment by tpoechtrager** [comment]
> Is 10.11 not supported ?

Xcode 7.x isn't supported yet (like stated in the README), Xcode 7.x requires a newer not yet open sourced linker.

You can of course compile for 10.11 by using the Xcode 6.x SDKs.

    testing o32-clang ... /osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1:25: warning: unknown attribute 'extern_c' [-Wignored-attributes]
    module Darwin [system] [extern_c] {
                            ^
    /osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1561:21: warning: unknown attribute 'extern_c' [-Wignored-attributes]
    module os [system] [extern_c] {
                        ^
    /osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1577:26: warning: unknown attribute 'extern_c' [-Wignored-attributes]
    module libkern [system] [extern_c] {
                            ^

Use clang >= 3.5 to get rid of the compiler warnings.
