### ISSUE TITLE
inexperienced user help

### ISSUE THREAD

**Issue by pacmac** [tpoechtrager/osxcross#49]
My apologies for my lack of knowledge, I have tried to solve this myself, but are not getting anywhere.

I am trying to compile this: http://www.irtrans.de/download/Server/Linux/irserver-src.tar.gz

I have followed all the instructions (with MacOSX10.10.sdk.tar.bz2) and are now attempting to compile.

So I enter the irserver-src directory and enter the following (as per the make instructions)

    make CC=o64-clang Cdarwin14=o64-clang++

However, this just throws numerours warings and errors:

	lowlevel.c:762:35: note: please include the header <string.h> or explicitly provide a declaration for 'strcpy'
	lowlevel.c:762:54: warning: passing 'int8_t [80]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
	if (res == ERR_REMOTENOTFOUND) strcpy (err_remote,acc->remotes[i]);
	                                                                          ^~~~~~~~~~~~~~~
	lowlevel.c:763:56: warning: passing 'int8_t [20]' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
	if (res == ERR_COMMANDNOTFOUND) strcpy (err_command,acc->commands[i]);
	                                                                            ^~~~~~~~~~~~~~~~
	lowlevel.c:836:112: error: use of undeclared identifier 'MSG_NOSIGNAL'
	if (IRDevices[bus].io.socket) res = recvfrom(IRDevices[bus].io.socket,(byte *)&ai,sizeof (GET_ANALOG_INPUTS),MSG_NOSIGNAL,(struct sockaddr *)&send_adr,&i);
	                                                                                                                             ^
	lowlevel.c:837:77: error: use of undeclared identifier 'MSG_NOSIGNAL'
	else  res = recvfrom(irtlan_socket,(byte *)&ai,sizeof (GET_ANALOG_INPUTS),MSG_NOSIGNAL,(struct sockaddr *)&send_adr,&i);
    162 warnings and 19 errors generated.
    make: *** [x86/lowlevel.o] Error 1

What am I doing wrong ?

**Comment by tpoechtrager** [comment]
"irserver" may simply not be compatible with Mac OS X.

Please ask programming related questions on StackOverflow, you will get better answers there.
