### ISSUE TITLE
`-stdlib=libc++` requires "targeted OS X version must be <= 10.6.0 (SDK)"

### ISSUE THREAD

**Issue by tamird** [tpoechtrager/osxcross#52]
This doesn't make sense:
```c++
root@70edf05eb7c2:/# cat foo.cc
int main(int argc, char const *argv[])
{
	/* code */
	return 0;
}
```
```bash
root@70edf05eb7c2:/# which o64-clang++
/osxcross/target/bin/o64-clang++
# this works:
root@70edf05eb7c2:/# o64-clang++ -std=c++11 foo.cc
# this doesn't:
root@70edf05eb7c2:/# o64-clang++ -std=c++11 -stdlib=libc++ foo.cc
osxcross: error: targeted OS X version must be <= 10.6.0 (SDK)
osxcross: error: while detecting target
```

Why does `-stdlib=libc++` require OS X <= 10.6.0? In the absence of this flag, my code fails to compile because c++11 features can't be found.

**Comment by tamird** [comment]
Ah, this is just a bad error message that comes from the fact that the packaged SDK is version 10.6.0. Perhaps the message could be improved by including the actual target SDK version that was selected?

**Comment by tpoechtrager** [comment]
The error is actually about the SDK, not about `libc++`.
The 10.6 SDK does not come with `libc++`, you must use at least the 10.7 SDK.
Or build gcc - then you can use `*-g++` and `*-clang++-gstdc++` to compile C++11 code.
