### ISSUE TITLE
`warning: unknown attribute 'extern_c'` when using a new SDK (which contains usr/include/module.map)

### ISSUE THREAD

**Issue by tamird** [tpoechtrager/osxcross#53]
I'm locally using `MacOSX10.11.sdk`, and I see this warning all over the place:
```
/osxcross/target/bin/../SDK/MacOSX10.11.sdk/usr/include/module.map:1561:21: warning: unknown attribute 'extern_c'
```
even though I'm invoking `o64-clang` with `MACOSX_DEPLOYMENT_TARGET=10.9`. Seems like an old `clang` is being used somewhere. Any ideas?

**Comment by tpoechtrager** [comment]
Remove the `*.map` files or use `clang >= 3.5`.

**Comment by tamird** [comment]
How do I use clang >= 3.5?

**Comment by tpoechtrager** [comment]
Install a newer version of clang: http://llvm.org/releases/download.html#3.7.0.
Also [please remove the SDK link](https://github.com/tpoechtrager/osxcross/issues/4).

**Comment by tamird** [comment]
Thanks for your help.
