### ISSUE TITLE
build error: unknown target CPU 'pentium-m'

### ISSUE THREAD

**Issue by capr** [tpoechtrager/osxcross#54]
Hi,

I'm getting the following error on running `./build.sh`

~~~
extracting MacOSX10.7.sdk.tar.bz2 ...
compiling wrapper ...
error: unknown target CPU 'pentium-m'
error: unknown target CPU 'pentium-m'
make: *** [main.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [tools.o] Error 1
~~~

I'm on an ubuntu 14.04 (x64).

`clang --version` reports:

~~~
Ubuntu clang version 3.4-1ubuntu3 (tags/RELEASE_34/final) (based on LLVM 3.4)
Target: x86_64-pc-linux-gnu
Thread model: posix
~~~

Any idea?

What exact versions of software would you recommend to increase the chances to get this to work on the first try? Eg. I could install a fresh Ubuntu 14.04 server, then what packages, etc.? It would be nice if there were a list of commands that would "just work" on a fresh Ubuntu install which anybody can have on a VM in 10min.

PS: Thanks for all the hard work! Building and packaging work is under-appreciated :)

**Comment by tpoechtrager** [comment]
Should be "fixed".

> What exact versions of software would you recommend to increase the chances to get this to work on the first try? Eg. I could install a fresh Ubuntu 14.04 server, then what packages, etc.? It would be nice if there were a list of commands that would "just work" on a fresh Ubuntu install which anybody can have on a VM in 10min.

You can use `./tools/get_dependencies.sh` to install all *required* packages.
Some *optional* packages like `xar` must be installed by hand.

> PS: Thanks for all the hard work! Building and packaging work is under-appreciated :)

YW :-) But yes, it's indeed a lot of work!

**Comment by capr** [comment]
That did it. Thanks!
