### ISSUE TITLE
ObjCopy Implementation

### ISSUE THREAD

**Issue by durandj** [tpoechtrager/osxcross#56]
Is there an objcopy implementation provided by this toolchain? I haven't found one yet but wasn't sure if I was missing something.

**Comment by tpoechtrager** [comment]
Try `./build_binutils.sh`.

**Comment by durandj** [comment]
Well I feel like an idiot lol. Thanks!

**Comment by tpoechtrager** [comment]
No worries :smile:. You are welcome.
