### ISSUE TITLE
Dockerizing osxcross

### ISSUE THREAD

**Issue by virtuald** [tpoechtrager/osxcross#57]
Given the possible fragility of the build environment for a cross compiler such as this, it seems like it would be really useful to have an automated build available on Docker Hub for people to download (sans Xcode).

The way I would envision it working is that the base docker image that gets automatically published would install using a known distro and known packages that actually work (similar to your instructions in #45), and also does the work of installing osxcross in that environment. 

Then a second build script that one would have to run locally would download that image, copy the right xcode bits in the image, and then change the internal docker userid/groupid to match the local user credentials. This image would be saved locally.

Then, there would be an environment script that would launch the final image, and mount a volume inside the image whereever you specified. This would give you a shell into the environment, which then compiles could be executed reliably regardless of how your host OS packages change.

I would contemplate working on this, but I need to package a python product for OSX that has binary requirements, and I don't think pyinstaller would work in a cross-compilation environment.

**Comment by tpoechtrager** [comment]
Sure, sounds good. But I must admit, I have never really used Python nor Docker, so I can't help with that.

For the pyinstaller part, you could try [maloader](https://github.com/shinh/maloader) and/or [darling](https://github.com/darlinghq/darling) to run Mac OS X binaries on Linux. The later one is horrible to set up.

**Comment by tpoechtrager** [comment]
No reply since November. Closing.

**Comment by karalabe** [comment]
Btw, this is exactly the approach taken by [`xgo`](https://github.com/karalabe/xgo) for C embedded/dependent Go cross compilation. You might want to look at those dockerfiles for inspiration. I pretty much have everything you need ;)
