### ISSUE TITLE
Different binary target

### ISSUE THREAD

**Issue by fxfactorial** [tpoechtrager/osxcross#58]
Is it somehow possible to use this produce ELF binaries? I guess the sdks are given as mach-o libraries, but it would great if osxcross could use a stuff like Foundation and work on linux, specifically debian/ubuntu.

**Comment by tpoechtrager** [comment]
No, unfortunately this is not possible. You can use `ld-mac` or `darling` to run non-GUI Mac OS X binaries on Linux.

**Comment by geoff-codes** [comment]
Also worth looking at the [CFLITE](http://www.opensource.apple.com/source/CF/CF-1153.18/README_CFLITE) readme if you're going to try something like this.
