### ISSUE TITLE
Can't compile simple dynamic library

### ISSUE THREAD

**Issue by JonnoFTW** [tpoechtrager/osxcross#60]
I'm trying to build my project [Bibtex label generator](https://github.com/JonnoFTW/BibTeX-Label-Creator) for use on mac os x, but when I invoke: 
```
$ o32-clang++ -O3 -dynamiclib EntryExit.cpp -o bibtex_label_generator.dylib -I /cygdrive/c/local/EndNote\ SDK/RSServices -I /cygdrive/c/local/rapidxml-1.13  -I /cygdrive/c/local/boost_1_56_0
```

I get the error:
```
Undefined symbols for architecture i386:
  "MyIUIServiceNotifyCallbackImp::appendTitle(std::string)", referenced from:
      _Init in EntryExit-93ac7e.o
  "MyIUIServiceNotifyCallbackImp::AddToToolsMenu()", referenced from:
      _Init in EntryExit-93ac7e.o
  "MyIUIServiceNotifyCallbackImp::OnMenuItemSelected()", referenced from:
      vtable for ResearchSoft::CBaseObject<MyIUIServiceNotifyCallbackImp> in EntryExit-93ac7e.o
  "MyIUIServiceNotifyCallbackImp::useSep(bool)", referenced from:
      _Init in EntryExit-93ac7e.o
  "MyIUIServiceNotifyCallbackImp::MyIUIServiceNotifyCallbackImp()", referenced from:
      _Init in EntryExit-93ac7e.o
  "MyIUIServiceNotifyCallbackImp::~MyIUIServiceNotifyCallbackImp()", referenced from:
      ResearchSoft::CBaseObject<MyIUIServiceNotifyCallbackImp>::~CBaseObject() in EntryExit-93ac7e.o
      ResearchSoft::CBaseObject<MyIUIServiceNotifyCallbackImp>::~CBaseObject() in EntryExit-93ac7e.o
  "typeinfo for MyIUIServiceNotifyCallbackImp", referenced from:
      typeinfo for ResearchSoft::CBaseObject<MyIUIServiceNotifyCallbackImp> in EntryExit-93ac7e.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any ideas on how to fix this? Also, to get boost working, do I need to build the libraries using the mac os x toolchain? Would it be worth it to just rewrite the `trim`, `split`, `to_lower` and `regex_replace` calls in vanilla c++?

**Comment by tpoechtrager** [comment]
You must link against the libraries (`-lboost-system`, etc.). Also ensure you are using the right C++ standard library, boost is probably using `libc++` and not `libstdc++`.

**Comment by JonnoFTW** [comment]
It still won't compile, now I get: 

```
$ o32-clang++-libc++ -O3 -dynamiclib EntryExit.cpp -o bibtex_label_generator.dylib -I/cygdrive/c/local/EndNote\ SDK/RSServices -I/cygdrive/c/local/rapidxml-1.13 \
   -lboost-system -lboost-regex
ld: library not found for -lboost-system
```

In cygwin I have installed all the boost libraries and I tried with `o32-clang++-libc++`, `o32-clang++`, `o32-clang++-libc++`, and `o32-clang++-stdc++`. I have all the cygwin packages installed for libboost 1.58 and libboost-devel.

**Comment by tpoechtrager** [comment]
You must install the MacPorts packages:

    $ echo "export MACOSX_DEPLOYMENT_TARGET=10.8" >> ~/.bashrc
    $ echo "export OSXCROSS_MP_INC=1" >> ~/.bashrc
    $ source ~/.bashrc
    $ osxcross-macports install boost
    $ o64-clang++-libc++ test.cpp -lboost_system-mt # boost is 64-bit!

**Comment by JonnoFTW** [comment]
I get the same error, after successfully installing the boost libraries (and I verified that they work with the compiler with a test program).
```
$ o64-clang++-libc++ -O3 -dynamiclib EntryExit.cpp -o bibtex_label_generator.dylib -I/cygdrive/c/local/EndNote\ SDK/RSServices -I/cygdrive/c/local/rapidxml-1.13 -lboost_regex-mt -lboost_system-mt
Undefined symbols for architecture x86_64:
  "MyIUIServiceNotifyCallbackImp::appendTitle(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      _Init in EntryExit-ce7e9b.o
  "MyIUIServiceNotifyCallbackImp::AddToToolsMenu()", referenced from:
      _Init in EntryExit-ce7e9b.o
  "MyIUIServiceNotifyCallbackImp::OnMenuItemSelected()", referenced from:
      vtable for ResearchSoft::CBaseObject<MyIUIServiceNotifyCallbackImp> in EntryExit-ce7e9b.o
  "MyIUIServiceNotifyCallbackImp::useSep(bool)", referenced from:
      _Init in EntryExit-ce7e9b.o
  "MyIUIServiceNotifyCallbackImp::MyIUIServiceNotifyCallbackImp()", referenced from:
      _Init in EntryExit-ce7e9b.o
  "MyIUIServiceNotifyCallbackImp::~MyIUIServiceNotifyCallbackImp()", referenced from:
      ResearchSoft::CBaseObject<MyIUIServiceNotifyCallbackImp>::~CBaseObject() in EntryExit-ce7e9b.o
      ResearchSoft::CBaseObject<MyIUIServiceNotifyCallbackImp>::~CBaseObject() in EntryExit-ce7e9b.o
  "typeinfo for MyIUIServiceNotifyCallbackImp", referenced from:
      typeinfo for ResearchSoft::CBaseObject<MyIUIServiceNotifyCallbackImp> in EntryExit-ce7e9b.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tpoechtrager** [comment]
This works:

    OSXCROSS_MP_INC=1 o64-clang++-libc++ -O3 -dynamiclib EntryExit.cpp Callback.cpp -fdelayed-template-parsing -o bibtex_label_generator.dylib -IEndNote\ SDK/RSServices  -isystem . -lboost_regex-mt -lboost_system-mt

`-fdelayed-template-parsing` is important, otherwise you will get:

    In file included from Callback.cpp:33:
    ./rapidxml/rapidxml_print.hpp:115:23: error: call to function 'print_children' that is neither visible in the template definition nor found by argument-dependent lookup
                    out = print_children(out, node, flags, indent);
                          ^
    ./rapidxml/rapidxml_print.hpp:390:26: note: in instantiation of function template specialization 'rapidxml::internal::print_node<std::__1::back_insert_iterator<std::__1::basic_string<char> >, char>' requested here
            return internal::print_node(out, &node, flags, 0);
                            ^
    Callback.cpp:201:3: note: in instantiation of function template specialization 'rapidxml::print<std::__1::back_insert_iterator<std::__1::basic_string<char> >, char>' requested here
                    print(back_inserter(outXML),doc,print_no_indenting);
                    ^
    ./rapidxml/rapidxml_print.hpp:169:22: note: 'print_children' should be declared prior to the call site or in namespace 'rapidxml'
            inline OutIt print_children(OutIt out, const xml_node<Ch> *node, int flags, int indent)
                        ^
    [and so on...]

**Comment by tpoechtrager** [comment]
No reply. Closing.

**Comment by JonnoFTW** [comment]
Sorry, I forgot about this, I don't have a mac to test on and the user I got to test the file couldn't get it working:

https://github.com/JonnoFTW/BibTeX-Label-Creator/issues/2

**Comment by tpoechtrager** [comment]
No problem! Feel free to reopen if you have any further questions.
