### ISSUE TITLE
Macports disregards any arch

### ISSUE THREAD

**Issue by TrueBrain** [tpoechtrager/osxcross#62]
osxcross-macports loads the macports dir, sorted by modified time, and just picks the latest item matching the darwin_NN.

This is fine for x86_64, as most packages have either x86_64, or +universal containing the x86_64. Besides from looking a bit silly (some packages x86_64, others +universal), and wasting some bytes (in case of +universal), this seems to be working just fine.

But when you want/need i386 libraries, this often goes wrong.

A quick solution is to filter on ARCH too. I used something like this:

    sed -i 's/OSXVERSION | uniq/OSXVERSION | grep "$ARCH" | uniq/' tools/osxcross-macports

This allows me to run:

    ARCH=i386 osxcross-macports upgrade

and only receive i386 versions (which are most often universal). Of course this solution is a bit silly, but I am sure you get the point here :)

**Comment by tpoechtrager** [comment]
I have added an (undocumented) `--i386` option.

There's just one major problem: There are barely any `i386` packages anymore, `zlib` is one of the few I could find.

A working example would be:

`MACOSX_DEPLOYMENT_TARGET=10.6 osxcross-macports install zlib --i386`
