### ISSUE TITLE
SDL 2.0.4 fails to compile with sdk 10.11 (from xcode 7.2)

### ISSUE THREAD

**Issue by pisto** [tpoechtrager/osxcross#63]
here the errors http://pastebin.com/XKeDALLE . the sdk for 10.10 (can't remember which xcode I extracted) works. clang version is:
```
clang version 3.5.0 (tags/RELEASE_350/final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/5.3.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

**Comment by tpoechtrager** [comment]
You may need a newer version of Clang.

Try

http://llvm.org/releases/3.7.1/clang+llvm-3.7.1-x86_64-fedora22.tar.xz
http://llvm.org/releases/3.7.1/clang+llvm-3.7.1-x86_64-fedora22.tar.xz.sig

**Comment by tpoechtrager** [comment]
No reply. Closing.

**Comment by pisto** [comment]
sorry, just forgot about it, keep it closed, I'll try some day

**Comment by pisto** [comment]
clang was indeed the problem.
