### ISSUE TITLE
Build a wxWidgets 3.0.2 applications fails

### ISSUE THREAD

**Issue by Arucard1983** [tpoechtrager/osxcross#64]
During my Ph. D. thesis I wrote a program to evaluate nuclear reaction yields, which I use wxWidgets to do the GUI , and since I use a Linux computer, I build a native Linux version, and a Windows version using the Mingw cross-compiler.
Since some of my colleges use Mac, I decided to make a native OS X port, since wxWidgets aids to compile a nice GUI application without change any line of code.
 Build the cross-compiling and this MacPorts wrapper went flawlessly, even to install the wxWidgets 3.0 libraries. When I run the cross-compiler command it fails due to wx-config script, unless I use aworkaround to set manually the correct libraries PATH.
  
 Switching to wx-config directory, and run
$ ./osx_cocoa-unicode-3.0 --libs
Gets the following error...
Warning: No config found to match: ./osx_cocoa-unicode-3.0 --libs
                   in /opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.0/lib/wx/config

While the real Path is...
$ ~/DOS/OSX/macports/pkgs/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.0/lib/wx/config

Using the pre-defined path, and the real one won't make any difference.
How to fix this issue ?

**Comment by tpoechtrager** [comment]
Try symlinking `~/DOS/OSX/macports/pkgs/opt/local` to `/opt/local`

    mkdir -p /opt
    ln -s ~/DOS/OSX/macports/pkgs/opt/local /opt/local

... not a great solution, but it might work.

**Comment by Arucard1983** [comment]
To avoid such hacks, I decided to cross-compile the wxWidgets directly to the osxcross folder (I created /opt/Darwin on that), using the source-code.
- By reference, the configure command I issued was...
./configure --prefix=/home/nosferatu/DOS/OSX/opt/Darwin/ --host=x86_64-apple-darwin15  CC=o64-clang CXX=o64-clang++ --build=x86_64-linux --with-osx_cocoa --with-macosx-version-min=10.11  --disable-shared --enable-monolithic --enable-unicode --without-subdirs

- And then make && make install as usually, make the job done.
(However, in large programs with several libraries, it could be overkill.)

- My suggestion to avoid this problems with MacPorts, it was to add some shell variable that emulates the "virtual" /opt that some OS X libraries from MacPorts expected to work. This would make cross-compiling more easy.

- Unless I create command-line OS X programs, the Darling emulator would not run on Linux. (Darling is basically the Wine cousin to run Mac OS X programs on Linux, like Wine does to Windows programs.)

**Comment by Arucard1983** [comment]
And to build the famous program, just type: 
o64-clang++ *.cpp `/home/nosferatu/DOS/OSX/opt/Darwin/bin/wx-config --cxxflags --libs` -stdlib=libc++  -o TargetExecutable


But Darling is not ready to run GUI programs, because it gives an error due to missing Carbon libraries... (Even it uses a lot of Cocoa API; that even Darling don't support yet)

**Comment by tpoechtrager** [comment]
That is indeed a way better solution. I will create a FAQ Wiki soon and will definitely add your solution.

> But Darling is not ready to run GUI programs, because it gives an error due to missing Carbon libraries... (Even it uses a lot of Cocoa API; that even Darling don't support yet)

Yeah... and not easy to set up. Or in the words of the main Darling developer:

> Yep. Looking at osxcross, I think Darling is already easier to use and performing better, but there is still a lot left to desire.

Closing this since you found a proper solution by yourself.
