### ISSUE TITLE
How cc is different than clang?

### ISSUE THREAD

**Issue by zatarus** [tpoechtrager/osxcross#68]
I don't understand what cc actually presents if gcc is not compiled by default. At first I thought it is same as clang but I think that has something different.

I have traced up to here:
https://github.com/tpoechtrager/osxcross/blob/master/wrapper/main.cpp#L404

I'm asking because I'm looking a way to build it for iOS as well, which is not listed in usage example of cctools-port project.

Appreciate any insights.

**Comment by tpoechtrager** [comment]
`-cc` is exactly the same as `<arch>-apple-darwinXX-clang` or `o<arch>-clang`.

Are you trying to build OSXCross for iOS or do you want to cross compile code for iOS?

**Comment by zatarus** [comment]
Thank you for the response. I've attempted to compile a library with clang, which failed with reference errors, and whenever I rename it to cc, it compiles every time. If they are same then I guess there might be a std lib difference, if not, then CMake is interpreting the compiler name to act differently. I will research this whether it is project specific and will give a feedback. 

I'm cross compiling code for iOS, not using osxcross(but cc tools port).  Same situation is holding me back for building iOS version as cc is not present. But again, that might be project specific. I will take time on it.

**Comment by tpoechtrager** [comment]
You probably need to set `CC` and `CXX` before running `cmake`.

Try:

    export CC=arm-apple-darwin11-clang
    export CXX=arm-apple-darwin11-clang++

Or:

    cmake -DCMAKE_C_COMPILER=arm-apple-darwin11-clang -DCMAKE_CXX_COMPILER=arm-apple-darwin11-clang++

Automake:

    CC=arm-apple-darwin11-clang CXX=arm-apple-darwin11-clang++ ./configure --host=arm-apple-darwin11

**Comment by zatarus** [comment]
I stick to CMAKE_FORCE_C_COMPILER and CMAKE_FORCE_CXX_COMPILER, but tried suggested variables as well. Error occurs when static libraries are built, and it is time to link them for HelloWorld.
Exact errors is: file was built for archive which is not the architecture being linked (x86_64)

I did a dirty trick to inject the static libraries built with c++ into clang++ build, and it worked! So, I'm pretty sure it is not the linking (flags are same) logic but difference lies in the way .a files are built. Sadly, lipo gives exact same output for both versions:
.. is not a fat file
.. is architecture: x86_64

**Comment by zatarus** [comment]
I better close this until I get a prove on osxcross side, will trace few stuff.
