### ISSUE TITLE
OSXCROSS_PKG_CONFIG* variables breaking the indended use of respective variables

### ISSUE THREAD

**Issue by stefanct** [tpoechtrager/osxcross#69]
What's the rationale behind breaking the native interface of pkg-config so badly by unsetting all ordinary native variables of pkg-config and forcing users to set the alternative values. The whole point of setting these values in the first place is to pass information to pkg-config. If the defaults are wrong then the user needs to set them appropriately before calling pkg-config and any non-broken cross compiler invocation will do that. With the wrapper as is a user having other (orderly behaving) cross compilers has to jump through hoops to coerce the osx wrapper to work as intended.

What's worse is that it does not tell the user of anything of this... just by reading the source it is possible to derive that it is not simply broken but intentionally constructed to avoid doing the right thing. (Yes, I am quite furious at the moment.)

**Comment by tpoechtrager** [comment]
This is a spare time project and I haven't seen a single cent for it - so if you expect me to help, calm down.

It's the way it is because `pkg-config` caused a lot of `./configure` scripts to include *native* (/usr/include) header files.

**Comment by stefanct** [comment]
Those configure scripts are broken or wrongly used. Build environments in general and autotools especially have become rather good and easy to use at crosscompiling support. Rewarding broken things by working around their flaws and breaking tools behaving honestly is not a very good idea in the long term in general. If you think your approach is nevertheless the right thing to do please add at least some error output to the else branch of [the respective if](https://github.com/tpoechtrager/osxcross/blob/f51b758db4706bd8c24e1d82cfa8d9bf4bfa427d/wrapper/programs/pkg-config.cpp#L79) to avoid wasting time of people who are in general on your side.

Just to put this into what I think is the right perspective: OSX on amd64 is the 40th architecture/OS combination I am automatically building for testing http://flashrom.org - in my own free time. Thank you for making this possible.

**Comment by tpoechtrager** [comment]
Does [this patch](https://gist.github.com/tpoechtrager/54db3b0d21ca1a301170) (barely tested) fit your needs?

Changes:

* `OSXCROSS_PKG_CONFIG_USE_NATIVE_VARIABLES=1` restores the default behavior
* New warning: `x86_64-apple-darwin15-pkg-config: ignoring environment variable 'PKG_CONFIG_*' - please see README.PKG-CONFIG.md for more`
* New Warning: `x86_64-apple-darwin15-pkg-config is a no-op - please see README.PKG-CONFIG.md for more`

**Comment by stefanct** [comment]
Looks reasonable to me. In my setup I have added a special case for osx already to set the OSXCROSS variables, but it would have definitely helped me before being aware of the situation. AFAICT this should also avoid regressions for existing osxcross users. Thanks for the fast reaction and mitigation efforts.

**Comment by tpoechtrager** [comment]
> Looks reasonable to me. In my setup I have added a special case for osx already to set the OSXCROSS variables, but it would have definitely helped me before being aware of the situation. AFAICT this should also avoid regressions for existing osxcross users.

Good. I will apply that patch including a README for pkg-config soon.

> Thanks for the fast reaction and mitigation efforts.

YW!
