### ISSUE TITLE
Problems installing osxcross

### ISSUE THREAD

**Issue by supertriodo** [tpoechtrager/osxcross#70]
Hi,
First of all thanks for all the hard work making this awesome project.
I would like to use it to make a Mac OS binary of my project (Arena Tracker) like I do with mxe for windows.

I'm on Linux Mint 17.3

I followed the install instruction:
* sudo tools/get_dependencies.sh
* Download xcode 7.0.1 on /tools
* Packing the SDK on Linux Method 1
 * clang and make are up to date
 * On /tools run ./gen_sdk_package_p7zip.sh <xcode>.dmg

I get:
_triodo@led ~/osxcross-master/tools $ ./gen_sdk_package_p7zip.sh xcode_7.0.1.dmg
7-Zip [64] 9.38 beta  Copyright (c) 1999-2014 Igor Pavlov  2015-01-03
p7zip Version 9.38.1 (locale=C,Utf16=off,HugeFiles=on,8 CPUs)
Command Line Error:
Cannot find archive
/home/triodo/osxcross-master/xcode_7.0.1.dmg
triodo@led ~/osxcross-master/tools $_

 * On /tools I try sh gen_sdk_package_p7zip.sh <xcode>.dmg

I get:
_triodo@led ~/osxcross-master/tools $ sh gen_sdk_package_p7zip.sh xcode_7.0.1.dmg 
gen_sdk_package_p7zip.sh: 4: gen_sdk_package_p7zip.sh: source: not found
gen_sdk_package_p7zip.sh: 6: [: ==: unexpected operator
gen_sdk_package_p7zip.sh: 3: gen_sdk_package_p7zip.sh: pushd: not found
mkdir: falta un operando
Pruebe 'mkdir --help' para más información.
gen_sdk_package_p7zip.sh: 23: gen_sdk_package_p7zip.sh: require: not found
gen_sdk_package_p7zip.sh: 24: gen_sdk_package_p7zip.sh: require: not found
gen_sdk_package_p7zip.sh: 29: gen_sdk_package_p7zip.sh: pushd: not found
Clonar en «p7zip»...
remote: Counting objects: 1285, done.
remote: Compressing objects: 100% (1078/1078), done.
remote: Total 1285 (delta 185), reused 1285 (delta 185), pack-reused 0
Receiving objects: 100% (1285/1285), 4.35 MiB | 665.00 KiB/s, done.
Resolving deltas: 100% (185/185), done.
Checking connectivity... hecho.
gen_sdk_package_p7zip.sh: 39: gen_sdk_package_p7zip.sh: pushd: not found
Error:
Incorrect command line
install: falta el operando archivo de destino después de «DEST_HOME=/SDK/tools»
Pruebe 'install --help' para más información.
find: «/SDK/tools/share»: No existe el archivo o el directorio
find: «/SDK/tools/share»: No existe el archivo o el directorio
gen_sdk_package_p7zip.sh: 50: gen_sdk_package_p7zip.sh: popd: not found
gen_sdk_package_p7zip.sh: 72: gen_sdk_package_p7zip.sh: Syntax error: "(" unexpected
gen_sdk_package_p7zip.sh: 56: gen_sdk_package_p7zip.sh: popd: not found
triodo@led ~/osxcross-master/tools $_

No luck so I tried with the other method.
* Packing the SDK on Linux Method 2
 * Install cmake, libxml2-dev and fuse. All up-to-date
 * On /tools Run ./gen_sdk_package_darling_dmg.sh <xcode>.dmg

I get:
_triodo@led ~/osxcross-master/tools $ ./gen_sdk_package_darling_dmg.sh xcode_7.0.1.dmg 
required kernel module 'fuse' not loaded
please run 'insmod fuse' as root
triodo@led ~/osxcross-master/tools $_

 * Run insmod fuse as root

I get:
_triodo@led ~/osxcross-master/tools $ sudo insmod fuse
insmod: ERROR: could not load module fuse: No such file or directory
triodo@led ~/osxcross-master/tools $_

 * On /tool I try sh gen_sdk_package_darling_dmg.sh <xcode>.dmg

I get:
_triodo@led ~/osxcross-master/tools $ sh gen_sdk_package_darling_dmg.sh xcode_7.0.1.dmg 
gen_sdk_package_darling_dmg.sh: 4: gen_sdk_package_darling_dmg.sh: source: not found
gen_sdk_package_darling_dmg.sh: 6: [: ==: unexpected operator
gen_sdk_package_darling_dmg.sh: 3: gen_sdk_package_darling_dmg.sh: pushd: not found
mkdir: falta un operando
Pruebe 'mkdir --help' para más información.
gen_sdk_package_darling_dmg.sh: 18: gen_sdk_package_darling_dmg.sh: require: not found
gen_sdk_package_darling_dmg.sh: 19: gen_sdk_package_darling_dmg.sh: require: not found
gen_sdk_package_darling_dmg.sh: 20: gen_sdk_package_darling_dmg.sh: require: not found
gen_sdk_package_darling_dmg.sh: 21: gen_sdk_package_darling_dmg.sh: require: not found
gen_sdk_package_darling_dmg.sh: 22: gen_sdk_package_darling_dmg.sh: require: not found
gen_sdk_package_darling_dmg.sh: 39: gen_sdk_package_darling_dmg.sh: pushd: not found
modinfo: ERROR: Module fuse not found.
Clonar en «darling-dmg»...
remote: Counting objects: 568, done.
remote: Total 568 (delta 0), reused 0 (delta 0), pack-reused 568
Receiving objects: 100% (568/568), 165.55 KiB | 0 bytes/s, done.
Resolving deltas: 100% (375/375), done.
Checking connectivity... hecho.
gen_sdk_package_darling_dmg.sh: 49: gen_sdk_package_darling_dmg.sh: pushd: not found
gen_sdk_package_darling_dmg.sh: 51: gen_sdk_package_darling_dmg.sh: pushd: not found
CMake Error: The source directory "/home/triodo/osxcross-master" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
triodo@led ~/osxcross-master/tools $_

Thank you in advance.

**Comment by zarvox** [comment]
The output of your first attempt looks like it's looking for the xcode dmg in `~/osxcross-master/` rather than `~/osxcross-master/tools`.  Try moving the dmg to where it says it's looking and running `./gen_sdk_package_p7zip.sh xcode_7.0.1.dmg` from the `tools/` directory again?

As for why the rest of the commands you tried failed: note that the scripts require `bash`, not just `sh`, as indicated by the first line of each (`#!/usr/bin/env bash`).

**Comment by supertriodo** [comment]
Wow, I feel so dumb now, It clearly say it. It worked! Thanks!

The project I want to crosscompile is a qt project that use opencv, is it possible?

**Comment by supertriodo** [comment]
Alright o32-clang++ and o64-clang++ have been generated on
/home/triodo/osxcross-master/target/bin

With mxe I use a specific qmake tool from mxe to generate the make.

I have this script that compile the project through mxe:
_#!/bin/bash
export PATH=$HOME/mxe2/mxe/usr/bin:$PATH
~/mxe2/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5
make_

Is there anything similar for osxcross?
This is my .pro file
http://hastebin.com/jacocahore.pl
