### ISSUE TITLE
Project in qt using opencv

### ISSUE THREAD

**Issue by supertriodo** [tpoechtrager/osxcross#71]
Hi,
I'm on Linux Mint

Alright o32-clang++ and o64-clang++ have been generated on
/home/triodo/osxcross-master/target/bin

With mxe I use a specific qmake tool from mxe to generate the make.

I have this script that compile the project through mxe:
#!/bin/bash
export PATH=$HOME/mxe2/mxe/usr/bin:$PATH
~/mxe2/mxe/usr/bin/i686-w64-mingw32.static-qmake-qt5
make

Is there anything similar for osxcross?
This is my .pro file
http://hastebin.com/jacocahore.pl

I have tried generating the Makefile through a qt5.5 static compiled version I have that allow me generate a static compiled version of my project for Linux.
Then I tried to compile that Makefile:
* export PATH=/home/triodo/osxcross-master/target/bin:$PATH
* make CC=o32-clang CXX=o32-clang++ LINK=o32-clang++

There's a ton of warning but all the .o are generated. The linker then throw this errors:

_o32-clang++ -Wl,-O1 -o ArenaTracker main.o mainwindow.o logloader.o logworker.o gamewatcher.o webuploader.o hscarddownloader.o deckhandler.o enemyhandhandler.o arenahandler.o secretshandler.o drafthandler.o heartharenamentor.o utility.o deckcard.o handcard.o secretcard.o draftcard.o drawcard.o resizebutton.o draftscorewindow.o scorebutton.o movelistwidget.o movetabwidget.o movetreewidget.o moveverticalscrollarea.o cardwindow.o versionchecker.o hearthstatsuploader.o enemydeckhandler.o arenatracker_plugin_import.o qrc_arenatracker.o moc_mainwindow.o moc_logloader.o moc_logworker.o moc_gamewatcher.o moc_webuploader.o moc_hscarddownloader.o moc_deckhandler.o moc_enemyhandhandler.o moc_arenahandler.o moc_secretshandler.o moc_drafthandler.o moc_heartharenamentor.o moc_resizebutton.o moc_draftscorewindow.o moc_scorebutton.o moc_movelistwidget.o moc_movetreewidget.o moc_moveverticalscrollarea.o moc_cardwindow.o moc_versionchecker.o moc_hearthstatsuploader.o moc_enemydeckhandler.o   -L/usr/local/lib -L/usr/local/share/OpenCV/3rdparty/lib -lopencv_contrib -lopencv_stitching -lopencv_nonfree -lopencv_superres -lopencv_ocl -lopencv_ts -lopencv_videostab -lopencv_gpu -lopencv_photo -lopencv_objdetect -lopencv_legacy -lopencv_video -lopencv_ml -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lIlmImf -lopencv_imgproc -lopencv_flann -lopencv_core -lzlib -lv4l2 -lv4l1 -ldc1394 -lgstpbutils-0.10 -lgstriff-0.10 -lgstapp-0.10 -lgstvideo-0.10 -lxml2 -lgmodule-2.0 -lgstreamer-0.10 -lgstbase-0.10 -lpango-1.0 -lcairo -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lpangoft2-1.0 -lgio-2.0 -latk-1.0 -lgdk-x11-2.0 -lgtk-x11-2.0 -ltbb -lstdc++ -L/home/triodo/qt-static-5.5/lib -lQt5Widgets -lgobject-2.0 -L/home/triodo/qt-static-5.5/plugins/platforms -lqxcb -L/home/triodo/qt-static-5.5/plugins/xcbglintegrations -lqxcb-glx-integration -lxcb-glx -lQt5XcbQpa -lX11-xcb -lXi -lxcb-render-util -lSM -lICE -lxcb-render -lxcb -lxcb-image -lxcb-icccm -lxcb-sync -lxcb-xfixes -lxcb-shm -lxcb-randr -lxcb-shape -lxcb-keysyms -lQt5PlatformSupport -lfontconfig -lfreetype -lXrender -lXext -lX11 -L/home/triodo/qt-static-5.5/plugins/imageformats -lqdds -lqicns -lqico -lqjp2 -ljasper -lqmng -lqtga -lqtiff -ltiff -lqwbmp -lqwebp -lQt5Gui -ljpeg -lpng -lqtharfbuzzng -L/home/triodo/qt-static-5.5/plugins/bearer -lqconnmanbearer -lqgenericbearer -lqnmbearer -lQt5Network -lQt5DBus -lQt5Core -lz -lqtpcre -lm -ldl -pthread -lgthread-2.0 -lglib-2.0 -lrt -lGL -lpthread 
clang: warning: argument unused during compilation: '-pthread'
ld: unknown option: -O1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ArenaTracker] Error 1_

Well I guess is normal it doesn't work as that Makefile was generated with Linux in mind. I have tried to mess around with qmake following the documentation, but if you want to target Mac OS while using qmake I think you have to be on Mac.

Thanks in advance. Getting this to work would be amazing.

**Comment by tpoechtrager** [comment]
As a *temporary workaround* you could make the linker ignore `-O` to see if you can get any further that way.

`cd` into `build/cctools-877.5-ld64-253.3_4f8ad51/cctools` and open `ld64/src/ld/Options.cpp` with an editor and add

    else if ( strcmp(arg, "-O") == 0 || strcmp(arg, "-O0") == 0 || strcmp(arg, "-O1") == 0 || strcmp(arg, "-O2") == 0 || strcmp(arg, "-O3") == 0 ) {

    }

after

    else if ( strcmp(arg, "-o") == 0 ) {
        ...
    }

`make install -j...`

**Comment by supertriodo** [comment]
I removed the link flags with:
* make CC=o32-clang CXX=o32-clang++ LINK=o32-clang++ LFLAGS=

I got this:
_o32-clang++  -o ArenaTracker main.o mainwindow.o logloader.o logworker.o gamewatcher.o webuploader.o hscarddownloader.o deckhandler.o enemyhandhandler.o arenahandler.o secretshandler.o drafthandler.o heartharenamentor.o utility.o deckcard.o handcard.o secretcard.o draftcard.o drawcard.o resizebutton.o draftscorewindow.o scorebutton.o movelistwidget.o movetabwidget.o movetreewidget.o moveverticalscrollarea.o cardwindow.o versionchecker.o hearthstatsuploader.o enemydeckhandler.o arenatracker_plugin_import.o qrc_arenatracker.o moc_mainwindow.o moc_logloader.o moc_logworker.o moc_gamewatcher.o moc_webuploader.o moc_hscarddownloader.o moc_deckhandler.o moc_enemyhandhandler.o moc_arenahandler.o moc_secretshandler.o moc_drafthandler.o moc_heartharenamentor.o moc_resizebutton.o moc_draftscorewindow.o moc_scorebutton.o moc_movelistwidget.o moc_movetreewidget.o moc_moveverticalscrollarea.o moc_cardwindow.o moc_versionchecker.o moc_hearthstatsuploader.o moc_enemydeckhandler.o   -L/usr/local/lib -L/usr/local/share/OpenCV/3rdparty/lib -lopencv_contrib -lopencv_stitching -lopencv_nonfree -lopencv_superres -lopencv_ocl -lopencv_ts -lopencv_videostab -lopencv_gpu -lopencv_photo -lopencv_objdetect -lopencv_legacy -lopencv_video -lopencv_ml -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lIlmImf -lopencv_imgproc -lopencv_flann -lopencv_core -lzlib -lv4l2 -lv4l1 -ldc1394 -lgstpbutils-0.10 -lgstriff-0.10 -lgstapp-0.10 -lgstvideo-0.10 -lxml2 -lgmodule-2.0 -lgstreamer-0.10 -lgstbase-0.10 -lpango-1.0 -lcairo -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lpangoft2-1.0 -lgio-2.0 -latk-1.0 -lgdk-x11-2.0 -lgtk-x11-2.0 -ltbb -lstdc++ -L/home/triodo/qt-static-5.5/lib -lQt5Widgets -lgobject-2.0 -L/home/triodo/qt-static-5.5/plugins/platforms -lqxcb -L/home/triodo/qt-static-5.5/plugins/xcbglintegrations -lqxcb-glx-integration -lxcb-glx -lQt5XcbQpa -lX11-xcb -lXi -lxcb-render-util -lSM -lICE -lxcb-render -lxcb -lxcb-image -lxcb-icccm -lxcb-sync -lxcb-xfixes -lxcb-shm -lxcb-randr -lxcb-shape -lxcb-keysyms -lQt5PlatformSupport -lfontconfig -lfreetype -lXrender -lXext -lX11 -L/home/triodo/qt-static-5.5/plugins/imageformats -lqdds -lqicns -lqico -lqjp2 -ljasper -lqmng -lqtga -lqtiff -ltiff -lqwbmp -lqwebp -lQt5Gui -ljpeg -lpng -lqtharfbuzzng -L/home/triodo/qt-static-5.5/plugins/bearer -lqconnmanbearer -lqgenericbearer -lqnmbearer -lQt5Network -lQt5DBus -lQt5Core -lz -lqtpcre -lm -ldl -pthread -lgthread-2.0 -lglib-2.0 -lrt -lGL -lpthread 
clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lv4l2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ArenaTracker] Error 1_

**Comment by tpoechtrager** [comment]
Obviously an incompatible Makefile. V4L = Video4Linux.
