### ISSUE TITLE
MacOSX10.11 SDK c++ compilation error

### ISSUE THREAD

**Issue by bfoo75** [tpoechtrager/osxcross#73]
Having issues with a compilation error when building the c++ compiler with MacOSx10.11:

![2016-04-13 14_19_15-tarballs](https://cloud.githubusercontent.com/assets/4731399/14509787/01c12f92-0183-11e6-9e7a-bb387a4ecdc9.png)

Going to try again with 10.10

**Comment by bfoo75** [comment]
Yeah 7.2.1 still doesn't work either when exporting from el capitan...  It's the same error and same SDK, even tho the tarball is a slightly smaller package.

**Comment by tpoechtrager** [comment]
Looks like the Cygwin guys broke the default include paths. Please let me know if my workaround fixes the include issue ([cygwin branch](https://github.com/tpoechtrager/osxcross/tree/cygwin)).

**Comment by bfoo75** [comment]
Awesome yeah, that fixed the compilation error.

**Comment by bfoo75** [comment]
Nice work Thank you tpoechtrager!
