### ISSUE TITLE
Please add smartmontools to the project lists 

### ISSUE THREAD

**Issue by samm-git** [tpoechtrager/osxcross#74]
Hello. I just want to thank authors of the osxcross project. We are using it on smartmontools.org to produce [daily builds](http://builds.smartmontools.org/)  and releases (6.5+). So it would be great to add it to the users list )

**Comment by tpoechtrager** [comment]
Done! And I have to thank you too. Your excellent `smartctl` tool helped me to prevent data loss a couple of months ago.
