### ISSUE TITLE
Intrinsic headers not found

### ISSUE THREAD

**Issue by rannbaron** [tpoechtrager/osxcross#79]
$ o64-clang++
osxcross: warning: cannot find clang intrinsic headers; please report this issue to the OSXCross project
osxcross: error: invoking compiler failed
osxcross: debug: --> o64-clang++ 
osxcross: debug: <-- clang++ -target x86_64-apple-darwin15 -mlinker-version=264.3.102 -isysroot /home/rann/src/osxcross-master/target/bin/../SDK/MacOSX10.11.sdk -stdlib=libstdc++ -cxx-isystem /home/rann/src/osxcross-master/target/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/4.2.1 -cxx-isystem /home/rann/src/osxcross-master/target/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/4.2.1/x86_64-apple-darwin15 -cxx-isystem /home/rann/src/osxcross-master/target/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/4.2.1/backward -mmacosx-version-min=10.5.0 -arch x86_64

This happens regardless of what I try to compile 

Please help!

**Comment by tpoechtrager** [comment]
Looks like you don't have Clang installed?

**Comment by rannbaron** [comment]
Ack! I had the clang-3.6 package installed, but not clang itself. I apologize for taking up your time!

**Comment by rannbaron** [comment]
I now get another error:

osxcross-master/target/bin/x86_64-apple-darwin15-ld: error
  while loading shared libraries: libLTO.so: cannot open shared object file:
  No such file or directory

I've now moved to clang-3.8 because I need openmp support.

**Comment by tpoechtrager** [comment]
Recompile OSXCross: `rm build/have_*; ./build.sh`

**Comment by rannbaron** [comment]
Done!

Next error:

-- Check for working CXX compiler: /home/rann/src/osxcross-master/target/bin/o64-clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenMP (missing: OpenMP_C_FLAGS OpenMP_CXX_FLAGS)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindOpenMP.cmake:234 (find_package_handle_standard_args)
  CMakeLists.txt:31 (FIND_PACKAGE)


I think this has to do with libiomp5 and the location of gomp omp header files

**Comment by tpoechtrager** [comment]
I have no clue about OpenMP. Sorry.

You will probably have to build libiomp for Mac OS X.

**Comment by tpoechtrager** [comment]
Closing (not really an OSXCross issue). Feel free to reopen if you have any further questions.
