### ISSUE TITLE
CMake toolchain files

### ISSUE THREAD

**Issue by OmniBlade** [tpoechtrager/osxcross#80]
More of a suggestion than an issue really, but it would be nice if there was a script to auto generate tool chain files to pass to cmake to configure it for cross compiles.

**Comment by tpoechtrager** [comment]
Good idea. Do you have an example CMake toolchain file for OSXCross?

**Comment by OmniBlade** [comment]
This should work when the CMAKE_FIND_ROOT_PATH is set to the install path of OSXCross.

[ubuntu-osxcross-10.7.txt](https://github.com/tpoechtrager/osxcross/files/385576/ubuntu-osxcross-10.7.txt)

**Comment by saxbophone** [comment]
I was just thinking about this myself, +1 on this. Nice file @OmniBlade

**Comment by tpoechtrager** [comment]
Do you guys have a list of projects I should use for testing?

**Comment by OmniBlade** [comment]
Do you just need a few projects that use cmake? Off the top of my head OpenRCT2 uses cmake.

**Comment by grimmy** [comment]
Here's what I'm using.  I'm using it with one of the osxcross docker images, but something is broke where everything in macports/pkgs/opt/local/bin doesn't have the execute bit set.

```set(CMAKE_SYSTEM_NAME Darwin)

set(ENV{PKG_CONFIG_PATH} /opt/osxcross/target/macports/pkgs/opt/local/lib/pkgconfig)

set(CMAKE_C_COMPILER x86_64-apple-darwin12-clang)
set(CMAKE_CXX_COMPILER x86_64-apple-darwin12-clang++)
set(CMAKE_FIND_ROOT_PATH /opt/osxcross/target/macports/pkgs/opt/local/)

set(CMAKE_OSX_SYSROOT /opt/osxcross/target/SDK/MacOSX10.8.sdk/)
```

**Comment by tpoechtrager** [comment]
>  but something is broke where everything in macports/pkgs/opt/local/bin doesn't have the execute bit set.

Should be fixed.

**Comment by grimmy** [comment]
The execute bit thing is actually fine.  I was being dumb due to being tired... I can't run the executables anyways since they're for OSX and I'm on Linux ;)

**Comment by saxbophone** [comment]
I tried this with building [SFML](https://github.com/SFML/SFML) this evening (a few hours ago). SFML uses CMake, and the build appeared to work, based on setting variables mentioned in this thread and a few other places I had to dig around for them.

Here's the variables I had to add to the CMake script to get it to work

> Note, I haven't yet tested the generated `.framework` packages on an _actual_ OSX system yet, so it may be no good! However, that it compiled and linked successfully is a pretty good sign I think :slightly_smiling_face:

```cmake
set(CMAKE_SYSTEM_NAME Darwin)
set(TOOLCHAIN_PREFIX x86_64-apple-darwin15)

# cross compilers to use for C and C++
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-clang)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-clang++)

# target environment on the build host system
#   set 1st to dir with the cross compiler's C/C++ headers/libs
set(CMAKE_FIND_ROOT_PATH "/home/joshua/Dev_Build/osxcross/target/SDK/MacOSX10.11.sdk/usr/include/")

# modify default behavior of FIND_XXX() commands to
# search for headers/libs in the target environment and
# search for programs in the build host environment
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)

set(CMAKE_FIND_ROOT_PATH "/home/joshua/Dev_Build/osxcross/target/macports/pkgs/opt/local/")

set(CMAKE_OSX_SYSROOT "/home/joshua/Dev_Build/osxcross/target/SDK/MacOSX10.11.sdk/")

set(CMAKE_INSTALL_FRAMEWORK_PREFIX "/home/joshua/Dev_Build/osxcross/target/SDK/MacOSX10.11.sdk/System/Library/Frameworks")

# this one is commented out as it did not appear to work when set in the script
# however, it does work when given on the command-line
# without it, SFML tries to install some of it's files to '/usr/local/share'
# set(CMAKE_INSTALL_PREFIX "/home/joshua/Dev_Build/osxcross/target/SDK/MacOSX10.11.sdk/usr/")

# this is a SFML-specific variable telling it to build for Mac OSX
# as I guess it wouldn't otherwise know it was to do so when on Linux
set(SFML_OS_MACOSX BOOL TRUE)
# these are required to get the binaries linked correctly, and appears to be a common OSX occurrence 
set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG "-Wl,-rpath,")
set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP ":")
# more linking variables
set(CMAKE_INSTALL_NAME_DIR "@rpath")
set(CMAKE_INSTALL_RPATH ...)
```

_of course, these are the specific paths on my system which will need amending before they're useful to anyone else_

**Comment by saxbophone** [comment]
Sorry for the extra noise, but I think people may be interested to know that I have this in a fork of SFML currently, as a sample for convenience at https://github.com/saxbophone/SFML

**Comment by tpoechtrager** [comment]
https://github.com/tpoechtrager/osxcross/pull/148
