### ISSUE TITLE
SpringRts cmake gcc

### ISSUE THREAD

**Issue by TurBoss** [tpoechtrager/osxcross#83]
Hi

I'm trying to build the springrts project http://springrts.com with osxcross
some users where able to build natively on mac : https://springrts.com/phpbb/viewtopic.php?f=65&t=32970

using xcode 7.3.1 from a mac
and compiling for 10.11

but this project requires gcc to sync online

this is the far i can go with my test settings :p

cmake parameters: http://paste.springfiles.com/view/7c810db0
cmake + make output: http://paste.springfiles.com/view/5bca413f

this will be used to setup a buildbot slave for the project

project can be found here : https://github.com/spring/

edit: add git info for the project 
```
git clone https://github.com/spring/spring.git
git submodule init && git submodule update
```
edit2:
forgot to mention my system xD

i'm on ubuntu 16.04

thx

**Comment by tpoechtrager** [comment]
Might be some incompatibility between Clang an GCC. I do not recommend using `g++-libc++` anyway. The better way would be to fix your code to compile Clang.

**Comment by TurBoss** [comment]
hi
Ive remove g++-libc++ in favour of g++ 

but i'm geting

Undefined symbols for architecture x86_64:
ld: symbol(s) not found for architecture x86_64

http://paste.springfiles.com/view/075a2c58#L62

thx

**Comment by tpoechtrager** [comment]
That can't work because of the different C++ standard libraries. You must use `clang++ -mmacosx-version-min=10.9` instead of `g++`.

**Comment by TurBoss** [comment]
ok thx
