### ISSUE TITLE
Compile error on Cygwin

### ISSUE THREAD

**Issue by jay3d** [tpoechtrager/osxcross#87]
I'm always getting a compile error with build.sh under Cygwin:

    libtool: compile:  g++ -DPACKAGE_NAME=\"cctools\" -DPACKAGE_TARNAME=\"cctools\" -DPACKAGE_VERSION=\"886\" "-DPACKAGE_STRING=\"cctools 886\"" -DPACKAGE_BUGREPORT=\"t.poechtrager@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DEMULATED_HOST_CPU_TYPE=16777223 -DEMULATED_HOST_CPU_SUBTYPE=3 -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -DHAVE_UUID_UUID_H=1 -I. -D__DARWIN_UNIX03 -Wno-attributes -Wall -Wno-format -Wno-enum-compare -Wno-unused-result -Wno-unused-variable -Wno-unused-but-set-variable -Wno-deprecated -Wno-deprecated-declarations -Wno-char-subscripts -Wno-strict-aliasing -Wno-shift-negative-value -D__LITTLE_ENDIAN__=1 -I../../../../include -I../../../../include/foreign -I../../../../ld64/src/abstraction -I../../../../ld64/src/ld -I../../../../ld64/src/3rd -I../../../../ld64/src -O3 -std=c++0x -isystem /usr/local/include -isystem /usr/pkg/include -D__private_extern__= -D__LARGE64_FILES -fno-PIC -c archive_file.cpp  -DDLL_EXPORT -DPIC -o .libs/libParsers_la-archive_file.o
    In file included from macho_relocatable_file.h:29:0,
                    from archive_file.cpp:41:
    ../../../../ld64/src/ld/Options.h: In constructor ‘Options::FileInfo::FileInfo(const char*)’:
    ../../../../ld64/src/ld/Options.h:166:56: error: ‘strdup’ was not declared in this scope
            FileInfo(const char *_path) : path(strdup(_path)), fileLen(0), modTime(0), options(), fromFileList(false) {};
                                                            ^
    archive_file.cpp: In constructor ‘archive::File<A>::File(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&)’:
    archive_file.cpp:278:32: error: there are no arguments to ‘strdup’ that depend on a template parameter, so a declaration of ‘strdup’ must be available [-fpermissive]
      : ld::archive::File(strdup(pth), modTime, ord),
                                    ^
    archive_file.cpp:278:32: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
    archive_file.cpp: In instantiation of ‘archive::File<A>::File(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&) [with A = x86_64; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]’:
    archive_file.cpp:67:33:   required from ‘static archive::File<A>* archive::Parser<A>::parse(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&) [with A = x86_64; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]’
    archive_file.cpp:598:37:   required from here
    archive_file.cpp:278:28: error: ‘strdup’ was not declared in this scope
      : ld::archive::File(strdup(pth), modTime, ord),
                                ^
    archive_file.cpp: In instantiation of ‘archive::File<A>::File(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&) [with A = x86; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]’:
    archive_file.cpp:67:33:   required from ‘static archive::File<A>* archive::Parser<A>::parse(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&) [with A = x86; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]’
    archive_file.cpp:604:34:   required from here
    archive_file.cpp:278:28: error: ‘strdup’ was not declared in this scope
    archive_file.cpp: In instantiation of ‘archive::File<A>::File(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&) [with A = arm; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]’:
    archive_file.cpp:67:33:   required from ‘static archive::File<A>* archive::Parser<A>::parse(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&) [with A = arm; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]’
    archive_file.cpp:610:34:   required from here
    archive_file.cpp:278:28: error: ‘strdup’ was not declared in this scope
    archive_file.cpp: In instantiation of ‘archive::File<A>::File(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&) [with A = arm64; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]’:
    archive_file.cpp:67:33:   required from ‘static archive::File<A>* archive::Parser<A>::parse(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const archive::ParserOptions&) [with A = arm64; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]’
    archive_file.cpp:616:36:   required from here
    archive_file.cpp:278:28: error: ‘strdup’ was not declared in this scope
    archive_file.cpp: In instantiation of ‘archive::File<A>::MemberState& archive::File<A>::makeObjectFileForMember(const archive::File<A>::Entry*) const [with A = arm64]’:
    archive_file.cpp:441:56:   required from ‘bool archive::File<A>::forEachAtom(ld::File::AtomHandler&) const [with A = arm64]’
    archive_file.cpp:625:2:   required from here
    archive_file.cpp:378:29: error: ‘strdup’ was not declared in this scope
      const char* mPath = strdup(memberPath);
                                ^
    archive_file.cpp: In instantiation of ‘archive::File<A>::MemberState& archive::File<A>::makeObjectFileForMember(const archive::File<A>::Entry*) const [with A = arm]’:
    archive_file.cpp:441:56:   required from ‘bool archive::File<A>::forEachAtom(ld::File::AtomHandler&) const [with A = arm]’
    archive_file.cpp:625:2:   required from here
    archive_file.cpp:378:29: error: ‘strdup’ was not declared in this scope
    archive_file.cpp: In instantiation of ‘archive::File<A>::MemberState& archive::File<A>::makeObjectFileForMember(const archive::File<A>::Entry*) const [with A = x86_64]’:
    archive_file.cpp:441:56:   required from ‘bool archive::File<A>::forEachAtom(ld::File::AtomHandler&) const [with A = x86_64]’
    archive_file.cpp:625:2:   required from here
    archive_file.cpp:378:29: error: ‘strdup’ was not declared in this scope
    archive_file.cpp: In instantiation of ‘archive::File<A>::MemberState& archive::File<A>::makeObjectFileForMember(const archive::File<A>::Entry*) const [with A = x86]’:
    archive_file.cpp:441:56:   required from ‘bool archive::File<A>::forEachAtom(ld::File::AtomHandler&) const [with A = x86]’
    archive_file.cpp:625:2:   required from here
    archive_file.cpp:378:29: error: ‘strdup’ was not declared in this scope
    At global scope:
    cc1plus: warning: unrecognized command line option ‘-Wno-shift-negative-value’
    make[4]: *** [Makefile:425: libParsers_la-archive_file.lo] Error 1
    make[4]: Leaving directory '/cygdrive/d/Develop/Repositories/osxcross/build/cctools-886-ld64-264.3.102_db1f8d9/cctools/ld64/src/ld/parsers'
    make[3]: *** [Makefile:631: all-recursive] Error 1
    make[3]: Leaving directory '/cygdrive/d/Develop/Repositories/osxcross/build/cctools-886-ld64-264.3.102_db1f8d9/cctools/ld64/src/ld'
    make[2]: *** [Makefile:378: all-recursive] Error 1
    make[2]: Leaving directory '/cygdrive/d/Develop/Repositories/osxcross/build/cctools-886-ld64-264.3.102_db1f8d9/cctools/ld64/src'
    make[1]: *** [Makefile:379: all-recursive] Error 1
    make[1]: Leaving directory '/cygdrive/d/Develop/Repositories/osxcross/build/cctools-886-ld64-264.3.102_db1f8d9/cctools/ld64'
    make: *** [Makefile:411: all-recursive] Error 1

Any idea how to solve this?

Thanks!

**Comment by tpoechtrager** [comment]
There might be some preprocesser defintion missing but I can't figure out which.

**Comment by jay3d** [comment]
I replaced -std=c++0x with -std=gnu++0x

Something solved but some new introduced:

`libtool: compile:  g++ -DPACKAGE_NAME=\"cctools\" -DPACKAGE_TARNAME=\"cctools\" -DPACKAGE_VERSION=\"886\" "-DPACKAGE_STRING=\"cctools 886\"" -DPACKAGE_BUGREPORT=\"t.poechtrager@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DEMULATED_HOST_CPU_TYPE=16777223 -DEMULATED_HOST_CPU_SUBTYPE=3 -D__STDC_LIMIT_MACROS=1 -D__STDC_CONSTANT_MACROS=1 -DHAVE_UUID_UUID_H=1 -I. -D__DARWIN_UNIX03 -Wno-attributes -Wall -Wno-format -Wno-enum-compare -Wno-unused-result -Wno-unused-variable -Wno-unused-but-set-variable -Wno-deprecated -Wno-deprecated-declarations -Wno-char-subscripts -Wno-strict-aliasing -Wno-shift-negative-value -D__LITTLE_ENDIAN__=1 -I../../../../include -I../../../../include/foreign -I../../../../ld64/src/abstraction -I../../../../ld64/src/ld -I../../../../ld64/src/3rd -I../../../../ld64/src -O3 -std=gnu++0x -isystem /usr/local/include -isystem /usr/pkg/include -D__private_extern__= -D__LARGE64_FILES -fno-PIC -c macho_relocatable_file.cpp  -DDLL_EXPORT -DPIC -o .libs/libParsers_la-macho_relocatable_file.o
macho_relocatable_file.cpp: In member function 'void mach_o::relocatable::Parser<A>::parseDebugInfo()':
macho_relocatable_file.cpp:3608:79: error: there are no arguments to 'asprintf' that depend on a template parameter, so a declaration of 'asprintf' must be available [-fpermissive]
   asprintf((char**)&(_file->_dwarfTranslationUnitPath), "%s/%s", tuDir, tuName);
                                                                               ^
macho_relocatable_file.cpp:3608:79: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
macho_relocatable_file.cpp: In instantiation of 'void mach_o::relocatable::Parser<A>::parseDebugInfo() [with A = x86_64]':
macho_relocatable_file.cpp:1962:2:   required from 'ld::relocatable::File* mach_o::relocatable::Parser<A>::parse(const mach_o::relocatable::ParserOptions&) [with A = x86_64]'
macho_relocatable_file.cpp:992:36:   required from 'static ld::relocatable::File* mach_o::relocatable::Parser<A>::parse(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const mach_o::relocatable::ParserOptions&) [with A = x86_64; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]'
macho_relocatable_file.cpp:7761:108:   required from here
macho_relocatable_file.cpp:3608:11: error: 'asprintf' was not declared in this scope
   asprintf((char**)&(_file->_dwarfTranslationUnitPath), "%s/%s", tuDir, tuName);
           ^
In file included from /usr/include/cygwin/in.h:263:0,
                 from /usr/include/netinet/in.h:12,
                 from /usr/include/arpa/inet.h:12,
                 from ../code-sign-blobs/endian.h:35,
                 from ../code-sign-blobs/blob.h:45,
                 from ../code-sign-blobs/superblob.h:7,
                 from macho_dylib_file.cpp:45:
../code-sign-blobs/endian.h: In function 'long unsigned int Security::h2n(long unsigned int)':
../code-sign-blobs/endian.h:53:59: error: '__htonl' was not declared in this scope
 static inline unsigned long h2n(unsigned long v) { return htonl(v); }
                                                           ^
../code-sign-blobs/endian.h: In function 'long unsigned int Security::n2h(long unsigned int)':
../code-sign-blobs/endian.h:54:59: error: '__ntohl' was not declared in this scope
 static inline unsigned long n2h(unsigned long v) { return ntohl(v); }
                                                           ^
../code-sign-blobs/endian.h: In function 'long int Security::h2n(long int)':
../code-sign-blobs/endian.h:56:56: error: '__htonl' was not declared in this scope
 static inline signed long h2n(signed long v)  { return htonl(v); }
                                                        ^
../code-sign-blobs/endian.h: In function 'long int Security::n2h(long int)':
../code-sign-blobs/endian.h:57:56: error: '__ntohl' was not declared in this scope
 static inline signed long n2h(signed long v)  { return ntohl(v); }
                                                        ^
../code-sign-blobs/endian.h: In function 'unsigned int Security::h2n(unsigned int)':
../code-sign-blobs/endian.h:68:58: error: '__htonl' was not declared in this scope
 static inline unsigned int h2n(unsigned int v)  { return htonl(v); }
                                                          ^
../code-sign-blobs/endian.h: In function 'unsigned int Security::n2h(unsigned int)':
../code-sign-blobs/endian.h:69:58: error: '__ntohl' was not declared in this scope
 static inline unsigned int n2h(unsigned int v)  { return ntohl(v); }
                                                          ^
../code-sign-blobs/endian.h: In function 'int Security::h2n(int)':
../code-sign-blobs/endian.h:71:50: error: '__htonl' was not declared in this scope
 static inline signed int h2n(int v)     { return htonl(v); }
                                                  ^
../code-sign-blobs/endian.h: In function 'int Security::n2h(int)':
../code-sign-blobs/endian.h:72:50: error: '__ntohl' was not declared in this scope
 static inline signed int n2h(int v)     { return ntohl(v); }
                                                  ^
../code-sign-blobs/endian.h: In function 'short unsigned int Security::h2n(short unsigned int)':
../code-sign-blobs/endian.h:75:61: error: '__htons' was not declared in this scope
 static inline unsigned short h2n(unsigned short v) { return htons(v); }
                                                             ^
../code-sign-blobs/endian.h: In function 'short unsigned int Security::n2h(short unsigned int)':
../code-sign-blobs/endian.h:76:61: error: '__ntohs' was not declared in this scope
 static inline unsigned short n2h(unsigned short v) { return ntohs(v); }
                                                             ^
../code-sign-blobs/endian.h: In function 'short int Security::h2n(short int)':
../code-sign-blobs/endian.h:78:58: error: '__htons' was not declared in this scope
 static inline signed short h2n(signed short v)  { return htons(v); }
                                                          ^
../code-sign-blobs/endian.h: In function 'short int Security::n2h(short int)':
../code-sign-blobs/endian.h:79:58: error: '__ntohs' was not declared in this scope
 static inline signed short n2h(signed short v)  { return ntohs(v); }
                                                          ^
macho_relocatable_file.cpp: In instantiation of 'void mach_o::relocatable::Parser<A>::parseDebugInfo() [with A = x86]':
macho_relocatable_file.cpp:1962:2:   required from 'ld::relocatable::File* mach_o::relocatable::Parser<A>::parse(const mach_o::relocatable::ParserOptions&) [with A = x86]'
macho_relocatable_file.cpp:992:36:   required from 'static ld::relocatable::File* mach_o::relocatable::Parser<A>::parse(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const mach_o::relocatable::ParserOptions&) [with A = x86; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]'
macho_relocatable_file.cpp:7767:105:   required from here
macho_relocatable_file.cpp:3608:11: error: 'asprintf' was not declared in this scope
macho_relocatable_file.cpp: In instantiation of 'void mach_o::relocatable::Parser<A>::parseDebugInfo() [with A = arm]':
macho_relocatable_file.cpp:1962:2:   required from 'ld::relocatable::File* mach_o::relocatable::Parser<A>::parse(const mach_o::relocatable::ParserOptions&) [with A = arm]'
macho_relocatable_file.cpp:992:36:   required from 'static ld::relocatable::File* mach_o::relocatable::Parser<A>::parse(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const mach_o::relocatable::ParserOptions&) [with A = arm; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]'
macho_relocatable_file.cpp:7773:105:   required from here
macho_relocatable_file.cpp:3608:11: error: 'asprintf' was not declared in this scope
macho_relocatable_file.cpp: In instantiation of 'void mach_o::relocatable::Parser<A>::parseDebugInfo() [with A = arm64]':
macho_relocatable_file.cpp:1962:2:   required from 'ld::relocatable::File* mach_o::relocatable::Parser<A>::parse(const mach_o::relocatable::ParserOptions&) [with A = arm64]'
macho_relocatable_file.cpp:992:36:   required from 'static ld::relocatable::File* mach_o::relocatable::Parser<A>::parse(const uint8_t*, uint64_t, const char*, time_t, ld::File::Ordinal, const mach_o::relocatable::ParserOptions&) [with A = arm64; uint8_t = unsigned char; uint64_t = long long unsigned int; time_t = long int]'
macho_relocatable_file.cpp:7779:107:   required from here
macho_relocatable_file.cpp:3608:11: error: 'asprintf' was not declared in this scope
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
make[4]: *** [Makefile:431: libParsers_la-macho_dylib_file.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-shift-negative-value'
make[4]: *** [Makefile:434: libParsers_la-macho_relocatable_file.lo] Error 1
make[4]: Leaving directory '/cygdrive/d/Develop/Repositories/osxcross/build/cctools-886-ld64-264.3.102_db1f8d9/cctools/ld64/src/ld/parsers'
make[3]: *** [Makefile:631: all-recursive] Error 1
make[3]: Leaving directory '/cygdrive/d/Develop/Repositories/osxcross/build/cctools-886-ld64-264.3.102_db1f8d9/cctools/ld64/src/ld'
make[2]: *** [Makefile:378: all-recursive] Error 1
make[2]: Leaving directory '/cygdrive/d/Develop/Repositories/osxcross/build/cctools-886-ld64-264.3.102_db1f8d9/cctools/ld64/src'
make[1]: *** [Makefile:379: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/d/Develop/Repositories/osxcross/build/cctools-886-ld64-264.3.102_db1f8d9/cctools/ld64'
make: *** [Makefile:411: all-recursive] Error 1

exiting with abnormal exit code (2)
run 'OCDEBUG=1 ./build.sh' to enable debug messages
removing stale locks...
if it is happening the first time, then just re-run the script`

Getting close ;)

**Comment by tpoechtrager** [comment]
Fixed.
