### ISSUE TITLE
cygLTO.dll doesn't exist anywhere

### ISSUE THREAD

**Issue by jay3d** [tpoechtrager/osxcross#88]
I followed the instructions for Cygwin installation, installed all required packages, but couldn't find cygLTO.dll anywhere.

Wonder if there's a required version of Cygwin? I'm using latest one.

**Comment by tpoechtrager** [comment]
Could be a packaging issue of Cygwin.

Run this script to generate the missing cygLTO dll:

    #!/bin/bash

    LLVM_CONFIG="llvm-config"

    CXXFLAGS="$($LLVM_CONFIG --cxxflags) -fno-PIC"
    LDFLAGS="$($LLVM_CONFIG --cxxflags) -Wl,-s"
    INCDIR=$($LLVM_CONFIG --includedir)
    LIBDIR=$($LLVM_CONFIG --libdir)
    LIBS=$($LLVM_CONFIG --libs all)
    SYSLIBS="$($LLVM_CONFIG --system-libs) -ledit -lffi"

    VERSION=$($LLVM_CONFIG --version | awk -F \. {'print $1$2'} | sed 's/svn//g')

    set -e
    TMP=$(mktemp -d)
    set +e

    pushd $TMP &>/dev/null
    wget https://raw.githubusercontent.com/llvm-mirror/llvm/release_$VERSION/tools/lto/lto.cpp
    wget https://raw.githubusercontent.com/llvm-mirror/llvm/release_$VERSION/tools/lto/LTODisassembler.cpp
    wget https://raw.githubusercontent.com/llvm-mirror/llvm/release_$VERSION/tools/lto/lto.exports

    echo "{" > lto.ls
    echo "  global:" >> lto.ls
    while read p; do
      echo "   $p;" >> lto.ls
    done < lto.exports
    echo "   LLVM*;" >> lto.ls
    echo "  local: *;" >> lto.ls
    echo "};" >> lto.ls
    popd &>/dev/null

    set -x

    g++ -shared \
      -L$LIBDIR -I$INCDIR $CXXFLAGS $LDFLAGS -Wl,--whole-archive $LIBS -Wl,--no-whole-archive \
      $SYSLIBS $TMP/lto.cpp $TMP/LTODisassembler.cpp -Wl,-version-script,$TMP/lto.ls \
      -o /bin/cygLTO.dll -Wl,--out-implib,/lib/libLTO.dll.a
    
    rm -rf $TMP
