### ISSUE TITLE
ld: library not found for -lcrt1.10.5.o

### ISSUE THREAD

**Issue by bronf** [tpoechtrager/osxcross#90]
Hi,

I tried to install the clang cross-compiler on cygwin with SDK 10.7 (but same type of error with 10.6).
At the end of the build process, I get this error:
testing o32-clang ... + o32-clang /cygdrive/c/Softs/build/osxcross11/oclang/test.c -O2 -Wall -o test
osxcross: debug: --> o32-clang /cygdrive/c/Softs/build/osxcross11/oclang/test.c -O2 -Wall -o test~
osxcross: debug: <-- /usr/bin/clang-3.8.exe (clang) -target i386-apple-darwin11 -mlinker-version=264.3.102 -isystem /usr/bin/../lib/clang/3.8.1/include -isysroot /cygdrive/c/Softs/build/osxcross11/target/bin/../SDK/MacOSX10.7.sdk -cxx-isystem /cygdrive/c/S>
osxcross: debug: === time spent in wrapper: 3 ms
ld: library not found for -lcrt1.10.5.o
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)

And when I try to compile a program, I get the same "ld: library not found" error (I think sometimes it's 10.6 instead of 10.5).

Any idea why?

I got the SDK from [Link removed]

**Comment by tpoechtrager** [comment]
Looks like a broken SDK to me.

Download Xcode 7.2.1 from [here](https://developer.apple.com/download/more/?name=Xcode%207.2.1) and use `./tools/gen_sdk_package_p7zip.sh` to generate a properly working SDK.
