### ISSUE TITLE
gen_cyglto_dll.sh dont work on cygwin64

### ISSUE THREAD

**Issue by msink** [tpoechtrager/osxcross#91]
```
g++ -shared -L/usr/lib -I/usr/include -I/usr/include -ggdb -pipe -fdebug-prefix-map=/usr/src/ports/llvm/llvm-3.8.1-1.x86_64/build=/usr/src/debug/llvm-3.8.1-1 -fdebug-prefix-map=/usr/src/ports/llvm/llvm-3.8.1-1.x86_64/src/llvm-3.8.1.src=/usr/src/debug/llvm-3.8.1-1 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -std=gnu++11 -O2 -g -DNDEBUG -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-PIC -I/usr/include -ggdb -pipe -fdebug-prefix-map=/usr/src/ports/llvm/llvm-3.8.1-1.x86_64/build=/usr/src/debug/llvm-3.8.1-1 -fdebug-prefix-map=/usr/src/ports/llvm/llvm-3.8.1-1.x86_64/src/llvm-3.8.1.src=/usr/src/debug/llvm-3.8.1-1 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -std=gnu++11 -O2 -g -DNDEBUG -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wl,-s -Wl,--whole-archive -lLLVMLTO -lLLVMObjCARCOpts -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMMIRParser -lLLVMTableGen -lLLVMOrcJIT -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUUtils -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLibDriver -lLLVMOption -lLLVMLineEditor -lLLVMPasses -lLLVMipo -lLLVMVectorize -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMDebugInfoCodeView -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMInstrumentation -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMTransformUtils -lLLVMMC -lLLVMBitWriter -lLLVMBitReader -lLLVMAnalysis -lLLVMCore -lLLVMSupport -Wl,--no-whole-archive -lrt -ldl -lcurses -lpthread -lz -lm -ledit -lffi /tmp/tmp.LQDOxfIO6W/lto.cpp /tmp/tmp.LQDOxfIO6W/LTODisassembler.cpp -Wl,-version-script,/tmp/tmp.LQDOxfIO6W/cyglto.exports -o /bin/cygLTO.dll -Wl,--out-implib,/lib/libLTO.dll.a
/tmp/tmp.LQDOxfIO6W/cctJs7eP.o: In function `lto_module_create_from_fd_at_offset':
/tmp/tmp.LQDOxfIO6W/lto.cpp:220: undefined reference to `llvm::LTOModule::createFromOpenFileSlice(llvm::LLVMContext&, int, char const*, unsigned long, long, llvm::TargetOptions)'
/tmp/tmp.LQDOxfIO6W/lto.cpp:220:(.text+0x2bba): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `llvm::LTOModule::createFromOpenFileSlice(llvm::LLVMContext&, int, char const*, unsigned long, long, llvm::TargetOptions)'
collect2: error: ld returned 1 exit status
```

in LTOModule.cpp:
llvm::LTOModule::createFromOpenFileSlice(LLVMContext &Context, int fd, const char *path, size_t map_size, off_t offset, TargetOptions options)

off_t is 'long long' on x86_64

**Comment by msink** [comment]
Build works fine if LTO disabled:
`DISABLE_LTO_SUPPORT=1 ./build.sh`
But why this option is not documented?

Another question: why generated symlinks in target/bin/* are filename only, not filename.exe ?
For example, "o32-clang", not "o32-clang.exe"
This way I can compile only from cygwin terminal, not from regular windows command line.

**Comment by tpoechtrager** [comment]
> ```
g++ -shared -L/usr/lib -I/usr/include -I/usr/include -ggdb -pipe -fdebug-prefix-map=/usr/src/ports/llvm/llvm-3.8.1-1.x86_64/build=/usr/src/debug/llvm-3.8.1-1 -fdebug-prefix-map=/usr/src/ports/llvm/llvm-3.8.1-1.x86_64/src/llvm-3.8.1.src=/usr/src/debug/llvm-3.8.1-1 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -std=gnu++11 -O2 -g -DNDEBUG -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-PIC -I/usr/include -ggdb -pipe -fdebug-prefix-map=/usr/src/ports/llvm/llvm-3.8.1-1.x86_64/build=/usr/src/debug/llvm-3.8.1-1 -fdebug-prefix-map=/usr/src/ports/llvm/llvm-3.8.1-1.x86_64/src/llvm-3.8.1.src=/usr/src/debug/llvm-3.8.1-1 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -std=gnu++11 -O2 -g -DNDEBUG -fno-exceptions -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wl,-s -Wl,--whole-archive -lLLVMLTO -lLLVMObjCARCOpts -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMMIRParser -lLLVMTableGen -lLLVMOrcJIT -lLLVMCppBackendCodeGen -lLLVMCppBackendInfo -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUUtils -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLibDriver -lLLVMOption -lLLVMLineEditor -lLLVMPasses -lLLVMipo -lLLVMVectorize -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMDebugInfoCodeView -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMScalarOpts -lLLVMInstCombine -lLLVMInstrumentation -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMTransformUtils -lLLVMMC -lLLVMBitWriter -lLLVMBitReader -lLLVMAnalysis -lLLVMCore -lLLVMSupport -Wl,--no-whole-archive -lrt -ldl -lcurses -lpthread -lz -lm -ledit -lffi /tmp/tmp.LQDOxfIO6W/lto.cpp /tmp/tmp.LQDOxfIO6W/LTODisassembler.cpp -Wl,-version-script,/tmp/tmp.LQDOxfIO6W/cyglto.exports -o /bin/cygLTO.dll -Wl,--out-implib,/lib/libLTO.dll.a
/tmp/tmp.LQDOxfIO6W/cctJs7eP.o: In function `lto_module_create_from_fd_at_offset':
/tmp/tmp.LQDOxfIO6W/lto.cpp:220: undefined reference to `llvm::LTOModule::createFromOpenFileSlice(llvm::LLVMContext&, int, char const*, unsigned long, long, llvm::TargetOptions)'
/tmp/tmp.LQDOxfIO6W/lto.cpp:220:(.text+0x2bba): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `llvm::LTOModule::createFromOpenFileSlice(llvm::LLVMContext&, int, char const*, unsigned long, long, llvm::TargetOptions)'
collect2: error: ld returned 1 exit status
```

> in LTOModule.cpp:
llvm::LTOModule::createFromOpenFileSlice(LLVMContext &Context, int fd, const char *path, size_t map_size, off_t offset, TargetOptions options)

> off_t is 'long long' on x86_64


Please report this issue to the Cygwin people.

> Build works fine if LTO disabled:
> `DISABLE_LTO_SUPPORT=1 ./build.sh`
> But why this option is not documented?

`DISABLE_LTO_SUPPORT=1` shouldn't be required. Remove the generated import library: `rm /lib/libLTO.dll.a`.

> Another question: why generated symlinks in target/bin/* are filename only, not filename.exe ?
> For example, "o32-clang", not "o32-clang.exe"
> This way I can compile only from cygwin terminal, not from regular windows command line.

Windows' "cmd" isn't supported and never will be.

**Comment by msink** [comment]
> Please report this issue to the Cygwin people.

Maybe, buf for me LTO is not critical, I just could not compile afer that failed `gen_cyglto_dll`

> DISABLE_LTO_SUPPORT=1 shouldn't be required. Remove the generated import library: rm /lib/libLTO.dll.a.

Yes, this fixed build too

> Windows' "cmd" isn't supported and never will be. This isn't a native Windows project.

The only missed piece is `.exe` extension, if I copy that symlink to `o32-clang.exe` - everything works from `cmd`.
At least I now can compile helloworld.c for mac too:

```
set PATH=f:\cygwin64\bin;f:\cygwin64\opt\osxcross\target\bin\;%PATH%
i686-w64-mingw32-gcc hello.c -o hello-win32.exe
x86_64-w64-mingw32-gcc hello.c -o hello-win64.exe
i686-pc-linux-gnu-gcc  hello.c -o hello-lin32
x86_64-pc-linux-gnu-gcc hello.c -o hello-lin64
armv7hl-unknown-linux-gnueabi-gcc hello.c -o hello-arm32
aarch64-unknown-linux-gnu-gcc hello.c -o hello-arm64
o64-clang hello.c -o hello-mac
```

**Comment by msink** [comment]
Thanks, 98a7b55 fixed issue with `.exe` extension, even better - now it don't require Administrator rights for building, and works fine from cyswin's bash and from windows's cmd.
Thanks!

You can close this, or leave open until issue with LTO will be fixed on cygwin's side.

**Comment by tpoechtrager** [comment]
Should be fixed as well.
