### ISSUE TITLE
Using osxcross from outside cygwin

### ISSUE THREAD

**Issue by LongDirtyAnimAlf** [tpoechtrager/osxcross#94]
Hi,

I am trying to use osxcross with the Free Pascal Compiler, to cross towards Mac.
This means that I need to use the bin-tools from ourside of cygwin environment.

This does not work (naturally ? / my mistake ?).

If my mistake, any help would be appreciated.
If not, than the addition of a search-path for all internal cygwin path could solve this issue.
E.g. inside of
Target::setupGCCLibs(Arch arch)
Target::setup()
TRYDIR2("/../lib/clang/x86_64-pc-cygwin"); 

ps : the setting OSXCROSS_SDKROOT=c:\cygwin\home\someuser\osxcross\target\SDK\MacOSX10.9.sdk gives a target error when using from outside of cygwin.

**Comment by msink** [comment]
For me - it works perfectly from windows command promt

Building of `ocxcross` itself works only from cygwin bash, of course:
```
git clone https://github.com/tpoechtrager/osxcross.git /opt/osxcross
cp MacOSX10.10.sdk.tar.xz /opt/osxcross/tarballs
/opt/osxcross/build.sh
```

But after that, it works outside cygwin, you only need cygwin and osxcross in PATH:
```
set PATH=f:\cygwin64\bin;f:\cygwin64\opt\osxcross\target\bin\;%PATH%
x86_64-apple-darwin14-clang hello.c -o hello-mac
```

**Comment by LongDirtyAnimAlf** [comment]
You are 100% right.
Thanks for your help !
