### ISSUE TITLE
Option -filelist does not work in Cygwin

### ISSUE THREAD

**Issue by LongDirtyAnimAlf** [tpoechtrager/osxcross#97]
Hello again,
I am still trying to use osxcross to build from the Free Pascal Compiler.
With some success.

Problem:
At one stage in the build-process, many files must be linked.
Too many for the Windows command line (ld c:\a\b\c\d\e.o c:\a\b\c\d\e\f.o many more ...)
Longs paths, many files. Over the win-limit.
So, I try to use -filelist. With a single file in it: c:\a\b\c\d\e.o
But ld gives error: file c:\a\b\c\d\e.o not found. But it is there !

For now, this is the only (fatal) error for successfull use of osxcross with FPC.
Thanks for you help.

**Comment by tpoechtrager** [comment]
Are you sure the correct path is passed to the linker?

`c:\a\b\c\d\e.o` might evaluate to `c:abcde.o`. Try `c:\\a\\b\\c\\d\\e.o` or `/cygdrive/drive_c/a/b/c/d/e.o`.

**Comment by LongDirtyAnimAlf** [comment]
Tried any combination ... no luck.

When I look in the sources, I see this:
findFile(path, {".tbd"}, result)
So, only if their is a corresponding tbd file, this file is added.
I just checked (only backslash works):
c:/a/b/c/d/e.o i added if c:/a/b/c/d/e.tbd is found.

Due to this fact, I do not think that it i possible to use plain files inside a filelist.
Which woul be very unfortunate.

**Comment by LongDirtyAnimAlf** [comment]
With this awfull path, it works:

--- ld64/src/ld/OptionsOrig.cpp	Fri Nov 18 21:17:04 2016
+++ ld64/src/ld/Options.cpp	Fri Nov 18 21:16:45 2016
@@ -897,6 +897,12 @@
 			return result;
 	}
 
+	bool found = findFile(path, {".o"}, result);
+	if ( found ) {
+		return result;
+	}
+
+
 	// not found
 	throwf("file not found: %s", path.c_str());
 }

**Comment by LongDirtyAnimAlf** [comment]
After much testing, here a proposal for a final change in Options.cpp for ld64
Add:
```
static std::string get_extension(const std::string &path)
{
	auto result = path;
	auto lastSlashIdx = result.find_last_of('/');
	auto lastDotIdx = result.find_last_of('.');
	if (lastDotIdx != std::string::npos && lastDotIdx > lastSlashIdx)
		result.erase(0,lastDotIdx);
	return result;
}

```
And, inside Options::FileInfo Options::findFile(const std::string &path) const.
Before throwf("file not found: %s", path.c_str());

```
	auto Extension = get_extension(path);
	// remove line endings
	while ( Extension.find ("\n") != std::string::npos )
	{
	        Extension.erase ( Extension.find ("\n"), 1 );
	}
	while ( Extension.find ("\r") != std::string::npos )
	{
	        Extension.erase ( Extension.find ("\r"), 1 );
	}
	found = findFile(path, {Extension}, result);
	if ( found ) {
		return result;
	}

```
With these changes, FPC can use your tools !

**Comment by tpoechtrager** [comment]
Cygwin is no longer supported by OSXCross.
