### ISSUE TITLE
build.sh fails with "symbol … version GLIBCXX_3.4.21 not defined in file libstdc++.so.6"

### ISSUE THREAD

**Issue by tjanson** [tpoechtrager/osxcross#98]
I tried to install OSXCross on an Ubuntu 14.04 machine using an El Capitan tarball I created.

Executing `build.sh` fails with the following error (excerpt, [full debug log here](https://gist.githubusercontent.com/anonymous/aaf872fd5f69600ba365bd201002442d/raw/4d571fd7a7022ece0793031d21b96ec234d5ee29/build.log)):

```
osxcross-cmp: relocation error: osxcross-cmp: symbol
_ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE,
version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

Googling this error reveals some Ubuntu users that have this problem in other contexts unrelated to OSXCross ([example](https://stackoverflow.com/questions/19386651/how-to-fix-usr-lib-libstdc-so-6-version-glibcxx-3-4-15-not-found)).

If you think this is an instance of that problem and unrelated to OSXCross, feel free to close. I just wondered whether this is perhaps a known (solved?) problem.

**Comment by tpoechtrager** [comment]
Try `LDFLAGS="-static-libstdc++" ./build.sh`

**Comment by tjanson** [comment]
Bingo! Thanks a lot!
